#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.Web.Mvc.SharedViews.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\ChangedByInfo.cshtml"
    using Kesco.ObjectModel;
    
    #line default
    #line hidden
    using Kesco.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/ChangedByInfo.cshtml")]
    public class ChangedByInfo : Kesco.Web.Mvc.SharedViews.SharedViewPage<Kesco.ObjectModel.ITrackableEntity>
    {
        public ChangedByInfo()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Shared\DisplayTemplates\ChangedByInfo.cshtml"
  
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");
	string name = ViewData.TemplateInfo.HtmlFieldPrefix;
	ModelMetadata metaData = ViewData.ModelMetadata;


            
            #line default
            #line hidden
WriteLiteral("\r\n\t<div style=\"text-align: right; color: #AA2222; padding: 2px;\" data-bind=\"\r\n\t\tv" +
"isible: ");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\ChangedByInfo.cshtml"
       Write(name);

            
            #line default
            #line hidden
WriteLiteral(".ChangedBy\r\n\t\t\"\r\n\t\t>&nbsp;<small class=\"ui-widget-content no-border\">\r\n\t\t");


            
            #line 13 "..\..\Views\Shared\DisplayTemplates\ChangedByInfo.cshtml"
Write(Html.Label("ChangedBy"));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 13 "..\..\Views\Shared\DisplayTemplates\ChangedByInfo.cshtml"
                      Write(Html.Display("ChangedBy"));

            
            #line default
            #line hidden
WriteLiteral(" | ");


            
            #line 13 "..\..\Views\Shared\DisplayTemplates\ChangedByInfo.cshtml"
                                                   Write(Html.Display("ChangedDate"));

            
            #line default
            #line hidden
WriteLiteral("</small>&nbsp;</div> \r\n");


        }
    }
}
#pragma warning restore 1591
