#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.Web.Mvc.SharedViews.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
    using Kesco;
    
    #line default
    #line hidden
    using Kesco.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Hyperlink.cshtml")]
    public class Hyperlink : Kesco.Web.Mvc.SharedViews.SharedViewPage<string>
    {
        public Hyperlink()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
  
	ModelMetadata metadata = ViewData.ModelMetadata;
	string contactIcon = (ViewData["contactIcon"] ?? String.Empty).ToString();
	string phoneType = (ViewData["PhoneType"] ?? 
			(metadata.AdditionalValues.ContainsKey("PhoneType") ? metadata.AdditionalValues["PhoneType"] : "")).ToString();


            
            #line default
            #line hidden

            
            #line 9 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
 if (String.IsNullOrEmpty(Model)) {

            
            #line default
            #line hidden
WriteLiteral("\t");

WriteLiteral(" ");


            
            #line 10 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
Write(ViewData.ModelMetadata.NullDisplayText);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 11 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
} else {
	var hyperlinks = @Model.GetUriList();
	bool showContactIcon = !String.IsNullOrEmpty(contactIcon);
	string contactIconTagBegin = (showContactIcon)
						? @"<span style='position: relative; top: 0px; left: 0px; padding-left: 20px;' ><img src='{0}'  style='position: absolute; top: -2px; left: 1px; cursor: pointer;'   
							title='{1}'
							alt='{1}'
							/>".FormatWith(
							WebAssetImage(contactIcon), 
							Kesco.Web.Mvc.SharedViews.Localization.Resources.ContactControl_CommunicateWithContact
						)
						: String.Empty;
	string contactIconTagEnd = (showContactIcon)
		? @"</span>" : String.Empty;
	foreach(var hyperlink in hyperlinks) {

            
            #line default
            #line hidden
WriteLiteral("\t\t");

WriteLiteral(" ");


            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
Write(Html.Raw(contactIconTagBegin));

            
            #line default
            #line hidden
WriteLiteral("<a href=\'");


            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
                                        Write(hyperlink.Value);

            
            #line default
            #line hidden
WriteLiteral("\' target=\'_blank\' \r\n");



WriteLiteral("\t\t");

WriteLiteral("\t\ttitle=\'");


            
            #line 27 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
         Write(Kesco.Web.Mvc.SharedViews.Localization.Resources.ContactControl_CommunicateWithContact);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n");



WriteLiteral("\t\t");

WriteLiteral("\t\talt=\'");


            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
       Write(Kesco.Web.Mvc.SharedViews.Localization.Resources.ContactControl_CommunicateWithContact);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n");



WriteLiteral("\t\t");

WriteLiteral(" >");


            
            #line 29 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
  Write(hyperlink.Key);

            
            #line default
            #line hidden
WriteLiteral("</a>");


            
            #line 29 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
                     Write(Html.Raw(contactIconTagEnd));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 30 "..\..\Views\Shared\DisplayTemplates\Hyperlink.cshtml"
	}
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
