#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Kesco.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Phone.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Phone_cshtml_ : Kesco.Web.Mvc.SharedViews.SharedViewPage<string>
    {
        public _Views_Shared_DisplayTemplates_Phone_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
  
	ModelMetadata metadata = ViewData.ModelMetadata;
	string icon = (ViewData["PhoneIcon"] ?? ViewData["contactIcon"] ?? (metadata.AdditionalValues.ContainsKey("PhoneIcon") ? metadata.AdditionalValues["PhoneIcon"] : String.Empty)).ToString();
	string phoneType = (ViewData["PhoneType"] ?? 
			(metadata.AdditionalValues.ContainsKey("PhoneType") ? metadata.AdditionalValues["PhoneType"] : "")).ToString();
	string phoneNumber = (ViewData["PhoneNumber"] ??
			(metadata.AdditionalValues.ContainsKey("PhoneNumber") ? metadata.AdditionalValues["PhoneNumber"] : Model)).ToString();
	string cssClass = (ViewData["CssClass"] ??
			(metadata.AdditionalValues.ContainsKey("CssClass") ? metadata.AdditionalValues["CssClass"] : String.Empty)).ToString();

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
 if (String.IsNullOrEmpty(Model)) {

            
            #line default
            #line hidden
WriteLiteral("\t");

WriteLiteral(" ");

            
            #line 13 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
Write(ViewData.ModelMetadata.NullDisplayText);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
} else {
	if (!String.IsNullOrWhiteSpace(phoneNumber)) {
		if (icon != String.Empty) {

            
            #line default
            #line hidden
WriteLiteral("\t");

WriteLiteral(" <span class=\"phoneContact ");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                          Write(cssClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

WriteLiteral("\t");

WriteLiteral(" <img src=\"");

            
            #line 18 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
         Write(WebAssetImage(icon));

            
            #line default
            #line hidden
WriteLiteral("\" \r\n");

WriteLiteral("\t");

WriteLiteral("\t\ttitle=\"");

            
            #line 19 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
        Write(Kesco.Web.Mvc.SharedViews.Localization.Resources.ContactControl_CommunicateWithContact);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n");

WriteLiteral("\t");

WriteLiteral("\t\talt=\"");

            
            #line 20 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
      Write(Kesco.Web.Mvc.SharedViews.Localization.Resources.ContactControl_CommunicateWithContact);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n");

WriteLiteral("\t");

WriteLiteral("\t\tonclick=\"ViewModel.makeCall(\'");

            
            #line 21 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                              Write(HttpUtility.UrlEncode(Model.Replace(" ", "")));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 21 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                                                                                  Write(Model.Replace(" ", "").Replace("+", "").Replace("(", "").Replace(")", "").Replace(".", "+"));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 21 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                                                                                                                                                                                    Write(System.Globalization.CultureInfo.CurrentUICulture.ToString());

            
            #line default
            #line hidden
WriteLiteral("\')\"\r\n");

WriteLiteral("\t");

WriteLiteral("\t/>\r\n");

            
            #line 23 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
		}
        //#XXX

            
            #line default
            #line hidden
WriteLiteral("\t");

WriteLiteral("<a href=\"#\" class=\"phoneContactLink ");

            
            #line 25 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                                   Write((icon == String.Empty)?cssClass:String.Empty);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n");

WriteLiteral("         \t");

WriteLiteral(" onclick=\"ViewModel.makeCall(\'");

            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                                      Write(HttpUtility.UrlEncode(Model.Replace(" ", "")));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                                                                                          Write(HttpUtility.UrlEncode(phoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
                                                                                                                                   Write(System.Globalization.CultureInfo.CurrentUICulture.ToString());

            
            #line default
            #line hidden
WriteLiteral("\'); return false;\"\r\n");

WriteLiteral("      \t");

WriteLiteral(" title=\" ");

            
            #line 27 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
              Write(Kesco.Web.Mvc.SharedViews.Localization.Resources.ContactControl_CommunicateWithContact);

            
            #line default
            #line hidden
WriteLiteral(" \"\r\n");

WriteLiteral("         \t");

WriteLiteral(" alt=\"");

            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
              Write(Kesco.Web.Mvc.SharedViews.Localization.Resources.ContactControl_CommunicateWithContact);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n");

WriteLiteral("         \t");

WriteLiteral(">\r\n");

            
            #line 30 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
	}
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
Write(Model);

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
            
    if (!String.IsNullOrWhiteSpace(phoneNumber))
    {

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 35 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
        if (icon != String.Empty)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n");

WriteLiteral("</span>\r\n");

            
            #line 39 "..\..\Views\Shared\DisplayTemplates\Phone.cshtml"
		}
	}
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
