#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.Web.Mvc.SharedViews.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Kesco.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/ValidationResults.cshtml")]
    public partial class ValidationResults : Kesco.Web.Mvc.SharedViews.SharedViewPage<Kesco.Web.Mvc.Validation.ValidationResults>
    {
        public ValidationResults()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\DisplayTemplates\ValidationResults.cshtml"
  
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");

	string name = ViewData.TemplateInfo.HtmlFieldPrefix;
	ModelMetadata metaData = ViewData.ModelMetadata;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" data-bind=\"if:  ViewModel.");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\ValidationResults.cshtml"
                           Write(name);

            
            #line default
            #line hidden
WriteLiteral(".Messages() != null &&  ViewModel.");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\ValidationResults.cshtml"
                                                                    Write(name);

            
            #line default
            #line hidden
WriteLiteral(".Messages().length > 0\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" style=\"font-size: 7pt\"");

WriteLiteral(" data-bind=\"css: \'validation-error\', foreach: ViewModel.");

            
            #line 9 "..\..\Views\Shared\DisplayTemplates\ValidationResults.cshtml"
                                                                                Write(name);

            
            #line default
            #line hidden
WriteLiteral(".Messages\"");

WriteLiteral(">\t\t\r\n\t\t<div");

WriteLiteral(" data-bind=\"html: $data\"");

WriteLiteral("></div>\t\t\r\n\t</div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
