//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.Web.Mvc.SharedViews.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kesco.Web.Mvc.SharedViews.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call.
        /// </summary>
        public static string CheckCall_Call {
            get {
                return ResourceManager.GetString("CheckCall_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking....
        /// </summary>
        public static string CheckCall_Checking {
            get {
                return ResourceManager.GetString("CheckCall_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string CheckCall_Error {
            get {
                return ResourceManager.GetString("CheckCall_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The cancellation of the call failed..
        /// </summary>
        public static string CheckCall_Error_CallCancellationFailed {
            get {
                return ResourceManager.GetString("CheckCall_Error_CallCancellationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communicate with the contact.
        /// </summary>
        public static string ContactControl_CommunicateWithContact {
            get {
                return ResourceManager.GetString("ContactControl_CommunicateWithContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Documents arhive communication error .
        /// </summary>
        public static string Documents_Controls_DocumentsArhiveErrorMessage {
            get {
                return ResourceManager.GetString("Documents_Controls_DocumentsArhiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string DossierEmployeeInfo_Contacts_Email {
            get {
                return ResourceManager.GetString("DossierEmployeeInfo_Contacts_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messanger.
        /// </summary>
        public static string DossierEmployeeInfo_Contacts_Messanger {
            get {
                return ResourceManager.GetString("DossierEmployeeInfo_Contacts_Messanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Phone.
        /// </summary>
        public static string DossierEmployeeInfo_Contacts_WorkPhone {
            get {
                return ResourceManager.GetString("DossierEmployeeInfo_Contacts_WorkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No contacts..
        /// </summary>
        public static string EmployeeContacts_NoContacts {
            get {
                return ResourceManager.GetString("EmployeeContacts_NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string GUI_Button_Cancel {
            get {
                return ResourceManager.GetString("GUI_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string GUI_Button_Close {
            get {
                return ResourceManager.GetString("GUI_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string GUI_Button_Copy {
            get {
                return ResourceManager.GetString("GUI_Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string GUI_Button_Create {
            get {
                return ResourceManager.GetString("GUI_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string GUI_Button_Delete {
            get {
                return ResourceManager.GetString("GUI_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string GUI_Button_Edit {
            get {
                return ResourceManager.GetString("GUI_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish call.
        /// </summary>
        public static string GUI_Button_FinishCall {
            get {
                return ResourceManager.GetString("GUI_Button_FinishCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string GUI_Button_Help {
            get {
                return ResourceManager.GetString("GUI_Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string GUI_Button_OK {
            get {
                return ResourceManager.GetString("GUI_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string GUI_Button_Refresh {
            get {
                return ResourceManager.GetString("GUI_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string GUI_Button_Save {
            get {
                return ResourceManager.GetString("GUI_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string GUI_Button_Select {
            get {
                return ResourceManager.GetString("GUI_Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string GUI_Button_View {
            get {
                return ResourceManager.GetString("GUI_Button_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occured while performing the action on the server..
        /// </summary>
        public static string GUI_Message_AjaxRequestError {
            get {
                return ResourceManager.GetString("GUI_Message_AjaxRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string GUI_Message_Loading {
            get {
                return ResourceManager.GetString("GUI_Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing....
        /// </summary>
        public static string GUI_Message_Refreshing {
            get {
                return ResourceManager.GetString("GUI_Message_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Phone.
        /// </summary>
        public static string GUI_PhoneContact_ChooseAnotherPhone {
            get {
                return ResourceManager.GetString("GUI_PhoneContact_ChooseAnotherPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Phone.
        /// </summary>
        public static string GUI_PhoneContact_ChooseDefaultPhone {
            get {
                return ResourceManager.GetString("GUI_PhoneContact_ChooseDefaultPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email address {0} is not valid. Please check..
        /// </summary>
        public static string Kesco_Web_Mvc_SharedApp_ClientSideViewModel_IncorrectEmail {
            get {
                return ResourceManager.GetString("Kesco_Web_Mvc_SharedApp_ClientSideViewModel_IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New entry.
        /// </summary>
        public static string Kesco_Web_Mvc_SharedApp_EditorTemplate_UniqueID_NewEntry {
            get {
                return ResourceManager.GetString("Kesco_Web_Mvc_SharedApp_EditorTemplate_UniqueID_NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application Error.
        /// </summary>
        public static string Kesco_Web_Mvc_SharedApp_LBL_13112 {
            get {
                return ResourceManager.GetString("Kesco_Web_Mvc_SharedApp_LBL_13112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to see the details....
        /// </summary>
        public static string Kesco_Web_Mvc_SharedApp_LBL_13113 {
            get {
                return ResourceManager.GetString("Kesco_Web_Mvc_SharedApp_LBL_13113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Male.
        /// </summary>
        public static string Kesco_Web_Mvc_SharedApp_LBL_20000 {
            get {
                return ResourceManager.GetString("Kesco_Web_Mvc_SharedApp_LBL_20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Female.
        /// </summary>
        public static string Kesco_Web_Mvc_SharedApp_LBL_20001 {
            get {
                return ResourceManager.GetString("Kesco_Web_Mvc_SharedApp_LBL_20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call has been accepted..
        /// </summary>
        public static string LINECALLSTATE_ACCEPTED {
            get {
                return ResourceManager.GetString("LINECALLSTATE_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call is receiving a busy tone..
        /// </summary>
        public static string LINECALLSTATE_BUSY {
            get {
                return ResourceManager.GetString("LINECALLSTATE_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call is a member of a conference call.
        /// </summary>
        public static string LINECALLSTATE_CONFERENCED {
            get {
                return ResourceManager.GetString("LINECALLSTATE_CONFERENCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call has been established..
        /// </summary>
        public static string LINECALLSTATE_CONNECTED {
            get {
                return ResourceManager.GetString("LINECALLSTATE_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dialing digits on the call....
        /// </summary>
        public static string LINECALLSTATE_DIALING {
            get {
                return ResourceManager.GetString("LINECALLSTATE_DIALING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ready to dial....
        /// </summary>
        public static string LINECALLSTATE_DIALTONE {
            get {
                return ResourceManager.GetString("LINECALLSTATE_DIALTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the remote party has disconnected from the call..
        /// </summary>
        public static string LINECALLSTATE_DISCONNECTED {
            get {
                return ResourceManager.GetString("LINECALLSTATE_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no call is currently active.
        /// </summary>
        public static string LINECALLSTATE_IDLE {
            get {
                return ResourceManager.GetString("LINECALLSTATE_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call is being offered to the station..
        /// </summary>
        public static string LINECALLSTATE_OFFERING {
            get {
                return ResourceManager.GetString("LINECALLSTATE_OFFERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call is on hold..
        /// </summary>
        public static string LINECALLSTATE_ONHOLD {
            get {
                return ResourceManager.GetString("LINECALLSTATE_ONHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call is proceeding through the telephone network..
        /// </summary>
        public static string LINECALLSTATE_PROCEEDING {
            get {
                return ResourceManager.GetString("LINECALLSTATE_PROCEEDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the station to be called has been reached, a ringback....
        /// </summary>
        public static string LINECALLSTATE_RINGBACK {
            get {
                return ResourceManager.GetString("LINECALLSTATE_RINGBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the call is receiving a special information..
        /// </summary>
        public static string LINECALLSTATE_SPECIALINFO {
            get {
                return ResourceManager.GetString("LINECALLSTATE_SPECIALINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на unknown.
        /// </summary>
        public static string LINECALLSTATE_UNKNOWN {
            get {
                return ResourceManager.GetString("LINECALLSTATE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A device is alerting (ringing)..
        /// </summary>
        public static string LocalConnectionState_t_CS_ALERTING {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_ALERTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A device is actively participating in a call.
        /// </summary>
        public static string LocalConnectionState_t_CS_CONNECT {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A failure to connect to the calling device or to the called device..
        /// </summary>
        public static string LocalConnectionState_t_CS_FAIL {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A device inactively participates in a call (HELD)..
        /// </summary>
        public static string LocalConnectionState_t_CS_HOLD {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A device is requesting service..
        /// </summary>
        public static string LocalConnectionState_t_CS_INITIATE {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_INITIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A device participates in a call, but its state is not known..
        /// </summary>
        public static string LocalConnectionState_t_CS_NONE {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A device does not participate in a call.
        /// </summary>
        public static string LocalConnectionState_t_CS_NULL {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A device is trying to establish a connection with a call..
        /// </summary>
        public static string LocalConnectionState_t_CS_QUEUED {
            get {
                return ResourceManager.GetString("LocalConnectionState_t_CS_QUEUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call {0} &amp;lt;-&amp;gt; {1}.
        /// </summary>
        public static string MakeCall_Call {
            get {
                return ResourceManager.GetString("MakeCall_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A call cannot be established from this phone..
        /// </summary>
        public static string MakeCall_CallCannotBeEstablished {
            get {
                return ResourceManager.GetString("MakeCall_CallCannotBeEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A phone with {0} number is not found in available equipment..
        /// </summary>
        public static string MakeCall_PhoneNotFound {
            get {
                return ResourceManager.GetString("MakeCall_PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A phone is not specified..
        /// </summary>
        public static string MakeCall_PhoneNotSpecified {
            get {
                return ResourceManager.GetString("MakeCall_PhoneNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout.
        /// </summary>
        public static string MakeCall_Timeout {
            get {
                return ResourceManager.GetString("MakeCall_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try to call from another phone.
        /// </summary>
        public static string MakeCall_TryToCallFromAnotherPhone {
            get {
                return ResourceManager.GetString("MakeCall_TryToCallFromAnotherPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No contacts..
        /// </summary>
        public static string PersonContacts_NoContacts {
            get {
                return ResourceManager.GetString("PersonContacts_NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create juridical person.
        /// </summary>
        public static string PersonControl_CreateJuridalPerson {
            get {
                return ResourceManager.GetString("PersonControl_CreateJuridalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create natural person.
        /// </summary>
        public static string PersonControl_CreateNaturalPerson {
            get {
                return ResourceManager.GetString("PersonControl_CreateNaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call.
        /// </summary>
        public static string PhoneCalling_Dialog_Button_Call {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_Button_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на in.
        /// </summary>
        public static string PhoneCalling_Dialog_Button_Call_In_Seconds {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_Button_Call_In_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sec..
        /// </summary>
        public static string PhoneCalling_Dialog_Button_Call_Seconds {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_Button_Call_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call Throuh.
        /// </summary>
        public static string PhoneCalling_Dialog_ChooseDefaultPhone_Table_CallThrouh {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_ChooseDefaultPhone_Table_CallThrouh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a phone which should be used to call the {0} number..
        /// </summary>
        public static string PhoneCalling_Dialog_ChooseDefaultPhone_Table_Caption {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_ChooseDefaultPhone_Table_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string PhoneCalling_Dialog_ChooseDefaultPhone_Table_Description {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_ChooseDefaultPhone_Table_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equipment.
        /// </summary>
        public static string PhoneCalling_Dialog_ChooseDefaultPhone_Table_Equipment {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_ChooseDefaultPhone_Table_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string PhoneCalling_Dialog_ChooseDefaultPhone_Table_Location {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_ChooseDefaultPhone_Table_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string PhoneCalling_Dialog_ChooseDefaultPhone_Table_Phone {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_ChooseDefaultPhone_Table_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string PhoneCalling_Dialog_ChooseDefaultPhone_Table_PhoneType {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_ChooseDefaultPhone_Table_PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please specify a phone from which to you want to make a call..
        /// </summary>
        public static string PhoneCalling_Dialog_Message_SpecifyPhoneToMakeACall {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_Message_SpecifyPhoneToMakeACall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No phones available.
        /// </summary>
        public static string PhoneCalling_Dialog_NoPhonesAvailable {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_NoPhonesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call.
        /// </summary>
        public static string PhoneCalling_Dialog_PhoneCallState_Call {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_PhoneCallState_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting....
        /// </summary>
        public static string PhoneCalling_Dialog_PhoneCallState_Connecting {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_PhoneCallState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string PhoneCalling_Dialog_PhonesLoading {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_PhonesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as main working telephone on the computer..
        /// </summary>
        public static string PhoneCalling_Dialog_SaveAsMainWorkingPhoneAtThisLocation {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_SaveAsMainWorkingPhoneAtThisLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calling....
        /// </summary>
        public static string PhoneCalling_Dialog_Title {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calling {0}....
        /// </summary>
        public static string PhoneCalling_Dialog_Title2 {
            get {
                return ResourceManager.GetString("PhoneCalling_Dialog_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please specify an email address to write..
        /// </summary>
        public static string PhoneCalling_PleaseSpecifyEmailToWrite {
            get {
                return ResourceManager.GetString("PhoneCalling_PleaseSpecifyEmailToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please specify a target phone number to call..
        /// </summary>
        public static string PhoneCalling_PleaseSpecifyPhoneToCall {
            get {
                return ResourceManager.GetString("PhoneCalling_PleaseSpecifyPhoneToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string QTip_LoadingStatus {
            get {
                return ResourceManager.GetString("QTip_LoadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No data.
        /// </summary>
        public static string ResourceView_NoData {
            get {
                return ResourceManager.GetString("ResourceView_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced Search.
        /// </summary>
        public static string SelectBox_AdvancedSearch {
            get {
                return ResourceManager.GetString("SelectBox_AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string SelectBox_View {
            get {
                return ResourceManager.GetString("SelectBox_View", resourceCulture);
            }
        }
    }
}
