//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.DataAccess.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kesco.DataAccess.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You don&apos;t have enough permission .
        /// </summary>
        internal static string AccessDenied_ValidationError {
            get {
                return ResourceManager.GetString("AccessDenied_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data base is not avaliable now.
        /// </summary>
        internal static string ConnectionFailure_ValidationError {
            get {
                return ResourceManager.GetString("ConnectionFailure_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Response on the query couldn&apos;t be received by reason of deadlock was detected.
        /// </summary>
        internal static string DeadLockDetected_ValidationError {
            get {
                return ResourceManager.GetString("DeadLockDetected_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There was no rensponse from data base server.
        /// </summary>
        internal static string NotRunningServer_ValidationError {
            get {
                return ResourceManager.GetString("NotRunningServer_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An existing connection was forcibly closed by remote host.
        /// </summary>
        internal static string RemoteHostUnreachable_ValidationError {
            get {
                return ResourceManager.GetString("RemoteHostUnreachable_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requested data base is not avaliable for the current user .
        /// </summary>
        internal static string RequestedDataBaseNotAvaliable_ValidationError {
            get {
                return ResourceManager.GetString("RequestedDataBaseNotAvaliable_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL Server does not exist or access denied.
        /// </summary>
        internal static string ServerDBNotExistOrAccessDenied_ValidationError {
            get {
                return ResourceManager.GetString("ServerDBNotExistOrAccessDenied_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time to query execution has been expired .
        /// </summary>
        internal static string TimeoutExpired_ValidationError {
            get {
                return ResourceManager.GetString("TimeoutExpired_ValidationError", resourceCulture);
            }
        }
    }
}
