#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
    using Kesco.Persons.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    using MvcJqGrid;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/PersonTypes.cshtml")]
    public partial class _Views_Shared_EditorTemplates_PersonTypes_cshtml_ : Kesco.Persons.Web.SiteViewPage<IList<int>>
    {
        public _Views_Shared_EditorTemplates_PersonTypes_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
   
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");
	string PersonThemes = ViewData.TemplateInfo.HtmlFieldPrefix;
	string PersonThemesVM = "window.ViewModel." + ViewData.TemplateInfo.HtmlFieldPrefix;
	string PersonThemesAndCatalogs = ViewData.TemplateInfo.HtmlFieldPrefix + "AndCatalogs";

            
            #line default
            #line hidden
WriteLiteral("\r\n\t<table >\r\n\t<tr>\r\n\t\t<th>\r\n\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-bind=\"\r\n\t\t\t\t\t\t\tclick: openChooseThemesDialog,\r\n\t\t\t\t\t\t\tjqueryui: {widget: \'b" +
"utton\', options: { icons: { primary: \'ui-icon-plus\'} } }\"");

WriteAttribute("title", Tuple.Create("\r\n\t\t\t\t\ttitle=\"", 602), Tuple.Create("\"", 696)
            
            #line 18 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
, Tuple.Create(Tuple.Create("", 616), Tuple.Create<System.Object, System.Int32>(Kesco.Persons.Web.Localization.Resources.Views_PersonThemes_ChooseButtonTitle
            
            #line default
            #line hidden
, 616), false)
);

WriteLiteral(" id=\"btnPersonTypes\"");

WriteLiteral("\r\n\t\t\t\t>\r\n\t\t\t\t<span");

WriteLiteral(" data-bind=\"visible: Model.PersonThemesAndCatalogs().length == 0\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
                                                                       Write(global::Resources.Resources.Kesco_Persons_CreateIndividual_2105);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t\t<span");

WriteLiteral(" data-bind=\"visible: Model.PersonThemesAndCatalogs().length != 0\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
                                                                       Write(global::Resources.Resources.Kesco_Persons_CreateIndividual_2104a);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t</button>\r\n            </br>\r\n            <span");

WriteLiteral(" id=\"personTypesValidationMessage\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" style=\"COLOR: #ff0000; font-weight:100; font-size: 10px;\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
                                                                             Write(global::Resources.Resources.Kesco_Persons_CreateJuridical_2202);

            
            #line default
            #line hidden
WriteLiteral("</label> \r\n           </span>\r\n\t\t</th>\r\n\t\t<th");

WriteLiteral(" data-bind=\"visible: Model.PersonThemesAndCatalogs().length != 0\r\n\t\t\"");

WriteLiteral(">");

            
            #line 29 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
Write(Kesco.Persons.Web.Localization.Resources.Views_PersonTypes_Catalogs);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n\t</tr>\r\n\t<tbody");

WriteLiteral(" data-bind=\"foreach: Model.PersonThemesAndCatalogs\"");

WriteLiteral(" >\r\n\t<tr>\r\n\t\t<td >\r\n\t\t\t<span");

WriteLiteral(" data-bind=\"\r\n\t\t\t\ttext: $data.Name\r\n\t\t\t\"");

WriteLiteral("></span>\r\n\t\t</td>\r\n\t\t<td");

WriteLiteral(" data-bind=\"foreach: $data.Catalogs\"");

WriteLiteral("><span");

WriteLiteral(" data-bind=\"if: $index\"");

WriteLiteral(">,</span> <span");

WriteLiteral(" data-bind=\"text: $data\"");

WriteLiteral("></span></td>\r\n\t</tr>\r\n\t</tbody>\r\n\t</table>\r\n\r\n");

            
            #line 43 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
Write(Html.CommonScriptCode("Persons_PersonType_Methods",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"<script>
     !(function (scope, $, undefined) {
         var vm = scope.ViewModel || {}; scope.ViewModel = vm;
         vm.openChooseThemesDialog = function () {
             vm.dispatchModelCommand('ChoosePersonTypes', null);
         };
         vm.checkPersonThemes = function () {
             vm.dispatchModelCommand('CheckPersonThemes', null);
         };
         vm.setPersonTypes = function () {
             setTypesValid(true);
             vm.dispatchModelCommand('SetPersonTypes', null);
         };

     })(window, jQuery);

	function setTypesValid(flag) {
	    var validationMsg = document.getElementById('personTypesValidationMessage');
	    if (flag == true || flag == ""true"") {
	        if (validationMsg != null && validationMsg != """") validationMsg.style.display = ""none"";
	    }
	    if (flag == false || flag == ""false"") {
	        if (validationMsg != null && validationMsg != """") validationMsg.style.display = ""table"";
	    }
	}

</script>");

            
            #line 70 "..\..\Views\Shared\EditorTemplates\PersonTypes.cshtml"
       })));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
