#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\EditorTemplates\TerritoryField.cshtml"
    using Kesco.Persons.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\EditorTemplates\TerritoryField.cshtml"
    using Kesco.Territories.Controls.ComponentModel;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\EditorTemplates\TerritoryField.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    using MvcJqGrid;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/TerritoryField.cshtml")]
    public partial class _Views_Shared_EditorTemplates_TerritoryField_cshtml_ : Kesco.Persons.Web.SiteViewPage<int?>
    {
        public _Views_Shared_EditorTemplates_TerritoryField_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\EditorTemplates\TerritoryField.cshtml"
  
    var descriptor = new TerritorySelectAttribute();
	descriptor.OnMetadataCreated(ViewData.ModelMetadata);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\TerritoryField.cshtml"
Write(Html.EditorFor(m => m, "PersonTypesSelect", new
{
	KescoSelect = descriptor,
	KescoSelectCommands = ViewData.ModelMetadata.AdditionalValues["KescoSelectCommands"]
}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
