#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
    using Kesco.ObjectModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Object.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Object_cshtml : Kesco.Persons.Web.SiteViewPage<object>
    {
        public _Views_Shared_DisplayTemplates_Object_cshtml()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
  
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");


            
            #line default
            #line hidden

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
 if (Model == null)
{
	
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
Write(ViewData.ModelMetadata.NullDisplayText);

            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
                                        
}
else
{

            
            #line default
            #line hidden
WriteLiteral("\t<table cellpadding=\"3\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");


            
            #line 13 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
 	foreach (var prop in ViewData.ModelMetadata.Properties.Where(pm => pm.ShowForDisplay && !ViewData.TemplateInfo.Visited(pm))) {
		if (prop.HideSurroundingHtml) {
			
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
Write(Html.Display(prop.PropertyName));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
                                   
		} else {

            
            #line default
            #line hidden
WriteLiteral("\t\t<tr valign=\"top\">\r\n\t\t\t<td style=\"width: 200px; padding-left: 20px;\">\r\n\t\t\t\t<div " +
"class=\"display-label\">");


            
            #line 19 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
                          Write(prop.GetDisplayName());

            
            #line default
            #line hidden
WriteLiteral(":</div>\r\n\t\t\t</td>\r\n\t\t\t<td style=\"padding-left: 10px;\">\r\n\t\t\t\t<div class=\"display-f" +
"ield\">\r\n\t\t\t\t\t<span id=\"model_");


            
            #line 23 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
                 Write(prop.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 23 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
                                      Write(Html.Display(prop.PropertyName, new { parentModel = Model }));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t\t</div>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n");


            
            #line 27 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
		}
	}

            
            #line default
            #line hidden
WriteLiteral("\t</table>\r\n");


            
            #line 30 "..\..\Views\Shared\DisplayTemplates\Object.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
