#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
    using Kesco.Persons.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
    using Kesco.Persons.Web.Models;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
    using Kesco.Persons.Web.Models.Requisites;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
    using Kesco.Web.Mvc.SharedViews;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
    using Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Requisites.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Requisites_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Persons.Web.Models.Requisites.Requisites>
    {
        public _Views_Shared_DisplayTemplates_Requisites_cshtml()
        {
        }
        public override void Execute()
        {








            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
   
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");
	string name = ViewData.TemplateInfo.HtmlFieldPrefix;
	string viewModelRequisites = "window.ViewModel." + name;


            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t<a href=\"javascript: void(0);\" id=\"Requisites_Edit_Button_");


            
            #line 14 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                                        Write(Model.ID);

            
            #line default
            #line hidden
WriteLiteral("\" data-bind=\"\r\n\t\t\tattr: { \r\n\t\t\t\talt: ");


            
            #line 16 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
     Write(name);

            
            #line default
            #line hidden
WriteLiteral(".TerritoryID()?\'\':\'");


            
            #line 16 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                               Write(Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Requisites_SpecifyCountryOfRegistration);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n\t\t\t\ttitle: ");


            
            #line 17 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
       Write(name);

            
            #line default
            #line hidden
WriteLiteral(".TerritoryID()?\'\':\'");


            
            #line 17 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                 Write(Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Requisites_SpecifyCountryOfRegistration);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n\t\t\t},\r\n\t\t\tenable2: ");


            
            #line 19 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".TerritoryID(),\r\n\t\t\tclick: editJuridicalRequisites\r\n\t\t\"><span class=\"ui-icon text" +
"-ui-icon\" data-bind=\"\r\n\t\t\t\tcss: { \'ui-icon-pencil\': ");


            
            #line 22 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                         Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsSpecified, \'ui-icon-plus\': !");


            
            #line 22 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                                               Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsSpecified() }\r\n\t\t\t\"></span><span data-bind=\"\r\n\t\t\t\tvisible: !");


            
            #line 24 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
          Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsSpecified()\r\n\t\t\t\">");


            
            #line 25 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
 Write(global::Resources.Resources.Kesco_Persons_Web_VW_142);

            
            #line default
            #line hidden
WriteLiteral("</span></a>\r\n            </br>\r\n            <span id=\"requisitesValidationMessage" +
"\" style=\"display: none\">\r\n                 <label style=\"COLOR: #ff0000; font-we" +
"ight:100; font-size: 10px;\">");


            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                                                              Write(Kesco.Persons.Web.Localization.Resources.Validation_JuridicalPerson_RequisitesMustBeSpecified);

            
            #line default
            #line hidden
WriteLiteral("</label> \r\n\t\t</span>\r\n        <span style=\"font-style: italic\" data-bind=\"\r\n\t\t\tvi" +
"sible: ");


            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
        Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsSpecified,\r\n\t\t\ttext: ");


            
            #line 32 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
     Write(name);

            
            #line default
            #line hidden
WriteLiteral("_ValidRange\" ></span>\r\n\t<table cellpadding=\"0\" cellspacing=\"0\">\r\n    <tr>\r\n      " +
"  <td colspan=\"2\" data-bind=\"\r\n\t\t\t\tstyle: { \'border-bottom\': (");


            
            #line 36 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                           Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsSpecified())?\'1px solid;\':\'\' }\r\n\t\t\t\"\r\n\t\t\t>\r\n        </td>\r\n    </tr>\r\n    <tr " +
"data-bind=\"visible: ");


            
            #line 41 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".IncorporationFormID() &&  ");


            
            #line 41 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                                          Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsRussia()\">\r\n        <td>\r\n\t\t\t");


            
            #line 43 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 46 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n    <tr data-bind=\"visible: ");


            
            #line 49 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".ShortNameRus\">\r\n        <td>\r\n\t\t\t");


            
            #line 51 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.ShortNameRus));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 54 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.ShortNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n    <tr data-bind=\"visible: ");


            
            #line 57 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".ShortNameLat\">\r\n        <td>\r\n\t\t\t");


            
            #line 59 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.ShortNameLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 62 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.ShortNameLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n    <tr data-bind=\"visible: ");


            
            #line 65 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".FullName() &&  ");


            
            #line 65 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                               Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsRussia()\">\r\n        <td>\r\n\t\t\t");


            
            #line 67 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.FullName));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 70 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n    <tr data-bind=\"visible: ");


            
            #line 73 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".OKONH() &&  ");


            
            #line 73 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                            Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsRussia()\">\r\n        <td>\r\n\t\t\t");


            
            #line 75 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.OKONH));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 78 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.OKONH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n    <tr data-bind=\"visible: ");


            
            #line 81 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".OKVED() &&  ");


            
            #line 81 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                            Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsRussia()\">\r\n        <td>\r\n\t\t\t");


            
            #line 83 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.OKVED));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 86 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.OKVED));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n    <tr data-bind=\"visible: ");


            
            #line 89 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".KPP() &&  ");


            
            #line 89 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                          Write(name);

            
            #line default
            #line hidden
WriteLiteral("_IsRussia()\">\r\n        <td>\r\n\t\t\t");


            
            #line 91 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.KPP));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 94 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.KPP));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n            \r\n    <tr data-bind=\"visible: ");


            
            #line 98 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".RwID\">\r\n        <td>\r\n\t\t\t");


            
            #line 100 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.RwID));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 103 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.RwID));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n            \r\n    <tr data-bind=\"visible: ");


            
            #line 107 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".AddressLegal\">\r\n        <td>\r\n\t\t\t");


            
            #line 109 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 112 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n            \r\n    <tr data-bind=\"visible: ");


            
            #line 116 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".AddressLegalLat\">\r\n        <td>\r\n\t\t\t");


            
            #line 118 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.AddressLegalLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 121 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.AddressLegalLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n            \r\n    <tr data-bind=\"visible: ");


            
            #line 125 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                        Write(name);

            
            #line default
            #line hidden
WriteLiteral(".ShortNameRusGenitive\">\r\n        <td>\r\n\t\t\t");


            
            #line 127 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.LabelFor(m => m.ShortNameRusGenitive));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t</td>\r\n        <td>\r\n\t\t\t");


            
            #line 130 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.DisplayFor(m => m.ShortNameRusGenitive));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n</table>\r\n\r\n");


            
            #line 135 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
Write(Html.CommonScriptCode("Persons_Requisites_Methods",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden

WriteLiteralTo(@__razor_template_writer, @"<script>
     function setRequisitesValid(flag) {
	    var validationMsg = document.getElementById('requisitesValidationMessage');
         if(flag == true || flag == ""true"") {
         if(validationMsg != null && validationMsg != """") validationMsg.style.display = ""none"";
             
         }
          if(flag == false || flag == ""false"") {
         if(validationMsg != null && validationMsg != """") validationMsg.style.display = ""table"";
              
         }
	}

     $(document).ready(function () {
         ");


            
            #line 150 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "_IsSpecified = window.ko.computed(function () {\r\n             setRequisitesValid(" +
"true);\r\n             return ");


            
            #line 152 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".ShortNameRus() || ");


            
            #line 152 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                             WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".ShortNameLat();\r\n         }, window.ViewModel);\r\n\r\n         \t\t");



WriteLiteralTo(@__razor_template_writer, "\r\n         ");


            
            #line 156 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "_IsRussia = window.ko.computed(function () {\r\n             return ");


            
            #line 157 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".TerritoryID() == ");


            
            #line 157 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                            WriteTo(@__razor_template_writer, Kesco.Territories.ObjectModel.Territory.Russia);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ";\r\n         }, window.ViewModel);\r\n\r\n         \t\t");



WriteLiteralTo(@__razor_template_writer, "\r\n         ");


            
            #line 161 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "_ValidRange = window.ko.computed(function () {\r\n             var d1  = ");


            
            #line 162 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".From(), d2 = ");


            
            #line 162 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                           WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".To();\r\n             var phrases = [];\r\n             if (");


            
            #line 164 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".ShortNameRus() || ");


            
            #line 164 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                          WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".ShortNameLat()) {\r\n                 phrases.push(\'");


            
            #line 165 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Requisites_Valid);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\');\r\n\r\n                 if (d1) {\r\n                     phrases.push(\'");


            
            #line 168 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
   WriteTo(@__razor_template_writer, Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Requisites_Valid_From);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\');\r\n                     phrases.push(d1);\r\n                 }\r\n\r\n              " +
"   if (d2) {\r\n                     phrases.push(\'");


            
            #line 173 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
   WriteTo(@__razor_template_writer, Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Requisites_Valid_To);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"');
                     phrases.push(d2);
                 }
             }
             return phrases.join("" "");
			
         }, window.ViewModel);

         // TODO: Сделать универсально
         // 1) параметр путь к объекту в модели, строка
         window.ViewModel.editJuridicalRequisites = function () {
             var areaID = ");


            
            #line 184 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ".TerritoryID();\r\n             if (!areaID) {\r\n                 alertMessage(\'&nbs" +
"p;&nbsp;\', \'");


            
            #line 186 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
              WriteTo(@__razor_template_writer, Resources.Persons_Requisites_SpecifyPersonRegistrationCountry);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\', \'OK\');\r\n                 return;\r\n             }\r\n             var callbackUrl" +
" = encodeURIComponent(\'");


            
            #line 189 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                  WriteTo(@__razor_template_writer, Url.FullPathAction("DialogResult", "Default"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\');\r\n             var url = \'");


            
            #line 190 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
WriteTo(@__razor_template_writer, Url.FullPathAction("Index","Requisites"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "?areaID={1}&return=1&mvc=1&callbackKey=c1&callbackUrl={0}\';\r\n             url = $" +
".validator.format(url, callbackUrl, areaID);\r\n\r\n             window.openPopupWin" +
"dow(url, \r\n                 {\t");



WriteLiteralTo(@__razor_template_writer, "\r\n                     type: \'POST\',\r\n                     callbackUrl: callbackU" +
"rl,\r\n                     Requisites: ko.mapping.toJS(");


            
            #line 197 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                 WriteTo(@__razor_template_writer, viewModelRequisites);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, ")\r\n                 }, \r\n                 function (val) { ");



WriteLiteralTo(@__razor_template_writer, "\r\n                     if (val) {\r\n                         \t\t\t\t\t\t");



WriteLiteralTo(@__razor_template_writer, @"
                         window.ko.mapping.fromJS({ 
                             Model: {
                                 Card: { 
                                     Requisites: window.ko.mapping.toJS(val[0]) 
                                 } 
                             }
                         }, window.ViewModel);
                         setTimeout(function() { $(""#Requisites_Edit_Button_");


            
            #line 209 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
                                            WriteTo(@__razor_template_writer, Model.ID);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\").get(0).focus() }, 200)\r\n                     }\r\n                 }, \"Requisite" +
"s\", 730, 500\r\n             );\r\n         };\r\n\r\n     });\r\n </script>");


            
            #line 216 "..\..\Views\Shared\DisplayTemplates\Requisites.cshtml"
        })));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
