#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Layout2.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout2.cshtml")]
    public partial class _Views_Shared__Layout2_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Web.Mvc.DialogViewModel>
    {
        public _Views_Shared__Layout2_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head >\r\n    <title>");


            
            #line 8 "..\..\Views\Shared\_Layout2.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\t<link rel=\"icon\" href=\'");


            
            #line 9 "..\..\Views\Shared\_Layout2.cshtml"
                   Write(Url.Content("~/favicon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\' type=\"image/x-icon\" />\r\n\t<link rel=\"shortcut icon\" href=\'");


            
            #line 10 "..\..\Views\Shared\_Layout2.cshtml"
                            Write(Url.Content("~/favicon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\' type=\"image/x-icon\" /> \r\n\t\r\n\t");



WriteLiteral("\r\n\t");


            
            #line 13 "..\..\Views\Shared\_Layout2.cshtml"
Write(Html.Partial("PageHeadSection"));

            
            #line default
            #line hidden
WriteLiteral(@"

	<style type=""text/css"">
		body {
			overflow: hidden;	
		}
		.field-validation-error {
			display: block !important;
		}

	</style>

<body>
	<span id=""wndSize"" style=""background-color: transparent; position: absolute; right: 42px; top: 3px;""></span>

	");



WriteLiteral("\r\n\t");


            
            #line 29 "..\..\Views\Shared\_Layout2.cshtml"
Write(Html.Partial("PageScriptsAndSetup"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t");



WriteLiteral("\r\n\t");


            
            #line 32 "..\..\Views\Shared\_Layout2.cshtml"
Write(Html.Partial("ClientSideViewModel", (object) Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\r\n\t");



WriteLiteral("\r\n\t");


            
            #line 35 "..\..\Views\Shared\_Layout2.cshtml"
Write(Html.Partial("DialogResultForm"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t");



WriteLiteral("\r\n\t<div id=\"dialogHeader\" style=\"display: none; border: 1px dashed silver;\" data-" +
"bind=\"visible: PageLoaded\">\r\n\t\t");


            
            #line 39 "..\..\Views\Shared\_Layout2.cshtml"
Write(RenderSection("Header", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n\r\n\t");



WriteLiteral("\r\n\t<div id=\"dialogContentPane\" class=\"ui-widget-content\" style=\"overflow: hidden;" +
" padding: 2px; display: none;\"\r\n\t\tdata-bind=\"visible: PageLoaded\">\r\n\t\t");


            
            #line 45 "..\..\Views\Shared\_Layout2.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n\r\n\t");



WriteLiteral("\r\n\t<div id=\"dialogFooter\" class=\"ui-widget\" style=\"padding: 5px 5px 0px 5px; text" +
"-align: center; display: none;\"\r\n\t\tdata-bind=\"visible: PageLoaded\">\r\n\t\t");


            
            #line 51 "..\..\Views\Shared\_Layout2.cshtml"
Write(RenderSection("Footer", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n\r\n\t");



WriteLiteral("\r\n\t<script language=\"javascript\" type=\"text/javascript\">\r\n\t\t$(document).ready(fun" +
"ction() {\r\n\t\t\tViewModel.PageLoaded(true);\r\n\t\t\tko.applyBindings(ViewModel);\r\n\t\t\tv" +
"ar $window = $(window);\r\n\t\t\t$window.resize();\r\n\t\t});\r\n\t</script>\r\n</body>\r\n</htm" +
"l>\r\n");


        }
    }
}
#pragma warning restore 1591
