#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Requisites\Index.cshtml"
    using Kesco.Persons.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Requisites\Index.cshtml"
    using Kesco.Persons.Web.Localization;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Requisites\Index.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Requisites\Index.cshtml"
    using Kesco.Web.Mvc.UI;
    
    #line default
    #line hidden
    using MvcJqGrid;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Requisites/Index.cshtml")]
    public partial class _Views_Requisites_Index_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Persons.Web.Models.Requisites.ViewModel>
    {
        public _Views_Requisites_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Requisites\Index.cshtml"
  
	Model
		.GetScriptCapabilities()
		.DisableGridScript()
		.DisableTreeScript();
	ViewBag.Title = Model.PageTitle;
	Layout = "~/Views/Shared/_Layout.cshtml";
	string territoryName = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLower() == "ru"?"Name":"Caption";
    /* Ищем в URL параметр hideOldVer, пишем его в сессию. Требуется для скрытия кнопки "Открыть в старой версии"  */
    string hideOldVerRequest = HttpContext.Current.Request["hideOldVer"];
    var hideOldVerSession = HttpContext.Current.Session["hideOldVer"];
    string hideOldVer = "false";

    if (!String.IsNullOrEmpty(hideOldVerRequest))
    {
        HttpContext.Current.Session["hideOldVer"] = hideOldVer = hideOldVerRequest;
    }
    else if (hideOldVerSession != null)
    {
        hideOldVer = hideOldVerSession.ToString();
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n\ttable.formTable td { padding: 4px; }\r\n</style>\r\n\r\n<div");

WriteLiteral(" id=\"formContainer\"");

WriteLiteral(" style=\"overflow: auto;\"");

WriteLiteral(" class=\"ui-widget\"");

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Views\Requisites\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Requisites\Index.cshtml"
       Html.EnableClientValidation(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 35 "..\..\Views\Requisites\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Requisites\Index.cshtml"
     using (Html.BeginForm("Save", "Requisites", FormMethod.Post, new { id = "editForm", name = "editForm", onsubmit = "return false;" })) {
		
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Requisites\Index.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Requisites\Index.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral("\t\t<table");

WriteLiteral(" class=\"formTable\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"2\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" width=\"99%\"");

WriteLiteral(">\r\n\t\t<tr>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" align=\"right\"");

WriteLiteral(" style=\"border-bottom: 1px solid;\"");

WriteLiteral(">\r\n\t\t\t\t<table>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td>");

            
            #line 42 "..\..\Views\Requisites\Index.cshtml"
                        Write(global::Resources.Resources.Kesco_Persons_Web_VW_133);

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" align=\"right\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\Requisites\Index.cshtml"
                                     Write(Html.LabelFor(m => m.Model.From));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" width=\"80\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\Requisites\Index.cshtml"
                                  Write(Html.EditorFor(m => m.Model.From));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" align=\"right\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Requisites\Index.cshtml"
                                     Write(Html.LabelFor(m => m.Model.To));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" width=\"80\"");

WriteLiteral(">");

            
            #line 46 "..\..\Views\Requisites\Index.cshtml"
                                  Write(Html.EditorFor(m => m.Model.To));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t</table>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: TerritoryIsRussia\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 280px;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 54 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 57 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 58 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 64 "..\..\Views\Requisites\Index.cshtml"
            Write(Html.LabelFor(m => m.Model.ShortNameRus));

            
            #line default
            #line hidden
WriteLiteral(" <small>(<span");

WriteLiteral(" data-bind=\"html: Territory.");

            
            #line 64 "..\..\Views\Requisites\Index.cshtml"
                                                                                                 Write(territoryName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></span>)</small>:\r\n\t\t\t</td>\r\n\t\t\t<td >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 67 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.ShortNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 68 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.ShortNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 74 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.ShortNameLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 77 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.ShortNameLat, new { Databinding = "latinOnly: true" }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");

WriteLiteral("\t\t\t\t");

            
            #line 78 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.ShortNameLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: TerritoryIsRussia\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" valign=\"top\"");

WriteLiteral("><br />\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 84 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.FullName));

            
            #line default
            #line hidden
WriteLiteral(" <small>(<span");

WriteLiteral(" data-bind=\"html: Territory.");

            
            #line 84 "..\..\Views\Requisites\Index.cshtml"
                                                                                           Write(territoryName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></span>)</small>:\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 87 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.FullName));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");

WriteLiteral("\t\t\t\t");

            
            #line 88 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: TerritoryIsRussia\"");

WriteLiteral(">\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 93 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.OKONH));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 96 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.OKONH, new { width = "50", maskOptions = "mask: '99999'" }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");

WriteLiteral("\t\t\t\t");

            
            #line 97 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.OKONH));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: TerritoryIsRussia\"");

WriteLiteral(">\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 102 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.OKVED));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 105 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.OKVED, new { width = "80" }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");

WriteLiteral("\t\t\t\t");

            
            #line 106 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.OKVED));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: TerritoryIsRussia\"");

WriteLiteral(">\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 111 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.KPP));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 114 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.KPP, new { width = "180" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 115 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.KPP));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 121 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.RwID));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 124 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.RwID, new { width = "350" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 125 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.RwID));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 131 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral(" <small>(<span");

WriteLiteral(" data-bind=\"html: Territory.");

            
            #line 131 "..\..\Views\Requisites\Index.cshtml"
                                                                                               Write(territoryName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></span>)</small>:\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 134 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 135 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 141 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.AddressLegalLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t\t<br />&nbsp;\r\n\t\t\t</td>\r\n\t\t\t<td>");

            
            #line 144 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.AddressLegalLat, new { Databinding = "latinOnly: true" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t<small>");

            
            #line 145 "..\..\Views\Requisites\Index.cshtml"
                   Write(Resources.Views_JuridicalPerson_Requisites_AddressLegalLat);

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" data-bind=\"html: Territory.Caption\"");

WriteLiteral("></span></small>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 146 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.AddressLegalLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t\t<" +
"tr");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" >\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 155 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.ShortNameRusGenitive));

            
            #line default
            #line hidden
WriteLiteral(" <small>(<span");

WriteLiteral(" data-bind=\"html: Territory.");

            
            #line 155 "..\..\Views\Requisites\Index.cshtml"
                                                                                                       Write(territoryName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></span>)</small>:<br />\r\n\t\t\t\t<center><small>");

            
            #line 156 "..\..\Views\Requisites\Index.cshtml"
                           Write(Resources.Persons_Requisites_ShortNameRusGenitive_AddOn);

            
            #line default
            #line hidden
WriteLiteral("</small></center>\r\n\t\t\t</td>\r\n\t\t\t<td >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 159 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.ShortNameRusGenitive));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 160 "..\..\Views\Requisites\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.ShortNameRusGenitive));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\r\n\t" +
"\t</table>\r\n");

            
            #line 169 "..\..\Views\Requisites\Index.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

DefineSection("Header", () => {

WriteLiteral("\r\n\t<div");

WriteLiteral(" id=\"toolBar\"");

WriteLiteral(" class=\"ui-widget-header ui-corner-all kui-toolbar\"");

WriteLiteral("\r\n\t\tstyle=\"padding: 2px;\"");

WriteLiteral("\r\n\t\tdata-bind=\"visible: PageLoaded\"");

WriteLiteral(">\r\n\t\t<table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" style=\"margin-top: -2px;\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n\t\t<tr");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(">\r\n\t\t\t<td >&nbsp;\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-bind=\" \r\n\t\t\t\t\t\tclick: function() { ViewModel.save(); $(\'#SubmitButton\').cli" +
"ck(); },\r\n\t\t\t\t\t\tjqueryui: { widget: \'button\', options: { icons: { primary: \'ui-i" +
"con-check\' } } }\r\n\t\t\t\t\t\"");

WriteLiteral(">");

            
            #line 183 "..\..\Views\Requisites\Index.cshtml"
                  Write(Model.Model.ID == 0 ? global::Resources.Resources.GUI_Button_Confirm : global::Resources.Resources.GUI_Button_Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-bind=\"\r\n\t\t\t\t\t\tclick: Delete,\r\n\t\t\t\t\t\tjqueryui: { widget: \'button\', options: " +
"{ disabled: !ViewModel.Model.ID() || ViewModel.CardsNumber()<=1, icons: { primar" +
"y: \'ui-icon-trash\' } } }\r\n\t\t\t\t\t\"");

WriteLiteral(">");

            
            #line 187 "..\..\Views\Requisites\Index.cshtml"
                  Write(global::Resources.Resources.GUI_Button_Delete);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-bind=\" \r\n\t\t\t\t\t\tclick: closeDialog, \r\n\t\t\t\t\t\tjqueryui: { widget: \'button\', op" +
"tions: { icons: { primary: \'ui-icon-cancel\' } } }\r\n\t\t\t\t\t\"");

WriteLiteral(">");

            
            #line 191 "..\..\Views\Requisites\Index.cshtml"
                  Write(global::Resources.Resources.GUI_Button_Cancel);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" nowrap=\"nowrap\"");

WriteLiteral(" style=\"width: 30px;\"");

WriteLiteral(">\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral("\r\n\t\t\t\t\t\tdata-bind=\"jqueryui: { widget: \'button\', options: { text: false, icons: {" +
" primary: \'ui-icon-help\' }}}, click: showHelp\"");

WriteLiteral("\r\n\t\t\t\t\t>");

            
            #line 196 "..\..\Views\Requisites\Index.cshtml"
                 Write(Kesco.Web.Mvc.UI.Controls.Localization.Resources.GUI_Menu_Help);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t</td>\r\n                 </tr>\r\n\t\t</table>\r\n\t</div>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Footer", () => {

WriteLiteral("\r\n");

            
            #line 204 "..\..\Views\Requisites\Index.cshtml"
Write(Html.CommonScriptCode("Requisites_Footer",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "<script>\r\n\t$(document).ready(function () {\r\n\t\t");

WriteLiteralTo(__razor_template_writer, "\r\n\t\tViewModel.ControlNameToFocus=\'#Model_ShortNameRus\';\r\n\r\n        ViewModel.prev" +
"VersionUrl = \"\";\r\n\r\n\t\twindow.ViewModel.TerritoryIsRussia = window.ko.computed(fu" +
"nction () {\r\n\t\t\treturn window.ViewModel.Model.TerritoryID() == ");

            
            #line 213 "..\..\Views\Requisites\Index.cshtml"
                            WriteTo(__razor_template_writer, Kesco.Territories.ObjectModel.Territory.Russia);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @";
		}, window.ViewModel);

		window.ViewModel.NamesAreRequired = window.ko.computed(function () {
			return !window.ViewModel.Model.ShortNameRus() && !window.ViewModel.Model.ShortNameLat();
		}, window.ViewModel);


		$(""#Model_ShortNameRus, #Model_ShortNameLat"").bind(""keydown change"", function() {
			setNamesRequired()
		})

		function setNamesRequired() {
			var rus = $(""#Model_ShortNameRus""), lat = $(""#Model_ShortNameLat"");
			var value = rus.val() || lat.val();
			if (value) {
				rus.parent().removeClass(""ui-state-highlight"");
				lat.parent().removeClass(""ui-state-highlight"");
			} else {
				rus.parent().addClass(""ui-state-highlight"");
				lat.parent().addClass(""ui-state-highlight"");
			}
		}

		");

WriteLiteralTo(__razor_template_writer, "\r\n\t\tvar prevOpForma = \'\', prevOpFormaShort = \'\';\r\n\t\twindow.ViewModel.Model.Incorp" +
"orationFormID.subscribe(function(newValue) {\r\n\t\t\tvar opValue = \"\";\r\n\t\t\tvar opVal" +
"ueShort = \"\";\r\n\r\n\t\t\t");

WriteLiteralTo(__razor_template_writer, "\r\n\t\t\tvar matches = $.grep(\r\n\t\t\t\twindow.ViewModel.Model_IncorporationFormID__Optio" +
"ns,\r\n\t\t\t\tfunction(item, i) {\r\n\t\t\t\t\treturn item.ID == newValue;\r\n\t\t\t\t});\r\n\r\n\t\t\tif" +
" (matches.length > 0) {\r\n\t\t\t\topValue = matches[0].Name;\r\n\t\t\t\topValueShort = matc" +
"hes[0].ShortName;\r\n\t\t\t}\r\n\r\n\t\t\tvar fullName = \"\";\r\n\t\t\tvar shortNameRus = \'\"...\"\';" +
"\r\n\r\n\t\t\tif (window.ViewModel.Model.FullName())\r\n\t\t\t\tfullName = window.ViewModel.M" +
"odel.FullName().toString();\r\n\r\n\t\t\tif (window.ViewModel.Model.ShortNameRus())\r\n\t\t" +
"\t\tshortNameRus = window.ViewModel.Model.ShortNameRus().toString();\r\n\r\n\t\t\tvar cle" +
"arFullName = \"\"+fullName;\r\n\t\t\tif (prevOpForma) clearFullName = clearFullName.rep" +
"lace(prevOpForma + \" \", \"\");\r\n\t\t\tvar clearShortNameRus = \"\"+shortNameRus;\r\n\t\t\tif" +
" (prevOpFormaShort) clearShortNameRus = clearShortNameRus.replace(prevOpFormaSho" +
"rt + \" \", \"\");\r\n\r\n\t\t\tprevOpForma = opValue;\r\n\t\t\tprevOpFormaShort = opValueShort;" +
"\r\n\r\n\t\t\twindow.ViewModel.Model.FullName((opValue?(opValue + \" \"):\"\") + clearFullN" +
"ame);\r\n\t\t\twindow.ViewModel.Model.ShortNameRus((opValueShort?(opValueShort+\" \"):\"" +
"\") + clearShortNameRus);\r\n\t\t});\r\n\r\n\t\tfunction checkLatSymbols(value) {\r\n\t\t\tif (!" +
"$.trim(value || \"\")) return false;\r\n\t\t\tvar pattern = /^[\\x00-\\x7F]+$/;\r\n\t\t\tretur" +
"n pattern.test(value);\r\n\t\t}\r\n\r\n\r\n\t\t$(\"#editForm\").submit(function () {\r\n\t\t\t// th" +
"is - DOM element - form\r\n\t\t\tvar $form = $(this);\r\n\r\n\t\t\tif ($form.valid()) {\r\n\r\n\t" +
"\t\t\twindow.ViewModel.save();\r\n\t\t\t}\r\n\r\n\t\t\treturn false;\r\n\t\t});\r\n\r\n\t\twindow.ViewMod" +
"el.save = function () {\r\n\t\t\tvar $form = $(\"#editForm\");\r\n\t\t\tif (!$form.valid()) " +
"return;\r\n\t\t\t$.ajax({\r\n\t\t\t\turl: \'");

            
            #line 299 "..\..\Views\Requisites\Index.cshtml"
WriteTo(__razor_template_writer, Url.Action("Dispatch"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
				type: 'POST',
				data: window.ko.toJSON({
					command: 'save',
					control: ViewModel.Confirmed()?""confirmed"":null,
					model:  window.ko.mapping.toJS(window.ViewModel.Model)
				}),
				contentType: ""application/json; charset=utf-8"",
				success: function (result, status, xhr) {
				},
				error: function (xhr, status, errorThrown) {
				},
				complete: function() {
				}
			});
		};

		ViewModel.Delete = function () {
			if(ViewModel.Model.ID()==0) return;
			confirmAction('");

            
            #line 318 "..\..\Views\Requisites\Index.cshtml"
WriteTo(__razor_template_writer, global::Resources.Resources.Persons_Delete_Confirm_Title);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\', \'");

            
            #line 318 "..\..\Views\Requisites\Index.cshtml"
                                                          WriteTo(__razor_template_writer, Html.Raw(global::Resources.Resources.Persons_Card_Delete_Confirm_Text));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\', \'");

            
            #line 318 "..\..\Views\Requisites\Index.cshtml"
                                                                                                                                      WriteTo(__razor_template_writer, global::Resources.Resources.GUI_Button_Confirm);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\', function(){ \r\n\t\t\t\t\t$.ajax({\r\n\t\t\t\t\t\turl: \'");

            
            #line 320 "..\..\Views\Requisites\Index.cshtml"
WriteTo(__razor_template_writer, Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\',\r\n\t\t\t\t\t\ttype: \'POST\',\r\n\t\t\t\t\t\tdata: window.ko.toJSON({\r\n\t\t\t\t\t\t\tmodel: ko.mapping" +
".toJS(ViewModel.Model)\r\n\t\t\t\t\t\t}),\r\n\t\t\t\t\t\tcontentType: \"application/json; charset" +
"=utf-8\",\r\n\t\t\t\t\t\tcomplete: function() {\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t});\r\n\t\t\t\t}, \'");

            
            #line 329 "..\..\Views\Requisites\Index.cshtml"
WriteTo(__razor_template_writer, global::Resources.Resources.GUI_Button_Cancel);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"', null, null);
		};

		$(window).resize(function () {
			$(""#formContainer"").height($(""#dialogContentPane"").height());
			$(""#formContainer"").width($(""#dialogContentPane"").width());
		});

		setTimeout(function() { $(window).resize(); }, 100);
	});
</script>");

            
            #line 339 "..\..\Views\Requisites\Index.cshtml"
       })));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 341 "..\..\Views\Requisites\Index.cshtml"
Write(Html.DisplayFor(m => m.Model, "ChangedByInfo"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
