#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Kesco.Web.Mvc;
    
    #line 2 "..\..\Views\Shared\EditorTemplates\DateTimeField.cshtml"
    using Kesco.Web.Mvc.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/DateTimeField.cshtml")]
    public partial class _Views_Shared_EditorTemplates_DateTimeField_cshtml_ : Kesco.Web.Mvc.SharedViews.SharedViewPage<DateTime?>
    {
        public _Views_Shared_EditorTemplates_DateTimeField_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\DateTimeField.cshtml"
  
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");

            
            #line default
            #line hidden
WriteLiteral("\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" size=\"10\"");

WriteLiteral(" style=\"width: 80px;\"");

WriteAttribute("name", Tuple.Create(" name=\"", 204), Tuple.Create("\"", 251)
            
            #line 6 "..\..\Views\Shared\EditorTemplates\DateTimeField.cshtml"
, Tuple.Create(Tuple.Create("", 211), Tuple.Create<System.Object, System.Int32>(ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 211), false)
);

WriteAttribute("id", Tuple.Create(" \r\n\tid=\"", 252), Tuple.Create("\"", 265)
            
            #line 7 "..\..\Views\Shared\EditorTemplates\DateTimeField.cshtml"
, Tuple.Create(Tuple.Create("", 260), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 260), false)
);

WriteLiteral("\r\n\tdata-bind=\"decoration: { width: \'100px\' }, \r\n\t\tdatepicker: ");

            
            #line 9 "..\..\Views\Shared\EditorTemplates\DateTimeField.cshtml"
          Write(ViewData.TemplateInfo.HtmlFieldPrefix);

            
            #line default
            #line hidden
WriteLiteral(", \r\n\t\tdatepickerOptions: { \r\n\t\t\tconstrainInput: true, \r\n\t\t\tchangeMonth: true,\r\n\t\t" +
"\tchangeYear: true,\r\n\t\t\tstepMonths: 1\r\n\t\t}\"");

WriteLiteral(" />\r\n        \r\n");

        }
    }
}
#pragma warning restore 1591
