#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.Web.Mvc.SharedViews.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Kesco.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/FixedLengthTextBox.cshtml")]
    public class FixedLengthTextBox : Kesco.Web.Mvc.SharedViews.SharedViewPage<string>
    {
        public FixedLengthTextBox()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Shared\EditorTemplates\FixedLengthTextBox.cshtml"
  
	string name = ViewData.TemplateInfo.HtmlFieldPrefix;
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");
	ModelMetadata meta = ViewData.ModelMetadata;

	var width = ViewData["width"] != null ? ViewData["width"].ToString() + "px" : "100px";

	List<string> databindings = new List<string>();
	databindings.Add(String.Format("decoration: {{width:'{0}'}}", width));
	databindings.Add((meta.IsRequired ? "valueEx: " : "value: ") + name);

	string mask = ViewData["mask"] != null ? ViewData["mask"].ToString() : null;

	if (ViewData["Databinding"] != null)
		databindings.Add(ViewData["Databinding"].ToString());


            
            #line default
            #line hidden
WriteLiteral("<span style=\"width: ");


            
            #line 18 "..\..\Views\Shared\EditorTemplates\FixedLengthTextBox.cshtml"
                Write(width);

            
            #line default
            #line hidden
WriteLiteral(";\">\r\n\t");


            
            #line 19 "..\..\Views\Shared\EditorTemplates\FixedLengthTextBox.cshtml"
Write(Html.KescoTextBoxFor(Model => Model, new { data_bind = String.Join(", ", databindings), data_mask = mask }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</span>");


        }
    }
}
#pragma warning restore 1591
