#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Shared\EmployeeInfo.cshtml"
    using Kesco.Employees.Controls;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\EmployeeInfo.cshtml"
    using Kesco.Employees.Controls.Localization;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\EmployeeInfo.cshtml"
    using Kesco.Employees.ObjectModel;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\EmployeeInfo.cshtml"
    using Kesco.ObjectModel;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\EmployeeInfo.cshtml"
    using Kesco.Persons.ObjectModel;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\EmployeeInfo.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EmployeeInfo.cshtml")]
    public partial class _Views_Shared_EmployeeInfo_cshtml : Kesco.Employees.Controls.SiteViewPage<Kesco.Employees.Controls.Models.EmployeeInfo.ViewModel>
    {
        public _Views_Shared_EmployeeInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Shared\EmployeeInfo.cshtml"
  
    ViewBag.Title = "Контакты сотрудника";
	Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 14 "..\..\Views\Shared\EmployeeInfo.cshtml"
   
	string id = ViewData.TemplateInfo.GetFullHtmlFieldId("");
	string name = ViewData.TemplateInfo.HtmlFieldPrefix;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"min-width: 450px; \"");

WriteLiteral(" >\r\n");

            
            #line 19 "..\..\Views\Shared\EmployeeInfo.cshtml"
 if (Model == null) {
	
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\EmployeeInfo.cshtml"
Write(ViewData.ModelMetadata.NullDisplayText);

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\EmployeeInfo.cshtml"
                                           
} else {
	if (Model.Employee == null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t");

WriteLiteral(" - #");

            
            #line 23 "..\..\Views\Shared\EmployeeInfo.cshtml"
          Write(Model.EmployeeID);

            
            #line default
            #line hidden
WriteLiteral(" -\r\n");

            
            #line 24 "..\..\Views\Shared\EmployeeInfo.cshtml"
	} else {

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"margin-bottom: 5px; \"");

WriteLiteral(" >\r\n\r\n\t<img");

WriteAttribute("src", Tuple.Create(" src=\"", 778), Tuple.Create("\"", 857)
            
            #line 28 "..\..\Views\Shared\EmployeeInfo.cshtml"
, Tuple.Create(Tuple.Create("", 784), Tuple.Create<System.Object, System.Int32>(Configuration.AppSettings.URI_user_photo
            
            #line default
            #line hidden
, 784), false)
, Tuple.Create(Tuple.Create("", 827), Tuple.Create("?id=", 827), true)
            
            #line 28 "..\..\Views\Shared\EmployeeInfo.cshtml"
, Tuple.Create(Tuple.Create("", 831), Tuple.Create<System.Object, System.Int32>(Model.Employee.ID
            
            #line default
            #line hidden
, 831), false)
, Tuple.Create(Tuple.Create("", 851), Tuple.Create("&w=100", 851), true)
);

WriteLiteral(" \r\n\t\t\talign=\"left\"");

WriteLiteral(" vspace=\"5\"");

WriteLiteral(" hspace=\"5\"");

WriteLiteral(" width=\"100px\"");

WriteLiteral(" />\r\n\t<div");

WriteLiteral(" style=\"padding-left: 5px; margin: 3px 0;\"");

WriteLiteral(" nowrap=\"nowrap\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 31 "..\..\Views\Shared\EmployeeInfo.cshtml"
       Write(Html.DisplayFor(m => m.Employee.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n\t<div");

WriteLiteral(" style=\"padding-left: 5px; margin: 3px 0;\"");

WriteLiteral(" nowrap=\"nowrap\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t");

            
            #line 34 "..\..\Views\Shared\EmployeeInfo.cshtml"
   Write(Html.DisplayFor(m => m.Employee.FullNameEn));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n");

            
            #line 36 "..\..\Views\Shared\EmployeeInfo.cshtml"
	
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Shared\EmployeeInfo.cshtml"
     if (Model.LastPassage != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" style=\"padding-left: 5px;  margin: 3px 0; white-space: nowrap !important;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 38 "..\..\Views\Shared\EmployeeInfo.cshtml"
       Write(Html.DisplayFor(m => m.LastPassage.Point));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");

WriteLiteral("\t\t\t");

            
            #line 39 "..\..\Views\Shared\EmployeeInfo.cshtml"
       Write(Model.LastPassage.TimeAt.FromUtcToClient().ToString("F"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</div>\r\n");

            
            #line 41 "..\..\Views\Shared\EmployeeInfo.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("\t");

            
            #line 42 "..\..\Views\Shared\EmployeeInfo.cshtml"
     if (Model.AllContacts.Count > 0) {
		bool drawBorder = false;

            
            #line default
            #line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" style=\"margin-top: 10px; clear: both; \"");

WriteLiteral(">\r\n");

            
            #line 45 "..\..\Views\Shared\EmployeeInfo.cshtml"
		
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Shared\EmployeeInfo.cshtml"
         foreach (var c in Model.AllContacts) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div");

WriteAttribute("style", Tuple.Create(" style=\"", 1571), Tuple.Create("\"", 1674)
, Tuple.Create(Tuple.Create("", 1579), Tuple.Create("min-height:", 1579), true)
, Tuple.Create(Tuple.Create(" ", 1590), Tuple.Create("18px;", 1591), true)
, Tuple.Create(Tuple.Create(" ", 1596), Tuple.Create("padding-top:", 1597), true)
, Tuple.Create(Tuple.Create(" ", 1609), Tuple.Create("2px;", 1610), true)
            
            #line 46 "..\..\Views\Shared\EmployeeInfo.cshtml"
, Tuple.Create(Tuple.Create(" ", 1614), Tuple.Create<System.Object, System.Int32>(drawBorder?"border-top: 1px solid silver !important;":""
            
            #line default
            #line hidden
, 1615), false)
);

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 47 "..\..\Views\Shared\EmployeeInfo.cshtml"
           Write(Html.DisplayFor(m => c.Contact, GetControlNameByContactType(c.ContactType), new {
					contactIcon = GetControlIconByContactType(c.ContactType),
					PhoneType = c.Type,
					PhoneNumber = c.PhoneNumber,
                    CID = Model.Employee.ID,
                    CType = 2,
					CssClass = (c.InDictionary ? "" : "clGrayTrans")
				}));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");

            
            #line 55 "..\..\Views\Shared\EmployeeInfo.cshtml"
				
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\EmployeeInfo.cshtml"
                 if (!String.IsNullOrEmpty(c.Note)) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("<small class=\"clGray\">(");

            
            #line 56 "..\..\Views\Shared\EmployeeInfo.cshtml"
                                         Write(c.Note);

            
            #line default
            #line hidden
WriteLiteral(")</small>\r\n");

            
            #line 57 "..\..\Views\Shared\EmployeeInfo.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</div>\r\n");

            
            #line 59 "..\..\Views\Shared\EmployeeInfo.cshtml"
			drawBorder = true;
		}

            
            #line default
            #line hidden
WriteLiteral("\t\t</div>\r\n");

WriteLiteral("\t\t<div");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(">");

WriteLiteral("</div>\r\n");

            
            #line 63 "..\..\Views\Shared\EmployeeInfo.cshtml"
	} else {

            
            #line default
            #line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" style=\"margin-top: 10px;\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Shared\EmployeeInfo.cshtml"
                                   Write(Kesco.Web.Mvc.SharedViews.Localization.Resources.PersonContacts_NoContacts);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 65 "..\..\Views\Shared\EmployeeInfo.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("\r\n");

            
            #line 68 "..\..\Views\Shared\EmployeeInfo.cshtml"
	}
}

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
