//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.Persons.BusinessLogic.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kesco.Persons.BusinessLogic.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while checking the person in accounting 1S..
        /// </summary>
        public static string Accounting_CheckPerson1SStatus_ErrorMessage {
            get {
                return ResourceManager.GetString("Accounting_CheckPerson1SStatus_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while checking the person in accounting Abacus..
        /// </summary>
        public static string Accounting_CheckPersonAbacusStatus_ErrorMessage {
            get {
                return ResourceManager.GetString("Accounting_CheckPersonAbacusStatus_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на looks like.
        /// </summary>
        public static string Kesco_Persons_MDL_677 {
            get {
                return ResourceManager.GetString("Kesco_Persons_MDL_677", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is equal.
        /// </summary>
        public static string Kesco_Persons_MDL_678 {
            get {
                return ResourceManager.GetString("Kesco_Persons_MDL_678", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specifies an unique number for the theme which entity can have..
        /// </summary>
        public static string Kesco_Persons_MDL_PersonTheme_ID_Description {
            get {
                return ResourceManager.GetString("Kesco_Persons_MDL_PersonTheme_ID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme ID.
        /// </summary>
        public static string Kesco_Persons_MDL_PersonTheme_ID_Name {
            get {
                return ResourceManager.GetString("Kesco_Persons_MDL_PersonTheme_ID_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please specify unique ID of the theme.
        /// </summary>
        public static string Kesco_Persons_MDL_PersonTheme_ID_Prompt {
            get {
                return ResourceManager.GetString("Kesco_Persons_MDL_PersonTheme_ID_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string Kesco_Persons_MDL_PersonTheme_ID_ShortName {
            get {
                return ResourceManager.GetString("Kesco_Persons_MDL_PersonTheme_ID_ShortName", resourceCulture);
            }
        }
    }
}
