#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Natural\Index.cshtml"
    using Kesco.Persons.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Natural\Index.cshtml"
    using Kesco.Persons.Web.Localization;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Natural\Index.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Natural\Index.cshtml"
    using Kesco.Web.Mvc.UI;
    
    #line default
    #line hidden
    using MvcJqGrid;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Natural/Index.cshtml")]
    public partial class _Views_Natural_Index_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Persons.Web.Models.Naturals.ViewModel>
    {
        public _Views_Natural_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Natural\Index.cshtml"
  
	Model
		.GetScriptCapabilities()
		.DisableGridScript()
		.DisableTreeScript();
	ViewBag.Title = Model.PageTitle;
    
    string[] accessLevel = Model.EmployeeRoles.Split(',');
	Layout = "~/Views/Shared/_Layout.cshtml";
    /* Ищем в URL параметр hideOldVer, пишем его в сессию. Требуется для скрытия кнопки "Открыть в старой версии"  */
    string hideOldVerRequest = HttpContext.Current.Request["hideOldVer"];
    var hideOldVerSession = HttpContext.Current.Session["hideOldVer"];
    string hideOldVer = "false";
     
    if (!String.IsNullOrEmpty(hideOldVerRequest))
    {
        HttpContext.Current.Session["hideOldVer"] = hideOldVer = hideOldVerRequest;
    }
    else if (hideOldVerSession != null)
    {
        hideOldVer = hideOldVerSession.ToString();
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n\ttable.formTable td { padding: 4px; }\r\n</style>\r\n<div");

WriteLiteral(" id=\"formContainer\"");

WriteLiteral(" style=\"overflow: auto;\"");

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Views\Natural\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Natural\Index.cshtml"
       Html.EnableClientValidation(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\t \r\n");

            
            #line 35 "..\..\Views\Natural\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Natural\Index.cshtml"
     using (Html.BeginForm("NaturalPersonForm", "Person", FormMethod.Post, new { id = "NaturalPersonForm", name = "NewJuridicalForm", onsubmit = "return false;" }))
	{
		
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Natural\Index.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Natural\Index.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral("\t\t<table");

WriteLiteral(" class=\"formTable\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" style=\"min-width: 700px;\"");

WriteLiteral(" cellpadding=\"4\"");

WriteLiteral(">\r\n\t\t");

WriteLiteral("\r\n\t\t<tr>\r\n\t\t\t<td");

WriteLiteral(" rowspan=\"30\"");

WriteLiteral(" style=\"width: 30px;\"");

WriteLiteral(">&nbsp;&nbsp;</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" >\r\n\r\n\t\t\t\t<b><span");

WriteLiteral(" style=\"font-size: 16px;\"");

WriteLiteral(" data-bind=\"text: Model.Card.Nickname\"");

WriteLiteral("></span></b>&nbsp;\r\n\t\t\t\t<input");

WriteLiteral(" style=\"visibility: hidden; width:1px; height:1px\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" \r\n\t\t\t\t\tid=\"SubmitButton\"");

WriteLiteral(" />\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" align=\"right\"");

WriteLiteral(">\r\n\t\t\t\t<table>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td>");

            
            #line 54 "..\..\Views\Natural\Index.cshtml"
                        Write(global::Resources.Resources.Kesco_Persons_Web_VW_133);

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" align=\"right\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\Natural\Index.cshtml"
                                     Write(Html.LabelFor(m => m.Model.Card.From));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" style=\"width: 80px\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\Natural\Index.cshtml"
                                           Write(Html.EditorFor(m => m.Model.Card.From));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" align=\"right\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Natural\Index.cshtml"
                                     Write(Html.LabelFor(m => m.Model.Card.To));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t<td");

WriteLiteral(" style=\"width: 80px\"");

WriteLiteral(">");

            
            #line 58 "..\..\Views\Natural\Index.cshtml"
                                           Write(Html.EditorFor(m => m.Model.Card.To));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t</table>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonData\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 66 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.TerritoryID, new { @for = "Model_Card_TerritoryID___Autocomplete" }));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 69 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.TerritoryID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 70 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.TerritoryID));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" style=\"width: 310px; white-space: normal;\"");

WriteLiteral(">\r\n\t\t\t\t<small>");

            
            #line 76 "..\..\Views\Natural\Index.cshtml"
                   Write(Resources.Views_JuridicalPerson_Requisites_NationalPassport);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t<span");

WriteLiteral(" id=\"TerritoryCaptionLat\"");

WriteLiteral(" \r\n\t\t\t\t\tdata-bind=\"\r\n\t\t\t\t\t\tdynamicLink: {\r\n\t\t\t\t\t\t\tvalue: Model.Card.TerritoryID,\r" +
"\n\t\t\t\t\t\t\tsource: \'");

            
            #line 81 "..\..\Views\Natural\Index.cshtml"
                                 Write(Url.FullPathAction("GetItemLang", "TerritorySelect"));

            
            #line default
            #line hidden
WriteLiteral("\' \r\n\t\t\t\t\t\t}\"");

WriteLiteral("\r\n\t\t\t\t\t></span></small>\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" style=\"width: 310px;\"");

WriteLiteral(">\r\n\t\t\t\t<small");

WriteLiteral(@" data-bind=""
						visible: Model.Card.LastNameLat() || Model.Card.FirstNameLat() || Model.Card.MiddleNameLat() 
							|| (Model.Card.LastNameRus() && !LastNameRusIsInLat()) 
							|| (Model.Card.FirstNameRus() && !FirstNameRusIsInLat()) 
							|| (Model.Card.MiddleNameRus() && !MiddleNameRusIsInLat())
					""");

WriteLiteral(">");

            
            #line 91 "..\..\Views\Natural\Index.cshtml"
                  Write(Resources.Views_JuridicalPerson_Requisites_English);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 150px; \"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 97 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.LastNameRus));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 160px;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 100 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.LastNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 101 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.LastNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n               \t<td");

WriteLiteral(" style=\"width: 10px;\"");

WriteLiteral(">\r\n                     <span");

WriteLiteral(" data-bind=\"visible: (Model.Card.LastNameLat() || Model.Card.LastNameRus() && !La" +
"stNameRusIsInLat()) && Model.Card.LastNameLat() != Model.Card.LastNameRus() \"");

WriteLiteral(">\r\n\t\t\t\t\t\t<a");

WriteLiteral(" href=\"javascript: translateName(\'lastName\');\"");

WriteLiteral(" \r\n                            ><img");

WriteLiteral(" style=\"cursor: pointer; border: 0px;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 4266), Tuple.Create("\"", 4359)
            
            #line 106 "..\..\Views\Natural\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4274), Tuple.Create<System.Object, System.Int32>(Kesco.Persons.Web.Localization.Resources.Views_NaturalPerson_Tooltip_TranslateName
            
            #line default
            #line hidden
, 4274), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 4360), Tuple.Create("\"", 4420)
            
            #line 106 "..\..\Views\Natural\Index.cshtml"
                                                                                           , Tuple.Create(Tuple.Create("", 4366), Tuple.Create<System.Object, System.Int32>(Url.Content(AppStyles.URI_Styles_Css)
            
            #line default
            #line hidden
, 4366), false)
, Tuple.Create(Tuple.Create("", 4404), Tuple.Create("images/right.png", 4404), true)
);

WriteLiteral("/></a>\r\n                            </span>\r\n\t\t\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 160px; \"");

WriteLiteral(">\r\n\t\t\t\t<span");

WriteLiteral(" data-bind=\"visible: (Model.Card.LastNameLat() || Model.Card.LastNameRus() && !La" +
"stNameRusIsInLat()) && Model.Card.LastNameLat() != Model.Card.LastNameRus() \"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 111 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.LastNameLat, new { Databinding = "latinOnly: true" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 112 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.LastNameLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</span>\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(">\r\n                <tr><span");

WriteLiteral(" data-bind=\"visible: false && Model.Card.LastNameRus() && !LastNameRusIsInLat()\"");

WriteLiteral(">\r\n\t\t\t\t&nbsp;");

            
            #line 117 "..\..\Views\Natural\Index.cshtml"
                 Write(Html.LabelFor(m => m.Model.Card.LastNameLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t\t</span>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 125 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.FirstNameRus));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 160px;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 128 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.FirstNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 129 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.FirstNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n              \t<td");

WriteLiteral(" style=\"width: 10px;\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-bind=\"visible: (Model.Card.FirstNameLat() || Model.Card.FirstNameRus() && !" +
"FirstNameRusIsInLat()) && Model.Card.FirstNameLat() != Model.Card.FirstNameRus()" +
" \"");

WriteLiteral(">\r\n\t\t\t\t\t\t<a");

WriteLiteral(" href=\"javascript: translateName(\'firstName\');\"");

WriteLiteral(" \r\n\t\t\t\t\t\t><img");

WriteLiteral(" style=\"cursor: pointer; border: 0px;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 5732), Tuple.Create("\"", 5825)
            
            #line 134 "..\..\Views\Natural\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5740), Tuple.Create<System.Object, System.Int32>(Kesco.Persons.Web.Localization.Resources.Views_NaturalPerson_Tooltip_TranslateName
            
            #line default
            #line hidden
, 5740), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 5826), Tuple.Create("\"", 5886)
            
            #line 134 "..\..\Views\Natural\Index.cshtml"
                                                                                       , Tuple.Create(Tuple.Create("", 5832), Tuple.Create<System.Object, System.Int32>(Url.Content(AppStyles.URI_Styles_Css)
            
            #line default
            #line hidden
, 5832), false)
, Tuple.Create(Tuple.Create("", 5870), Tuple.Create("images/right.png", 5870), true)
);

WriteLiteral(" \r\n\t\t\t\t\t\t\t/></a>\r\n                            </span>\r\n\t\t\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 160px;\"");

WriteLiteral(">\r\n\t\t\t\t<span");

WriteLiteral(" data-bind=\"visible: (Model.Card.FirstNameLat() || Model.Card.FirstNameRus() && !" +
"FirstNameRusIsInLat()) && Model.Card.FirstNameRus() != Model.Card.FirstNameLat()" +
"\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 140 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.FirstNameLat, new { Databinding = "latinOnly: true" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 141 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.FirstNameLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</span>\r\n\t\t\t</td>\r\n      \r\n\t\t\t<td");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n\t\t\t\t<span");

WriteLiteral(" data-bind=\"visible: false && Model.Card.FirstNameRus() && !FirstNameRusIsInLat()" +
"\"");

WriteLiteral(">\r\n\t\t\t\t\t&nbsp;");

            
            #line 147 "..\..\Views\Natural\Index.cshtml"
                     Write(Html.LabelFor(m => m.Model.Card.FirstNameLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t\t</span>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 154 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.MiddleNameRus));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 160px;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 157 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.MiddleNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 158 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.MiddleNameRus));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n               \t<td");

WriteLiteral(" style=\"width: 10px;\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-bind=\"visible: (Model.Card.MiddleNameLat() || Model.Card.MiddleNameRus() &&" +
" !MiddleNameRusIsInLat()) && Model.Card.MiddleNameLat() != Model.Card.MiddleName" +
"Rus() \"");

WriteLiteral(">\r\n\t\t\t\t\t\t<a");

WriteLiteral(" href=\"javascript: translateName(\'middleName\');\"");

WriteLiteral(" \r\n\t\t\t\t\t\t><img");

WriteLiteral(" style=\"cursor: pointer; border: 0px;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7209), Tuple.Create("\"", 7302)
            
            #line 163 "..\..\Views\Natural\Index.cshtml"
, Tuple.Create(Tuple.Create("", 7217), Tuple.Create<System.Object, System.Int32>(Kesco.Persons.Web.Localization.Resources.Views_NaturalPerson_Tooltip_TranslateName
            
            #line default
            #line hidden
, 7217), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 7303), Tuple.Create("\"", 7363)
            
            #line 163 "..\..\Views\Natural\Index.cshtml"
                                                                                       , Tuple.Create(Tuple.Create("", 7309), Tuple.Create<System.Object, System.Int32>(Url.Content(AppStyles.URI_Styles_Css)
            
            #line default
            #line hidden
, 7309), false)
, Tuple.Create(Tuple.Create("", 7347), Tuple.Create("images/right.png", 7347), true)
);

WriteLiteral(" \r\n\t\t\t\t\t\t\t/></a>\r\n                            </span>\r\n\t\t\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 160px;\"");

WriteLiteral(" >\r\n\t\t\t\t<span");

WriteLiteral(" data-bind=\"visible: (Model.Card.MiddleNameLat() || Model.Card.MiddleNameRus() &&" +
" !MiddleNameRusIsInLat()) && Model.Card.MiddleNameRus() != Model.Card.MiddleName" +
"Lat()\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 169 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.MiddleNameLat, new { Databinding = "latinOnly: true" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 170 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.MiddleNameLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</span>\r\n               </td>\r\n\t\t\t<td");

WriteLiteral(" style=\"\"");

WriteLiteral(" >\r\n\t\t\t\t<span");

WriteLiteral(" data-bind=\"visible: false && Model.Card.MiddleNameRus() && !MiddleNameRusIsInLat" +
"()\"");

WriteLiteral(">\r\n\t\t\t\t\t&nbsp;");

            
            #line 175 "..\..\Views\Natural\Index.cshtml"
                     Write(Html.LabelFor(m => m.Model.Card.MiddleNameLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t\t</span>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n        <tr>\r\n            <td></td>\r\n         " +
"   <td");

WriteLiteral("  style=\"width: 160px;\"");

WriteLiteral(" >\r\n                <span");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" id=\"fioValidationMessage\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" style=\"COLOR: #ff0000; font-weight:100;  font-size: 10px;\"");

WriteLiteral(">");

            
            #line 183 "..\..\Views\Natural\Index.cshtml"
                                                                                  Write(Kesco.Persons.Web.Localization.Resources.Validation_NaturalPerson_AtLeastTheNameMustBeSpecified);

            
            #line default
            #line hidden
WriteLiteral("</label> \r\n           </span>\r\n            </td>\r\n\r\n        </tr>\r\n          \r\n\t\t" +
"");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" data-bind=\"if: ShowPersonRequisites\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 192 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.Nickname, global::Resources.Resources.Kesco_Persons_Web_VW_136));

            
            #line default
            #line hidden
WriteLiteral(":\r\n              \r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n\t\t\t\t<select");

WriteLiteral(" id=\"NicknameVariants\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral("  data-bind=\"\r\n\t\t\t\t\t\tenable: NicknameVariants().length > 1,\r\n\t\t\t\t\t\tvalue: Model.C" +
"ard.Nickname,\r\n\t\t\t\t\t\tjqOptions: NicknameVariants,\r\n\t\t\t\t\t\toptionsValue: \'ID\',\r\n\t\t" +
"\t\t\t\toptionsText: \'Nickname\',\r\n\t\t\t\t\t\trequired: true\r\n\t\t\t\t\t\"");

WriteLiteral("></select>  \r\n");

WriteLiteral("\t\t\t\t");

            
            #line 204 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n        <tr>\r\n            <td></td>\r\n            <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" id=\"nicknameValidationMessage\"");

WriteLiteral(">\r\n                      <label");

WriteLiteral(" style=\"COLOR: #ff0000; font-weight:100;  font-size: 10px;\"");

WriteLiteral(">");

            
            #line 211 "..\..\Views\Natural\Index.cshtml"
                                                                                    Write(Kesco.Persons.Web.Localization.Resources.Models_JuridicalPersonCard_Nickname_Required);

            
            #line default
            #line hidden
WriteLiteral("</label> \r\n         </span>\r\n            </td>\r\n        </tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites\"");

WriteLiteral(">\r\n\t\t\t<td>");

            
            #line 217 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.Sex));

            
            #line default
            #line hidden
WriteLiteral(":</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" nowrap=\"nowrap\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 219 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.Sex));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 220 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.Sex));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n           <tr>\r\n            <td></td>\r\n            <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" id=\"sexValidationMessage\"");

WriteLiteral(">\r\n                  <label");

WriteLiteral(" style=\"COLOR: #ff0000; font-weight:100;  font-size: 10px;\"");

WriteLiteral(">");

            
            #line 227 "..\..\Views\Natural\Index.cshtml"
                                                                                Write(Kesco.Persons.Web.Localization.Resources.Validation_NaturalPerson_SexMustBeSpecified);

            
            #line default
            #line hidden
WriteLiteral("</label> \r\n            </span>\r\n            </td>\r\n        </tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonData\"");

WriteLiteral("> \r\n\t\t\t<td >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 234 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.Birthday));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 237 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.Birthday));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites() && (true || Model.Card.IncorporationF" +
"ormID())\"");

WriteLiteral(">\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 243 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t\t<br />&nbsp;\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 247 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t<small>");

            
            #line 248 "..\..\Views\Natural\Index.cshtml"
                   Write(Resources.Views_JuridicalPerson_Requisites_Local);

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" id=\"TerritoryCaptionLat2\"");

WriteLiteral(" \r\n\t\t\t\t\tdata-bind=\"\r\n\t\t\t\t\t\tdynamicLink: {\r\n\t\t\t\t\t\t\tvalue: Model.Card.TerritoryID,\r" +
"\n\t\t\t\t\t\t\tsource: \'");

            
            #line 252 "..\..\Views\Natural\Index.cshtml"
                                 Write(Url.FullPathAction("GetItemLang", "TerritorySelect"));

            
            #line default
            #line hidden
WriteLiteral("\' \r\n\t\t\t\t\t\t}\"");

WriteLiteral("\r\n\t\t\t\t\t></span></small>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 255 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.AddressLegal));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites() && (Model.Card.AddressLegalLat() || M" +
"odel.Card.AddressLegal() && !AddressLegalRusIsInLat()) && (true || Model.Card.In" +
"corporationFormID())\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral("  style=\"border-bottom: 1px solid;\"");

WriteLiteral(">\r\n\t\t\t\t<span");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">");

            
            #line 261 "..\..\Views\Natural\Index.cshtml"
                                        Write(Html.LabelFor(m => m.Model.Card.AddressLegalLat));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t\t<br />&nbsp;</span>\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral("  style=\"border-bottom: 1px solid;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 265 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.AddressLegalLat, new { Databinding = "latinOnly: true" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t<small>");

            
            #line 266 "..\..\Views\Natural\Index.cshtml"
                   Write(Resources.Views_JuridicalPerson_Requisites_English1);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 267 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.AddressLegalLat));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n \t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: HasRolesForBusinessProjects().length > 0\"");

WriteLiteral("> \r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 274 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.BusinessProjectID, new { @for = "Model_Card_BusinessProjectID___Autocomplete" }));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 277 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.BusinessProjectID));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites\"");

WriteLiteral(" >\r\n \t\t\t<td");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 283 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 286 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 287 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.IncorporationFormID));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t   </tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" id=\"OGRNFields\"");

WriteLiteral(" data-bind=\"visible: ShowPersonData\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(" >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 293 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.OGRN, new Dictionary<string, object> {
						{ "data-bind", "text: FormatRegistration.OGRNName" }
					}));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 298 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.OGRN, new { width = 150 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n              ");

WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 300 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.OGRN));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"visible:ShowPersonData() && FormatRegistration.INNLength2()\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(" >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 306 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.INN, new Dictionary<string, object> {
						{ "data-bind", "text: FormatRegistration.INNName" }
				}));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 311 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.INN, new { width = 110 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t(");

            
            #line 312 "..\..\Views\Natural\Index.cshtml"
             Write(Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Length);

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" data-bind=\"text: FormatRegistration.INNLength2\"");

WriteLiteral("></span>)\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 313 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.INN));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" id=\"OKPOFields\"");

WriteLiteral(" data-bind=\"visible: ShowPersonData() && FormatRegistration.OKPOLength2() && wind" +
"ow.ViewModel.Model.ShowReqFromIncForm != \'hideAllExINN\' \"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(" >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 319 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.OKPO, new Dictionary<string, object> {
						{ "data-bind", "text: FormatRegistration.OKPOName" }
				}));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 324 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.OKPO, new { width = 110 }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n\t\t\t\t(");

            
            #line 325 "..\..\Views\Natural\Index.cshtml"
             Write(Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Length);

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" data-bind=\"text: FormatRegistration.OKPOLength2\"");

WriteLiteral("></span>)\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 326 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.OKPO));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" id=\"OKONHFields\"");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites() && Model.Card.IncorporationFormID() &" +
"& ViewModel.Model.ShowReqFromIncForm != \'hideAllExINN\' && ViewModel.Model.ShowRe" +
"qFromIncForm != \'hideOKONH\' \"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(" >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 332 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.OKONH));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 335 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.OKONH, new
                {
                    width = "50",
                    maskOptions = "mask: '99999'"
                }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");

WriteLiteral("\t\t\t\t");

            
            #line 340 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.OKONH));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr");

WriteLiteral(" id=\"OKVEDFields\"");

WriteLiteral("  data-bind=\"visible: ShowPersonRequisites() && Model.Card.IncorporationFormID() " +
"&& ViewModel.Model.ShowReqFromIncForm != \'hideAllExINN\'\"");

WriteLiteral(">\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 345 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.OKVED));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 348 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.OKVED, new
                {
                    width = "150",
                    maskOptions = "mask: '99999999'"
                }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 353 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.OKVED));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr");

WriteLiteral(" id=\"KPPFields\"");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites() && Model.Card.IncorporationFormID() &" +
"& ViewModel.Model.ShowReqFromIncForm != \'hideAllExINN\' \"");

WriteLiteral(">\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 358 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.KPP));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 361 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.KPP, new { width = "150" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 362 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.KPP));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t<tr");

WriteLiteral(" id=\"RwIDFields\"");

WriteLiteral(" data-bind=\"visible: ShowPersonRequisites() && Model.Card.IncorporationFormID() &" +
"& ViewModel.Model.ShowReqFromIncForm != \'hideAllExINN\' && ViewModel.Model.ShowRe" +
"qFromIncForm != \'hideOKONH\'\"");

WriteLiteral(">\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 368 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.RwID));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 371 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.RwID, new { width = "150" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 372 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.RwID));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n        \t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" data-bind=\"if: !Model.Card.PersonID()\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(" style=\"border-top: 1px outset;\"");

WriteLiteral(" >\r\n\t\t\t\t<span");

WriteLiteral(" class=\"ui-icon ui-icon-script text-ui-icon\"");

WriteLiteral(">&nbsp;</span> ");

            
            #line 378 "..\..\Views\Natural\Index.cshtml"
                                                                            Write(global::Resources.Resources.Kesco_Persons_Web_VW_138);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" style=\"border-top: 1px outset;\"");

WriteLiteral(" >\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 381 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.PersonTypes));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t");

WriteLiteral("\r\n\t\t<tr");

WriteLiteral(" data-bind=\"if: !Model.Card.PersonID()\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" style=\"border-top: 1px outset;\"");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">\r\n\t\t\t\t<table>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td>\r\n                        <!-- Если секретарь " +
"или администратор лиц -->\r\n");

            
            #line 392 "..\..\Views\Natural\Index.cshtml"
            			
            
            #line default
            #line hidden
            
            #line 392 "..\..\Views\Natural\Index.cshtml"
                         if (accessLevel.Contains("11") || accessLevel.Contains("12"))
                        {
						
            
            #line default
            #line hidden
            
            #line 394 "..\..\Views\Natural\Index.cshtml"
                   Write(Html.Raw(String.Format(@"<a href='javascript: void(0);' onclick=""window.ViewModel.ChooseEmpls(getResponsibleIds());"">{0}</a>", global::Resources.Resources.Kesco_Persons_Web_VW_126)));

            
            #line default
            #line hidden
            
            #line 394 "..\..\Views\Natural\Index.cshtml"
                                                                                                                                                                                                                ;
						} else {
            

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<span");

WriteLiteral(" class=\"ui-icon ui-icon-person text-ui-icon\"");

WriteLiteral(">&nbsp;\r\n\t\t\t\t\t\t</span>");

            
            #line 398 "..\..\Views\Natural\Index.cshtml"
                               
            
            #line default
            #line hidden
            
            #line 398 "..\..\Views\Natural\Index.cshtml"
                           Write(global::Resources.Resources.Kesco_Persons_Web_VW_126);

            
            #line default
            #line hidden
            
            #line 398 "..\..\Views\Natural\Index.cshtml"
                                                                                      
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<!--\r\n\t\t\t\t\t\t| <a href=\"javascript: void(0)\" data-bind=\"\r\n\t\t\t\t\t\t\t\t" +
"click: openChooseEmployeesDialog\r\n\t\t\t\t\t\t\t\" title=\"");

            
            #line 405 "..\..\Views\Natural\Index.cshtml"
                                 Write(global::Resources.Resources.Kesco_Persons_Web_VW_1002);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t\t<span class=\"ui-icon ui-icon-plus text-ui-icon\">&nbsp;</span>\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 407 "..\..\Views\Natural\Index.cshtml"
                        Write(global::Resources.Resources.Kesco_Persons_Web_VW_1002);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t\t\t\t//-->\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t</table>\r\n\t\t\t\t<table>\r\n\t\t\t\t<tr>\r\n\t\t" +
"\t\t\t<td");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral(">&nbsp;</td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<table");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<tbody");

WriteLiteral(" data-bind=\"foreach: Model.ResponsibleEmployees\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t<td>\r\n                                        <!--   vi" +
"sible: ($data.ID()) != ViewModel.Model.CurrentEmployeeID(), -->\r\n");

            
            #line 421 "..\..\Views\Natural\Index.cshtml"
                                         
            
            #line default
            #line hidden
            
            #line 421 "..\..\Views\Natural\Index.cshtml"
                                          if (accessLevel.Contains("11") || accessLevel.Contains("12"))
                                         {

            
            #line default
            #line hidden
WriteLiteral("                                             <a");

WriteLiteral(" href=\"javascript: void(0);\"");

WriteLiteral(" data-bind=\"\r\n\t\t\t\t\t\t\t\t\t\t\t\tclick: $root.removeResponsibleEmployee\r\n\t\t\t\t\t\t\t\t\t\t\t\"");

WriteAttribute("title", Tuple.Create(" title=\"", 18290), Tuple.Create("\"", 18354)
            
            #line 425 "..\..\Views\Natural\Index.cshtml"
, Tuple.Create(Tuple.Create("", 18298), Tuple.Create<System.Object, System.Int32>(global::Resources.Resources.Kesco_Persons_Web_VW_1001
            
            #line default
            #line hidden
, 18298), false)
);

WriteLiteral("\r\n                                                 ><span");

WriteLiteral(" class=\"ui-icon ui-icon-minus text-ui-icon\"");

WriteLiteral(">&nbsp;</span></a>\r\n");

            
            #line 427 "..\..\Views\Natural\Index.cshtml"
                                         }

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t<a");

WriteLiteral(" class=\"employeeControl\"");

WriteLiteral(" title=\"$data.FullName()\"");

WriteLiteral(" href=\"javascript: void(0)\"");

WriteLiteral(@"
											data-bind=""
												attr: { 
													id: $data.ID(), 
													'data-employee-id': $data.ID(), 
													alt: $data.FullName(), 
													title: $data.FullName()
												},
												click: function() { ViewModel.showUser($data.ID()); },
												dynamicLink: { 
													value: $data.ID(), 
													source: '");

            
            #line 439 "..\..\Views\Natural\Index.cshtml"
                                                         Write(Url.Action("GetItem", "EmployeeSelect"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n\t\t\t\t\t\t\t\t\t\t\t\t\ttooltipSource: \'");

            
            #line 440 "..\..\Views\Natural\Index.cshtml"
                                                                Write(Configuration.AppSettings.URI_user_info);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n\t\t\t\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t\t\"");

WriteLiteral("></a>\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t</tbody>\r\n\t\t\t\t\t\t\t<tbody");

WriteLiteral(" data-bind=\"visible: Model.ResponsibleEmployees().length == 0\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<td>\r\n                                    <span");

WriteLiteral(" id=\"responsibleValidationMessage\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" style=\"COLOR: #ff0000; font-weight:100;  font-size: 10px;\"");

WriteLiteral(">");

            
            #line 449 "..\..\Views\Natural\Index.cshtml"
                                                                                                      Write(Kesco.Persons.Web.Localization.Resources.Views_NaturalPerson_Validation_Responsible);

            
            #line default
            #line hidden
WriteLiteral("</label> \r\n                                    </span>\r\n                         " +
"          \r\n                                </td>\r\n\t\t\t\t\t\t\t</tbody>\r\n\t\t\t\t\t\t</tabl" +
"e>\r\n\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t</table>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t");

WriteLiteral("\r\n\r\n\t\t<tr");

WriteLiteral(" valign=\"top\"");

WriteLiteral("  data-bind=\"visible: ShowPersonData\"");

WriteLiteral(">\r\n\t\t\t<td");

WriteLiteral(" width=\"150px\"");

WriteLiteral(" style=\"border-top: 1px outset;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 465 "..\..\Views\Natural\Index.cshtml"
           Write(Html.LabelFor(m => m.Model.Card.Comment));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" style=\"border-top: 1px outset;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 468 "..\..\Views\Natural\Index.cshtml"
           Write(Html.EditorFor(m => m.Model.Card.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 469 "..\..\Views\Natural\Index.cshtml"
           Write(Html.ValidationMessageFor(m => m.Model.Card.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\r\n\t\t</table>\r\n");

            
            #line 474 "..\..\Views\Natural\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 479 "..\..\Views\Natural\Index.cshtml"
  
    Html.RegisterScript(@"
		;(function(scope, $) {{
			// поиск страна регистрации 
			scope.ViewModel.Model.Card.TerritoryID.__SearchParameters.HowSearch(1); // начинается с
			scope.ViewModel.Model.Card.TerritoryID.__SearchParameters.AreaIDs.push(2); // является страной

			// поиск бизнес-проекта 
			scope.ViewModel.Model.Card.BusinessProjectID.__SearchParameters.HowSearch(1); // начинается с

		}})(window, jQuery);
		
	");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Header", () => {

WriteLiteral("\r\n\t<div");

WriteLiteral(" id=\"toolBar\"");

WriteLiteral(" class=\"ui-widget-header ui-corner-all kui-toolbar\"");

WriteLiteral("\r\n\t\tstyle=\"padding: 2px;\"");

WriteLiteral("\r\n\t\tdata-bind=\"visible: PageLoaded\"");

WriteLiteral(">\r\n\t\t<table");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" style=\"margin-top: -2px;\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n\t\t<tr");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(">\r\n\t\t\t<td >&nbsp;\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-bind=\" \r\n\t\t\t\t\t\tclick: function() { ViewModel.Model.Confirmed(false); $(\'#Su" +
"bmitButton\').click(); },\r\n\t\t\t\t\t\tjqueryui: { widget: \'button\', options: { icons: " +
"{ primary: \'ui-icon-disk\' } } }\r\n\t\t\t\t\t\"");

WriteLiteral(">");

            
            #line 504 "..\..\Views\Natural\Index.cshtml"
                  Write(global::Resources.Resources.GUI_Button_Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-bind=\"\r\n\t\t\t\t\t\tclick: Delete,\r\n\t\t\t\t\t\tjqueryui: { widget: \'button\', options: " +
"{ disabled: !ViewModel.Model.Card.ID() || ViewModel.Model.CardsNumber()<=1, icon" +
"s: { primary: \'ui-icon-trash\' } } }\r\n\t\t\t\t\t\"");

WriteLiteral(">");

            
            #line 508 "..\..\Views\Natural\Index.cshtml"
                  Write(global::Resources.Resources.GUI_Button_Delete);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" data-bind=\" \r\n\t\t\t\t\t\tclick: closeDialog, \r\n\t\t\t\t\t\tjqueryui: { widget: \'button\', op" +
"tions: { icons: { primary: \'ui-icon-cancel\' } } }\r\n\t\t\t\t\t\"");

WriteLiteral(">");

            
            #line 512 "..\..\Views\Natural\Index.cshtml"
                  Write(global::Resources.Resources.GUI_Button_Cancel);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t</td>\r\n\t\t\t<td");

WriteLiteral(" nowrap=\"nowrap\"");

WriteLiteral(" style=\"width: 30px;\"");

WriteLiteral(">\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" style=\"\"");

WriteLiteral("\r\n\t\t\t\t\t\tdata-bind=\"jqueryui: { widget: \'button\', options: { text: false, icons: {" +
" primary: \'ui-icon-help\' }}}, click: showHelp\"");

WriteLiteral("\r\n\t\t\t\t\t>");

            
            #line 517 "..\..\Views\Natural\Index.cshtml"
                 Write(Kesco.Web.Mvc.UI.Controls.Localization.Resources.GUI_Menu_Help);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t</td>\r\n                 </tr>\r\n\t\t</table>\r\n\t</div>\r\n");

});

WriteLiteral("\r\n\r\n");

DefineSection("Footer", () => {

WriteLiteral("\r\n\r\n");

            
            #line 527 "..\..\Views\Natural\Index.cshtml"
Write(Html.CommonScriptCode("Natural_Footer",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "<script>\r\n");

            
            #line 529 "..\..\Views\Natural\Index.cshtml"
  
    bool isMvc = (Request["clr"] ?? "0") == "0";

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"
    function showTranslateValidationErrors(name, hide) {
        if(hide == true || hide == ""true"") hide = ""hide"";
        if(hide == false || hide == ""false"") hide = ""show"";
        if(name == 'firstName') { 
               $('#Model_Card_FirstNameLat').qtip(hide);
        }
        if(name == ""lastName"") {
                   $('#Model_Card_LastNameLat').qtip(hide);
        }
        if(name == ""middleName"") {
                $('#Model_Card_MiddleNameLat').qtip(hide);
        }
    }


    function translateName(name)
    {
        window.ViewModel.translateName(name);
        showTranslateValidationErrors(name, false);
       if(name == 'lastName') {
            $('#Model_Card_LastNameLat').focus();
       }
        if(name == 'firstName') {
            $('#Model_Card_FirstNameLat').focus();
       }
        if(name == 'middleName') {
            $('#Model_Card_MiddleNameLat').focus();
       }
        
    }

    function returnResult(result) {

");

            
            #line 565 "..\..\Views\Natural\Index.cshtml"
		
            
            #line default
            #line hidden
            
            #line 565 "..\..\Views\Natural\Index.cshtml"
         if (isMvc)
  {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\t\t\t");

WriteLiteralTo(__razor_template_writer, " var arr = []; arr.push(result);\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t\t");

WriteLiteralTo(__razor_template_writer, " closeDialogAndReturnValue(JSON.stringify(arr));\r\n");

            
            #line 569 "..\..\Views\Natural\Index.cshtml"
		}
  else
  {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\t\t\t");

WriteLiteralTo(__razor_template_writer, " var retVal = result.value + String.fromCharCode(31) + result.label;\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t\t");

WriteLiteralTo(__razor_template_writer, " DialogPageReturn(retVal, 0);\r\n");

            
            #line 574 "..\..\Views\Natural\Index.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\t}\r\n\r\n    function getResponsibleIds() {\r\n        var employeeControlIds = \'\';\r\n\t" +
"    for (var i = 0; i < $(\'.employeeControl\').length; i++) {{\r\n\t            if(i" +
" == ($(\'.employeeControl\').length - 1))\r\n\t\t                {{ employeeControlIds" +
"+= $(\'.employeeControl\')[i].id; }} \r\n  \t            else {{employeeControlIds+= " +
"$(\'.employeeControl\')[i].id; employeeControlIds+= \',\'; }}  \r\n            }}\r\n\r\n " +
"       return employeeControlIds;\r\n    }\r\n    \r\n\r\n\r\n    function checkSexValid()" +
" {\r\n\t    if(ViewModel.Model.Card.Sex() == null || ViewModel.Model.Card.Sex() == " +
"\"\") {\r\n\t        sexValidationMessage.style.display = \"table\";\r\n        }\r\n\t    e" +
"lse {\r\n            sexValidationMessage.style.display = \"none\";\r\n        }\r\n\t}\r\n" +
"\r\n    function checkNicknameValid() {\r\n\t    if(ViewModel.Model.Card.Nickname() =" +
"= null || ViewModel.Model.Card.Nickname() == \"\") {\r\n\t        nicknameValidationM" +
"essage.style.display = \"table\";\r\n        }\r\n\t    else {\r\n            nicknameVal" +
"idationMessage.style.display = \"none\";\r\n        }\r\n\t}\r\n    \r\n\r\n     function che" +
"ckFioValid() {\r\n        if((ViewModel.Model.Card.LastNameRus() == null || ViewMo" +
"del.Model.Card.LastNameRus() == \"\") && \r\n            (ViewModel.Model.Card.First" +
"NameRus() == null || ViewModel.Model.Card.FirstNameRus() == \"\") &&\r\n            " +
"    (ViewModel.Model.Card.MiddleNameRus() == null || ViewModel.Model.Card.Middle" +
"NameRus() == \"\")) \r\n        {\r\n            fioValidationMessage.style.display = " +
"\"table\";\r\n        }\r\n         else \r\n        {\r\n            fioValidationMessage" +
".style.display = \"none\";\r\n        }\r\n     }\r\n\r\n    function setCountryFildEmpty(" +
") {\r\n             var countryField = document.getElementById(\'Model_Card_Territo" +
"ryID___Autocomplete\');\r\n            if(countryField == null) return;\r\n          " +
"      countryField.onfocusout = function() {\r\n                    if(countryFiel" +
"d.value == null || countryField.value == \"\") {\r\n                        ViewMode" +
"l.Model.Card.TerritoryID(\'\');\r\n                    }\r\n                };\r\n      " +
"  }\r\n    \r\n     function setBuissnesFieldEmpty() {\r\n             var buissnessFi" +
"eld = document.getElementById(\'Model_Card_BusinessProjectID___Autocomplete\');\r\n " +
"           if(buissnessField == null) return;\r\n                buissnessField.on" +
"focusout = function() {\r\n                    if(buissnessField.value == null || " +
"buissnessField.value == \"\") {\r\n                        ViewModel.Model.Card.Busi" +
"nessProjectID(\'\');\r\n                    }\r\n                };\r\n        }\r\n\r\n\t$(d" +
"ocument).ready(function () {\r\n\r\n        ");

WriteLiteralTo(__razor_template_writer, "\r\n        $(\'#Model_Card_LastNameLat\').qtip({\r\n              content: {\r\n        " +
"          text: \'");

            
            #line 647 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Kesco.Persons.Web.Localization.Resources.Validation_NaturalPerson_CheckSecondNameOnLat);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
             },
             position: {
		          at: 'bottom left'
		     },
             style: {
                 classes: 'qtip-light',
                 wight: '50px'
             },
          show: '',
	      hide: ''
          });

          $('#Model_Card_FirstNameLat').qtip({
              content: {
                  text: '");

            
            #line 662 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Kesco.Persons.Web.Localization.Resources.Validation_NaturalPerson_CheckFirstNameOnLat);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
             },
             position: {
		          at: 'bottom left'
		     },
             style: {
                 classes: 'qtip-light',
                 wight: '50px'
             },
          show: '',
	      hide: ''
          });

          $('#Model_Card_MiddleNameLat').qtip({
              content: {
                  text: '");

            
            #line 677 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Kesco.Persons.Web.Localization.Resources.Validation_NaturalPerson_CheckMiddleNameOnLat);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
             },
             position: {
		          at: 'bottom left'
		     },
             style: {
                 classes: 'qtip-light',
                 wight: '50px'
             },
          show: '',
	      hide: ''
          });

	    ");

WriteLiteralTo(__razor_template_writer, @"

	    
	    document.getElementById('Model_Card_LastNameLat').onfocusout = function() { showTranslateValidationErrors('lastName', true); };
	    document.getElementById('Model_Card_FirstNameLat').onfocusout = function() { showTranslateValidationErrors('firstName', true); };
	    document.getElementById('Model_Card_MiddleNameLat').onfocusout = function() { showTranslateValidationErrors('middleName', true); };



        ");

WriteLiteralTo(__razor_template_writer, @"
	    document.getElementById('Model_Card_Sex__male').onclick = function() { sexValidationMessage.style.display = ""none""; };
	    document.getElementById('Model_Card_Sex__female').onclick = function() { sexValidationMessage.style.display = ""none""; };
	    var firstNameTextBox = document.getElementById('Model_Card_FirstNameRus');
	    firstNameTextBox.onchange = function() { 
	        if (firstNameTextBox.value != null && firstNameTextBox.value != """") {window.fioValidationMessage.style.display = ""none"";}
	        if (firstNameTextBox.value == null || firstNameTextBox.value == """"){ window.ViewModel.Model.Card.FirstNameLat(null);}
	    };
	    var lastNameTextBox = document.getElementById('Model_Card_LastNameRus');
	    lastNameTextBox.onchange = function() { 
	        if (lastNameTextBox.value != null && lastNameTextBox.value != """") {window.fioValidationMessage.style.display = ""none"";}
	        if (lastNameTextBox.value == null || lastNameTextBox.value == """"){ window.ViewModel.Model.Card.LastNameLat(null);}
	    };
	    var middleNameTextBox = document.getElementById('Model_Card_MiddleNameRus');
	    middleNameTextBox.onchange = function() {
	        if (middleNameTextBox.value != null && middleNameTextBox.value != """") {window.fioValidationMessage.style.display = ""none"";}
	        if (middleNameTextBox.value == null || middleNameTextBox.value == """"){window.ViewModel.Model.Card.MiddleNameLat(null); }
	    };

		");

WriteLiteralTo(__razor_template_writer, "\r\n\t\tViewModel.ControlNameToFocus = \'");

            
            #line 720 "..\..\Views\Natural\Index.cshtml"
         WriteTo(__razor_template_writer, Model.ShowPersonData ? "#Model_Card_TerritoryID___Autocomplete" : "#Model_Card_LastNameRus");

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"';

        ViewModel.prevVersionUrl = """";

        
		$(""#NaturalPersonForm"").submit(function () {
			// this - DOM element - form
			var $form = $(this);

			if ($form.valid()) {
				window.ViewModel.Model.Confirmed(false);
				window.ViewModel.save();
			}
		    if(ViewModel.Model.Card.PersonID() == null || ViewModel.Model.Card.PersonID() == """") {
		       
		        checkFioValid();
		        checkNicknameValid();
		        checkSexValid();
		    }
		    return false;
		});

	
	    window.ViewModel.ChooseEmpls = function (responsibleIDs) {
			$.ajax({
				url: '");

            
            #line 745 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Url.Action("Dispatch"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
				type: 'POST',
				data: window.ko.toJSON({
					command: 'chooseempls',
					control: responsibleIDs,
					model:  window.ko.mapping.toJS(window.ViewModel.Model)
				}),
				contentType: ""application/json; charset=utf-8""
			});
		};


		window.ViewModel.save = function () {
			$.ajax({
				url: '");

            
            #line 759 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Url.Action("Dispatch"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
				type: 'POST',
				data: window.ko.toJSON({
					command: 'save',
					control: null,
					model:  window.ko.mapping.toJS(window.ViewModel.Model)
				}),
				contentType: ""application/json; charset=utf-8""
			});
		};
	    

        window.ViewModel.translateName = function (name) {
			$.ajax({
				url: '");

            
            #line 773 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Url.Action("Dispatch"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
				type: 'POST',
				data: window.ko.toJSON({
					command: 'translitName',
					control: name,
					model:  window.ko.mapping.toJS(window.ViewModel.Model)
				}),
				contentType: ""application/json; charset=utf-8""
			});
		};

		ViewModel.Delete = function () {
			if(ViewModel.Model.Card.ID()==0) return;
			confirmAction('");

            
            #line 786 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, global::Resources.Resources.Persons_Delete_Confirm_Title);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\', \'");

            
            #line 786 "..\..\Views\Natural\Index.cshtml"
                                                          WriteTo(__razor_template_writer, Html.Raw(global::Resources.Resources.Persons_Card_Delete_Confirm_Text));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\', \'");

            
            #line 786 "..\..\Views\Natural\Index.cshtml"
                                                                                                                                      WriteTo(__razor_template_writer, global::Resources.Resources.GUI_Button_Confirm);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\', function(){ \r\n\t\t\t\t\t$.ajax({\r\n\t\t\t\t\t\turl: \'");

            
            #line 788 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\',\r\n\t\t\t\t\t\ttype: \'POST\',\r\n\t\t\t\t\t\tdata: window.ko.toJSON({\r\n\t\t\t\t\t\t\tmodel: ko.mapping" +
".toJS(ViewModel.Model)\r\n\t\t\t\t\t\t}),\r\n\t\t\t\t\t\tcontentType: \"application/json; charset" +
"=utf-8\",\r\n\t\t\t\t\t\tcomplete: function() {\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t});\r\n\t\t\t\t}, \'");

            
            #line 797 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, global::Resources.Resources.GUI_Button_Cancel);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"', null, null);
		};

		ViewModel.removeResponsibleEmployee = function() {
			//if (ko.mapping.toJS(this.ID) != ViewModel.Model.CurrentEmployeeID()) {
				ViewModel.Model.ResponsibleEmployees.remove(this);
			//}
		};



		// TODO: Make universary
		ViewModel.openChooseEmployeesDialog = function() {
			var selected = [];
			var list = ko.mapping.toJS(ViewModel.Model.ResponsibleEmployees());
			for(var i=0; i<list.length; i++) {
				selected[i] = list[i].ID.toString();
			}
			selected = selected.join("","");
			var callbackUrl = encodeURIComponent('");

            
            #line 816 "..\..\Views\Natural\Index.cshtml"
                   WriteTo(__razor_template_writer, Url.FullPathAction("DialogResult", "Default"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\');\r\n\t\t\tvar title = encodeURIComponent(\'");

            
            #line 817 "..\..\Views\Natural\Index.cshtml"
             WriteTo(__razor_template_writer, global::Resources.Resources.Kesco_Persons_Web_VW_1000);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\');\r\n\t\t\tvar url;\r\n\t\t\turl = \'");

            
            #line 819 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, Html.Raw(Configuration.AppSettings.URI_user_search));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "?");

            
            #line 819 "..\..\Views\Natural\Index.cshtml"
                                           WriteTo(__razor_template_writer, Html.Raw(Configuration.URI_user_search_QS ?? "t=1"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"&selectedid='+selected;
			url = $.validator.format(url, callbackUrl, title);

			openPopupWindow(url, null, function(result) {
				if ($.isArray(result)) {
					ViewModel.Model.ResponsibleEmployees.removeAll();
					for(var i=0; i<result.length; i++)
						ViewModel.Model.ResponsibleEmployees.push({ID: ko.observable(result[i].ID), FullName: ko.observable(result[i].Name) });
				}
			}, ""wnd_ChooseEmployees"", 800, 600);

		  
		};

");

            
            #line 833 "..\..\Views\Natural\Index.cshtml"
  
    ModelMetadata pmm = ViewData.ModelMetadata
        .Properties.First(p => p.PropertyName == "Model")
        .Properties.First(p => p.PropertyName == "Card");

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n\r\n\t\t$(\'#");

            
            #line 839 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\').mask();\r\n\t\t$(\'#");

            
            #line 840 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\').mask();\r\n\t\t$(\'#");

            
            #line 841 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"').mask();

       
	  
//	    var updateRegistrationFormat = function (tid) {
//			function repeat(symbol, length) {
//				var s="""", len = 0+length;
//				for (var i = 0; i < len; i++) s += symbol;
//				return s;
//			}
//			var result = window.ViewModel.FormatRegistrations.filterByProperty(""ID"", tid || 0);
//			var registrationFormat = window.ViewModel.FormatRegistration;
//			if (result().length > 0) {
//				format = result()[0];
//                registrationFormat.OGRNLength2(format.OGRNLength2());
//                registrationFormat.OGRNFormat2(format.OGRNFormat2());
//				registrationFormat.OGRNName(format.OGRNName());
//				registrationFormat.INNName(format.INNName());
//				registrationFormat.INNLength2(format.INNLength2());
//				registrationFormat.OKPOName(format.OKPOName());
//				registrationFormat.OKPOLength2(format.OKPOLength2());
//			} else {
//				registrationFormat.OGRNName('");

            
            #line 863 "..\..\Views\Natural\Index.cshtml"
              WriteTo(__razor_template_writer, pmm.Properties.First(p => p.PropertyName == "OGRN").GetDisplayName());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"');
//				registrationFormat.INNName("""");
//				registrationFormat.INNLength2(0);
//				registrationFormat.OGRNFormat2(""####################"");
//			    registrationFormat.OGRNLength2(20);
//				registrationFormat.OKPOName("""");
//				registrationFormat.OKPOLength2(0);
//			}

//			try {
//				var multiplicator = 8;
//				var len = 0;
//			    var baseMask;
//                
//                len = registrationFormat.OGRNLength2();
//                baseMask = registrationFormat.OGRNFormat2();
//               

//				$('#");

            
            #line 881 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"')
//					.mask(""option"", { mask: baseMask })
//					.width(len*multiplicator).parent().width(len*multiplicator);

//                    if(len == 0) {
//                      document.getElementById(""OGRNFields"").style.display = ""none"";
//                       
//                    }
//			        else {
//                         document.getElementById(""OGRNFields"").style.display = """";
//                    }
//                     document.getElementById('OGRNlenghtField').innerText = len;
//			    len = registrationFormat.INNLength2()?registrationFormat.INNLength2():12;
//				$('#");

            
            #line 894 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')\r\n//\t\t\t\t\t.mask(\"option\", { mask: repeat(\"9\", len) })\r\n//\t\t\t\t\t.width(len*multipl" +
"icator).parent().width(len*multiplicator);\r\n\r\n//\t\t\t\tlen = registrationFormat.OKP" +
"OLength2()?registrationFormat.OKPOLength2():10;\r\n//\t\t\t\t$(\'#");

            
            #line 899 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')\r\n//\t\t\t\t\t.mask(\"option\", { mask: repeat(\"9\", len) })\r\n//\t\t\t\t\t.width(len*multipl" +
"icator).parent().width(len*multiplicator);\r\n//\t\t\t    \r\n//                \r\n//\t\t\t" +
"} catch(e) { \r\n//\t\t\t\tif (window.console) console.log(e);\r\n//\t\t\t}\r\n//\t\t};\r\n\t    \r" +
"\n\r\n        function clearFieldsWhenIncFormChanged(incFormName)\r\n\t    {\r\n\t       " +
" if(incFormName == \'Глава крестьянских (фермерских) хозяйств\') {\r\n\t            w" +
"indow.ViewModel.Model.Card.OKONH(\"\");\r\n                window.ViewModel.Model.Ca" +
"rd.RwID(\"\");\r\n            }\r\n            else if(incFormName == \'Адвокат, учреди" +
"вший адвокатский кабинет\' || incFormName == \'Нотариус, занимающийся частной прак" +
"тикой\') {\r\n\t            window.ViewModel.Model.Card.OKONH(\"\");\r\n                " +
"window.ViewModel.Model.Card.OGRN(\"\");\r\n                window.ViewModel.Model.Ca" +
"rd.OKPO(\"\");\r\n                window.ViewModel.Model.Card.OKVED(\"\");\r\n          " +
"      window.ViewModel.Model.Card.KPP(\"\");\r\n                window.ViewModel.Mod" +
"el.Card.RwID(\"\");\r\n            }\r\n        }\r\n\r\n\t    var showRequisitesFieldsFrom" +
"IncForm = function (tid) {\r\n\t        $(\'#Model_Card_IncorporationFormID-button s" +
"pan\');\r\n\t        var incFormName = $(\'#Model_Card_IncorporationFormID-button spa" +
"n\')[0].innerText;\r\n\t        if(incFormName == \'Глава крестьянских (фермерских) х" +
"озяйств\') {\r\n                window.ViewModel.Model.ShowReqFromIncForm = \'hideOK" +
"ONH\'; \r\n                $(\'#OKONHFields\')[0].style.display = \"none\";\r\n          " +
"      $(\'#RwIDFields\')[0].style.display = \"none\";\r\n\t            \r\n              " +
"  if(window.ViewModel.ShowPersonRequisites() && window.ViewModel.Model.Card.Inco" +
"rporationFormID())$(\'#OKVEDFields\')[0].style.display = \"\";\r\n                if(w" +
"indow.ViewModel.ShowPersonRequisites() && window.ViewModel.Model.Card.Incorporat" +
"ionFormID())$(\'#KPPFields\')[0].style.display = \"\";\r\n                if(window.Vi" +
"ewModel.ShowPersonData())$(\'#OGRNFields\')[0].style.display = \"\";\r\n              " +
"  if(window.ViewModel.ShowPersonData() && window.ViewModel.FormatRegistration.OK" +
"POLength2()) $(\'#OKPOFields\')[0].style.display = \"\";\r\n                clearField" +
"sWhenIncFormChanged(incFormName);\r\n            }\r\n            else if(incFormNam" +
"e == \'Адвокат, учредивший адвокатский кабинет\' || incFormName == \'Нотариус, зани" +
"мающийся частной практикой\') {\r\n                window.ViewModel.Model.ShowReqFr" +
"omIncForm = \'hideAllExINN\';\r\n                $(\'#OGRNFields\')[0].style.display =" +
" \"none\";\r\n                $(\'#OKPOFields\')[0].style.display = \"none\";\r\n         " +
"       $(\'#OKONHFields\')[0].style.display = \"none\";\r\n                $(\'#OKVEDFi" +
"elds\')[0].style.display = \"none\";\r\n                $(\'#KPPFields\')[0].style.disp" +
"lay = \"none\";\r\n                $(\'#RwIDFields\')[0].style.display = \"none\";\r\n    " +
"            clearFieldsWhenIncFormChanged(incFormName);\r\n            } else {\r\n " +
"               window.ViewModel.Model.ShowReqFromIncForm = \'\';\r\n                " +
"if(window.ViewModel.ShowPersonData())$(\'#OGRNFields\')[0].style.display = \"\";\r\n  " +
"              if(window.ViewModel.ShowPersonData() && window.ViewModel.FormatReg" +
"istration.OKPOLength2())$(\'#OKPOFields\')[0].style.display = \"\";\r\n               " +
" if(window.ViewModel.ShowPersonRequisites() && window.ViewModel.Model.Card.Incor" +
"porationFormID())$(\'#OKONHFields\')[0].style.display = \"\";\r\n                if(wi" +
"ndow.ViewModel.ShowPersonRequisites() && window.ViewModel.Model.Card.Incorporati" +
"onFormID())$(\'#OKVEDFields\')[0].style.display = \"\";\r\n                if(window.V" +
"iewModel.ShowPersonRequisites() && window.ViewModel.Model.Card.IncorporationForm" +
"ID())$(\'#KPPFields\')[0].style.display = \"\";\r\n                if(window.ViewModel" +
".ShowPersonRequisites() && window.ViewModel.Model.Card.IncorporationFormID())$(\'" +
"#RwIDFields\')[0].style.display = \"\";\r\n            }\r\n            \r\n        };\r\n\r" +
"\n\t    var updateRegistrationFormat = function (tid) {\r\n\t\t\tfunction repeat(symbol" +
", length) {\r\n\t\t\t\tvar s=\"\", len = 0+length;\r\n\t\t\t\tfor (var i = 0; i < len; i++) s " +
"+= symbol;\r\n\t\t\t\treturn s;\r\n\t\t\t}\r\n\t\t\tvar result = window.ViewModel.FormatRegistra" +
"tions.filterByProperty(\"ID\", tid || 0);\r\n\t\t\tvar registrationFormat = window.View" +
"Model.FormatRegistration;\r\n\t\t\tif (result().length > 0) {\r\n\t\t\t\tformat = result()[" +
"0];\r\n\t\t\t\tregistrationFormat.OGRNFormat(format.OGRNFormat());\r\n\t\t\t\tregistrationFo" +
"rmat.OGRNName(format.OGRNName());\r\n\t\t\t\tregistrationFormat.INNName(format.INNName" +
"());\r\n\t\t\t\tregistrationFormat.INNLength2(format.INNLength2());\r\n\t\t\t\tregistrationF" +
"ormat.OKPOName(format.OKPOName());\r\n\t\t\t\tregistrationFormat.OKPOLength2(format.OK" +
"POLength2());\r\n\t\t\t} else {\r\n\t\t\t\tregistrationFormat.OGRNName(\'");

            
            #line 978 "..\..\Views\Natural\Index.cshtml"
              WriteTo(__razor_template_writer, pmm.Properties.First(p => p.PropertyName == "OGRN").GetDisplayName());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"');
				registrationFormat.INNName("""");
				registrationFormat.INNLength2(0);
				registrationFormat.OGRNFormat(""####################"");
				registrationFormat.OKPOName("""");
				registrationFormat.OKPOLength2(0);
			}

			try {
				var multiplicator = 8;
				var len = registrationFormat.OGRNFormat().length;
				$('#");

            
            #line 989 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')\r\n\t\t\t\t\t.mask(\"option\", { mask: registrationFormat.OGRNFormat() })\r\n\t\t\t\t\t.width(" +
"len*multiplicator).parent().width(len*multiplicator);\r\n\r\n\t\t\t\tlen = registrationF" +
"ormat.INNLength2()?registrationFormat.INNLength2():12;\r\n\t\t\t\t$(\'#");

            
            #line 994 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')\r\n\t\t\t\t\t.mask(\"option\", { mask: repeat(\"9\", len) })\r\n\t\t\t\t\t.width(len*multiplicat" +
"or).parent().width(len*multiplicator);\r\n\r\n\t\t\t\tlen = registrationFormat.OKPOLengt" +
"h2()?registrationFormat.OKPOLength2():10;\r\n\t\t\t\t$(\'#");

            
            #line 999 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')\r\n\t\t\t\t\t.mask(\"option\", { mask: repeat(\"9\", len) })\r\n\t\t\t\t\t.width(len*multiplicat" +
"or).parent().width(len*multiplicator);\r\n\r\n\t\t\t    $(\'#");

            
            #line 1003 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')[0].maxLength = 200;\r\n\t\t\t    $(\'#");

            
            #line 1004 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')[0].maxLength = 200;\r\n\t\t\t    $(\'#");

            
            #line 1005 "..\..\Views\Natural\Index.cshtml"
WriteTo(__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\')[0].maxLength = 200;\r\n\t\t\t} catch(e) { \r\n\t\t\t\tif (window.console) console.log(e);" +
"\r\n\t\t\t}\r\n\t\t};\r\n\t\tupdateRegistrationFormat(window.ViewModel.Model.Card.TerritoryID" +
"());\r\n        var testoption = function (id) {\r\n             if(window.ViewModel" +
".Model.Card.IncorporationFormID() != 91 && window.ViewModel.Model.Card.Nickname(" +
") != null && window.ViewModel.Model.Card.Nickname().substring(0, 3) == \"ИП \") {\r" +
"\n                window.ViewModel.Model.Card.Nickname91 = window.ViewModel.Model" +
".Card.Nickname().substring(3, 200);\r\n                return;\r\n            }\r\n   " +
"         //ViewModel.Model.Card.Nickname(\"\");\r\n            var haveAllready = 0;" +
"\r\n            for (var i = 0; i < id.length; i++) {\r\n                if(id[i].ID" +
" == window.ViewModel.Model.Card.Nickname())haveAllready = 1;\r\n                if" +
"(id[i].Nickname == window.ViewModel.Model.Card.Nickname()) window.ViewModel.Mode" +
"l.Card.Nickname91 = id[i].ID;\r\n\t        }\r\n            if(haveAllready != 0) win" +
"dow.ViewModel.Model.Card.Nickname91 = null;\r\n        }\r\n\t    \r\n        var testn" +
"ick = function (id) {\r\n            if(id == \"\") {\r\n                if (window.Vi" +
"ewModel.Model.Card.Nickname91 != null) {\r\n                    window.ViewModel.M" +
"odel.Card.Nickname(window.ViewModel.Model.Card.Nickname91);\r\n                   " +
"}\r\n                 window.ViewModel.Model.Card.Nickname91 = null;\r\n            " +
"}\r\n\r\n        }\r\n\t    ViewModel.Model.Card.Nickname.subscribe(testnick);\r\n\t    wi" +
"ndow.ViewModel.Model.Card.IncorporationFormID.subscribe(showRequisitesFieldsFrom" +
"IncForm);\r\n\t\twindow.ViewModel.Model.Card.TerritoryID.subscribe(updateRegistratio" +
"nFormat);\r\n\t\twindow.ViewModel.NicknameVariants = window.ko.computed(function () " +
"{\r\n\t\t    if(ViewModel.Model.Card.Nickname() != null && ViewModel.Model.Card.Nick" +
"name() != \"\") {\r\n\t\t        checkNicknameValid();\r\n\t\t    }\r\n\t\t    var options = [" +
"];\r\n\t\t\tvar form = \'\';\r\n\t\t    updateRegistrationFormat(window.ViewModel.Model.Car" +
"d.TerritoryID());\r\n\t\t\tif(ViewModel.Model.Card.IncorporationFormID()==91) form = " +
"\'ИП \';\r\n\r\n\t\t\tfunction getSecondNames(fn, mn, lat) {\r\n\t\t\t\tvar secondNames = [];\r\n" +
"\r\n\t\t\t\tif (fn)\r\n\t\t\t\t\tif (mn.length > 0) {\r\n\t\t\t\t\t\tsecondNames.push(\"\" + fn + \" \" +" +
" mn); // FirstName MiddleName\r\n\r\n\t\t\t\t\t\tif (fn.length > 1 && mn.length > 1) {\r\n\t\t" +
"\t\t\t\t\tsecondNames.push(\"\" + fn.substr(0, 1).toUpperCase() + \". \" + mn.substr(0, 1" +
").toUpperCase() + \".\"); // Initials: F. M.\r\n\t\t\t\t\t\t\tif (lat)\r\n\t\t\t\t\t\t\t\tsecondNames" +
".push(\"\" + fn + \" \" + mn.substr(0, 1).toUpperCase() + \".\"); // Initials: F. M.\r\n" +
"\t\t\t\t\t\t}\r\n\t\t\t\t\t} else {\r\n\t\t\t\t\t\tsecondNames.push(\"\" + fn); // FirstName\r\n\r\n\t\t\t\t\t\ti" +
"f (fn.length > 1)\r\n\t\t\t\t\t\t\tsecondNames.push(\"\" + fn.substr(0, 1).toUpperCase() + " +
"\".\"); // Initials: F.\r\n\t\t\t\t\t}\r\n\r\n\t\t\t\treturn secondNames;\r\n\t\t\t}\r\n\r\n\t\t\tvar secondN" +
"ames;\r\n\r\n\t\t\tvar fn = window.ViewModel.Model.Card.FirstNameRus(); fn = fn ? fn : " +
"\"\";\r\n\t\t\tvar mn = window.ViewModel.Model.Card.MiddleNameRus(); mn = mn ? mn : \"\";" +
"\r\n\t\t\tvar ln = window.ViewModel.Model.Card.LastNameRus(); ln = ln ? ln : \"\";\r\n\r\n\t" +
"\t\tsecondNames = getSecondNames(fn, mn);\r\n\t\t\tvar i;\r\n\r\n\t\t\tif (ln || secondNames.l" +
"ength) {\r\n\t\t\t\tif (secondNames.length)\r\n\t\t\t\t\tfor (i = 0; i < secondNames.length; " +
"i++)\r\n\t\t\t\t\t\tif (ln) {\r\n\t\t\t\t\t\t\toptions.push({ ID: form + ln + \" \" + secondNames[i" +
"], Nickname: ln + \" \" + secondNames[i] });\r\n\t\t\t\t\t\t\toptions.push({ ID: form + sec" +
"ondNames[i] + \" \" + ln, Nickname: secondNames[i] + \" \" + ln });\r\n\t\t\t\t\t\t} else\r\n\t" +
"\t\t\t\t\t\toptions.push({ ID: form + secondNames[i], Nickname: secondNames[i] });\r\n\t\t" +
"\t\telse\r\n\t\t\t\t\toptions.push({ ID: form + ln, Nickname: ln });\r\n\t\t\t}\r\n\r\n\t\t\tfn = win" +
"dow.ViewModel.Model.Card.FirstNameLat(); fn = fn ? fn : \"\";\r\n\t\t\tmn = window.View" +
"Model.Model.Card.MiddleNameLat(); mn = mn ? mn : \"\";\r\n\t\t\tln = window.ViewModel.M" +
"odel.Card.LastNameLat(); ln = ln ? ln : \"\";\r\n\t\t\tsecondNames = getSecondNames(fn," +
" mn, true);\r\n\r\n\t\t\tif (ln || secondNames.length) {\r\n\t\t\t\tif (options.length > 0)\r\n" +
"\t\t\t\t\toptions.push({ ID: null, Nickname: \"---------------------------------------" +
"-------\" });\r\n\t\t\t\tif (secondNames.length)\r\n\t\t\t\t\tfor (i = 0; i < secondNames.leng" +
"th; i++)\r\n\t\t\t\t\t\tif (ln) {\r\n\t\t\t\t\t\t\toptions.push({ ID: form + ln + \" \" + secondNam" +
"es[i], Nickname: ln + \" \" + secondNames[i] });\r\n\t\t\t\t\t\t\toptions.push({ ID: form +" +
" secondNames[i] + \" \" + ln, Nickname: secondNames[i] + \" \" + ln });\r\n\t\t\t\t\t\t} els" +
"e\r\n\t\t\t\t\t\t\toptions.push({ ID: form + secondNames[i], Nickname: secondNames[i] });" +
"\r\n\t\t\t\telse\r\n\t\t\t\t\toptions.push({ ID: form + ln, Nickname: ln });\r\n\t\t\t}\r\n\r\n\t\t\topti" +
"ons.unshift({ID:\'\', Nickname:\'");

            
            #line 1108 "..\..\Views\Natural\Index.cshtml"
               WriteTo(__razor_template_writer, global::Resources.Resources.Kesco_Persons_Web_VW_1005);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\'});\r\n\r\n\r\n\t\t\treturn options;\r\n\t\t});\r\n//\t\twindow.ViewModel.NicknameVariant = windo" +
"w.ko.observable();  \r\n\t    window.ViewModel.NicknameVariants.subscribe(testoptio" +
"n);\r\n        \r\n\t\t");

WriteLiteralTo(__razor_template_writer, @"
		function clearNickname() {
		    if(window.ViewModel.NicknameVariants().length <= 1) {
             window.ViewModel.Model.Card.Nickname("""");
		    }
		}

		window.ViewModel.Model.Card.FirstNameRus	= window.ViewModel.Model.Card.FirstNameRus.extend({ capitalize: true });
		window.ViewModel.Model.Card.MiddleNameRus	= window.ViewModel.Model.Card.MiddleNameRus.extend({ capitalize: true });
		window.ViewModel.Model.Card.LastNameRus		= window.ViewModel.Model.Card.LastNameRus.extend({ capitalize: true });

		window.ViewModel.Model.Card.FirstNameLat	= window.ViewModel.Model.Card.FirstNameLat.extend({ capitalize: true });
		window.ViewModel.Model.Card.MiddleNameLat	= window.ViewModel.Model.Card.MiddleNameLat.extend({ capitalize: true });
		window.ViewModel.Model.Card.LastNameLat		= window.ViewModel.Model.Card.LastNameLat.extend({ capitalize: true });

");

            
            #line 1131 "..\..\Views\Natural\Index.cshtml"
		
            
            #line default
            #line hidden
            
            #line 1131 "..\..\Views\Natural\Index.cshtml"
         if (Model.ShowPersonRequisites)
  {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.FirstNameRus.subscribe(clearNickname);\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.MiddleNameRus.subscribe(clearNickname);\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.LastNameRus.subscribe(clearNickname);\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.FirstNameLat.subscribe(clearNickname);\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.MiddleNameLat.subscribe(clearNickname);\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.LastNameLat.subscribe(clearNickname);\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.IncorporationFormID.subscribe(clearNickname);\r\n");

            
            #line 1140 "..\..\Views\Natural\Index.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n        function getURLParameter(name) {\r\n            return decodeURIComponent" +
"((new RegExp(\'[?|&]\' + name + \'=\' + \'([^&;]+?)(&|#|;|$)\').exec(location.search)|" +
"|[,\"\"])[1].replace(/\\+/g, \'%20\'))||null\r\n        }\r\n\r\n\r\n");

            
            #line 1147 "..\..\Views\Natural\Index.cshtml"
		
            
            #line default
            #line hidden
            
            #line 1147 "..\..\Views\Natural\Index.cshtml"
         if (!Model.Model.Card.ID.HasValue && Request["text"] != null && Request["text"] != "")
        {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\tvar nameParts = getURLParameter(\'text\').replace(/\\s+/gi, \" \").split(\" \");\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.LastNameRus(nameParts[0] || \"\");\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.FirstNameRus(nameParts[1] || \"\");\r\n");

WriteLiteralTo(__razor_template_writer, "\t\t");

WriteLiteralTo(__razor_template_writer, "\twindow.ViewModel.Model.Card.MiddleNameRus(nameParts[2] || \"\");\r\n");

            
            #line 1153 "..\..\Views\Natural\Index.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n\t\twindow.ViewModel.AddressLegalRusIsInLat = window.ko.computed(function () {\r\n\t" +
"\t\treturn checkLatSymbols(ViewModel.Model.Card.AddressLegal());\r\n\t\t});\r\n\r\n\t\twindo" +
"w.ViewModel.LastNameRusIsInLat = window.ko.computed(function () {\r\n\t\t\treturn che" +
"ckLatSymbols(ViewModel.Model.Card.LastNameRus());\r\n\t\t});\r\n\r\n\t\twindow.ViewModel.F" +
"irstNameRusIsInLat = window.ko.computed(function () {\r\n\t\t\treturn checkLatSymbols" +
"(ViewModel.Model.Card.FirstNameRus());\r\n\t\t});\r\n\r\n\t\twindow.ViewModel.MiddleNameRu" +
"sIsInLat = window.ko.computed(function () {\r\n\t\t\treturn checkLatSymbols(ViewModel" +
".Model.Card.MiddleNameRus());\r\n\t\t});\r\n\r\n\t\tfunction adjustLatValue(value, targetO" +
"bservable) {\r\n\t\t\tif (checkLatSymbols(value)) targetObservable(value || \"\");\r\n\t\t}" +
"\r\n\r\n\t\tfunction checkLatSymbols(value) {\r\n\t\t    \r\n\t\t\tif (!$.trim(value || \"\")) re" +
"turn false;\r\n\t\t\tvar pattern = /^[\\x00-\\x7F]+$/;\r\n\t\t\treturn pattern.test(value);\r" +
"\n\t\t}\r\n        \r\n\t\t$(\"#Model_Card_FirstNameRus, #Model_Card_MiddleNameRus, #Model" +
"_Card_LastNameRus, #Model_Card_FirstNameLat, #Model_Card_MiddleNameLat, #Model_C" +
"ard_LastNameLat\")\r\n\t\t\t.bind(\"keydown change\", function() {\r\n\t\t\t\tsetNamesRequired" +
"()\r\n\t\t\t})\r\n\r\n\t\tfunction setNamesRequired() {\r\n\t\t\tvar $inputs = $(\"#Model_Card_Fi" +
"rstNameRus, #Model_Card_MiddleNameRus, #Model_Card_LastNameRus, #Model_Card_Firs" +
"tNameLat, #Model_Card_MiddleNameLat, #Model_Card_LastNameLat\");\r\n\t\t\tvar value = " +
"\"\";\r\n\t\t\t$inputs.each(function() {\r\n\t\t\t\tvalue = value || $(this).val();\r\n\t\t\t});\r\n" +
"\r\n\t\t\tif (value) {\r\n\t\t\t\t$inputs.parent().removeClass(\"ui-state-highlight\");\r\n\t\t\t}" +
" else {\r\n\t\t\t\t$inputs.parent().addClass(\"ui-state-highlight\");\r\n\t\t\t}\r\n\t\t}\r\n\r\n    " +
"    setTimeout(function() { showRequisitesFieldsFromIncForm(null); }, 100);\r\n\t\ts" +
"etTimeout(function() { setNamesRequired(); }, 100);\r\n         setTimeout(functio" +
"n() { setCountryFildEmpty(); }, 100);\r\n\t    setTimeout(function() { setBuissnesF" +
"ieldEmpty(); }, 100);\r\n\t\twindow.ViewModel.gotoPerson = function (param) {\r\n\t\t\twi" +
"ndow.location.href = \"");

            
            #line 1206 "..\..\Views\Natural\Index.cshtml"
     WriteTo(__razor_template_writer, Kesco.Persons.Web.Configuration.AppSettings.URI_person_form);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\" + \"?id=\" + param;\r\n\t\t};\r\n\r\n\t\t$(window).resize(function () {\r\n\t\t\t$(\"#formContain" +
"er\").height($(\"#dialogContentPane\").height()-2);\r\n\t\t\t$(\"#formContainer\").width($" +
"(\"#dialogContentPane\").width()-2);\r\n\t\t});\r\n\r\n\t});\r\n</script>\r\n");

            
            #line 1216 "..\..\Views\Natural\Index.cshtml"
})));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 1218 "..\..\Views\Natural\Index.cshtml"
Write(Html.DisplayFor(m => m.Model.Card, "ChangedByInfo"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
