#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Juridical\Index.cshtml"
    using Kesco.Persons.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Juridical\Index.cshtml"
    using Kesco.Persons.Web.Localization;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Juridical\Index.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Juridical\Index.cshtml"
    using Kesco.Web.Mvc.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Juridical/Index.cshtml")]
    public partial class _Views_Juridical_Index_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Persons.Web.Models.Juridicals.ViewModel>
    {
        public _Views_Juridical_Index_cshtml()
        {
        }
        public override void Execute()
        {






            
            #line 6 "..\..\Views\Juridical\Index.cshtml"
  
    Model
        .GetScriptCapabilities()
        .DisableGridScript()
        .DisableTreeScript();
    string[] accessLevel = Model.EmployeeRoles.Split(',');
    ViewBag.Title = Model.PageTitle;
    Layout = "~/Views/Shared/_Layout.cshtml";
    /* Ищем в URL параметр hideOldVer, пишем его в сессию. Требуется для скрытия кнопки "Открыть в старой версии"  */
    string hideOldVerRequest = HttpContext.Current.Request["hideOldVer"];
    var hideOldVerSession = HttpContext.Current.Session["hideOldVer"];
    string hideOldVer = "false";

    if (!String.IsNullOrEmpty(hideOldVerRequest))
    {
        HttpContext.Current.Session["hideOldVer"] = hideOldVer = hideOldVerRequest;
    }
    else if (hideOldVerSession != null)
    {
        hideOldVer = hideOldVerSession.ToString();
    }


            
            #line default
            #line hidden
WriteLiteral("<div id=\"formContainer\" style=\"overflow: auto;\" class=\"ui-widget\">\r\n");


            
            #line 29 "..\..\Views\Juridical\Index.cshtml"
       Html.EnableClientValidation(); 

            
            #line default
            #line hidden

            
            #line 30 "..\..\Views\Juridical\Index.cshtml"
     using (Html.BeginForm("CreateNewJuridical", "Person", FormMethod.Post, new { id = "CreateNewJuridical", name = "NewJuridicalForm", onsubmit = "return false;" }))
    {
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Juridical\Index.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Juridical\Index.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral(@"        <table cellspacing=""0"" border=""0"" style=""width: 99%"" cellpadding=""4"">
            <tr>
                <td rowspan=""30"">
                    &nbsp;&nbsp;
                </td>
                <td>
                    <input style=""visibility: hidden; width: 1px; height: 1px"" type=""submit"" id=""SubmitButton"" />
                </td>
            </tr>
            ");



WriteLiteral("\r\n            <tr>\r\n                <td>\r\n                    <table style=\"width" +
": 100%\">\r\n                        <tr>\r\n                            <td width=\"1" +
"00px\">");


            
            #line 47 "..\..\Views\Juridical\Index.cshtml"
                                         Write(Html.LabelFor(m => m.Model.Card.Nickname));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 50 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.Nickname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");


            
            #line 51 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.Nickname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n            </tr>\r\n            ");



WriteLiteral("\r\n            <tr>\r\n                <td align=\"right\">\r\n                    <tabl" +
"e>\r\n                        <tr>\r\n                            <td align=\"right\">" +
"");


            
            #line 62 "..\..\Views\Juridical\Index.cshtml"
                                         Write(Html.LabelFor(m => m.Model.Card.TerritoryID, new { @for = "Model_Card_TerritoryID___Autocomplete" }));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td style=\"widt" +
"h: 350px;\">");


            
            #line 64 "..\..\Views\Juridical\Index.cshtml"
                                                 Write(Html.EditorFor(m => m.Model.Card.TerritoryID));

            
            #line default
            #line hidden
WriteLiteral(@"
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td>
                                <span  class=""field-validation-error""><span id=""territotyIDValidationMessage""  style=""display: none"">");


            
            #line 71 "..\..\Views\Juridical\Index.cshtml"
                                                                                                                                 Write(Kesco.Persons.Web.Localization.Resources.Models_JuridicalPersonCard_TerritoryID_Required);

            
            #line default
            #line hidden
WriteLiteral("</span></span>\r\n                            </td>\r\n                        </tr>\r" +
"\n                    </table>\r\n                </td>\r\n            </tr>\r\n       " +
"     ");



WriteLiteral("\r\n            <tr>\r\n                <td align=\"right\" style=\"border-bottom: 1px s" +
"olid;\">\r\n                    <table>\r\n                        <tr>\r\n            " +
"                <td align=\"right\">\r\n                                ");


            
            #line 83 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.IsStateOrganization));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>");


            
            #line 85 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.IsStateOrganization));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n            </tr>\r\n            ");



WriteLiteral("\r\n            <tr>\r\n                <td id=\"OGRNFields\" style=\"border-bottom: 1px" +
" solid;\">\r\n                    <table>\r\n                        <tr>\r\n          " +
"                  <td width=\"100px\">\r\n                                ");


            
            #line 97 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.OGRN, new Dictionary<string, object> {
							 { "data-bind", "text: FormatRegistration.OGRNName" }
							}));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 102 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.OGRN, new { width = 150 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                              ");



WriteLiteral("\r\n                                ");


            
            #line 105 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.OGRN));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"           <tr data-bind=\"visible: FormatRegistration.INNName\">\r\n               " +
"             <td>\r\n                                ");


            
            #line 110 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.INN, new Dictionary<string, object> {
							 { "data-bind", "text: FormatRegistration.INNName" }
						}));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 115 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.INN, new { width = 110 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                (");


            
            #line 116 "..\..\Views\Juridical\Index.cshtml"
                             Write(Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Length);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span data-bind=\"text: FormatRegistration.INNLe" +
"ngth1\"></span>)\r\n                                ");


            
            #line 118 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.INN));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"           <tr data-bind=\"visible: FormatRegistration.OKPOName\">\r\n              " +
"              <td>\r\n                                ");


            
            #line 123 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.OKPO, new Dictionary<string, object> {
							 { "data-bind", "text: FormatRegistration.OKPOName" }
						}));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 128 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.OKPO, new { width = 110 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                (");


            
            #line 129 "..\..\Views\Juridical\Index.cshtml"
                             Write(Kesco.Persons.Web.Localization.Resources.Views_JuridicalPerson_Length);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span data-bind=\"text: FormatRegistration.OKPOL" +
"ength1\"></span>)\r\n                                ");


            
            #line 131 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.OKPO));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n            </tr>\r\n            ");



WriteLiteral(@"
            <tr data-bind=""visible: HasRolesForBusinessProjects().length > 0"">
                <td style=""border-bottom: 1px solid;"">
                    <table width=""100%"">
                        <tr>
                            <td width=""100px"">
                                ");


            
            #line 143 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.BusinessProjectID, new { @for = "Model_Card_BusinessProjectID___Autocomplete" }));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 146 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.BusinessProjectID));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n            </tr>\r\n            ");



WriteLiteral(@"
            <tr data-bind=""ifnot: HidePersonTypesSection"">
                <td style=""border-bottom: 1px outset;"">
                    <table cellpadding=""0"" cellspacing=""0"">
                        <tr>
                            <td valign=""top"" width=""100px"">
                                <span class=""ui-icon ui-icon-contact text-ui-icon""></span>
                                ");


            
            #line 159 "..\..\Views\Juridical\Index.cshtml"
                            Write(global::Resources.Resources.Kesco_Persons_Web_VW_146);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n          " +
"                      ");


            
            #line 162 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.DisplayFor(m => m.Model.Card.Requisites, "Requisites"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n            </tr>\r\n            ");



WriteLiteral("\r\n            <tr>\r\n                <td style=\"border-bottom: 1px outset;\">\r\n    " +
"                <table>\r\n                        <tr>\r\n                         " +
"   <td>\r\n                                ");


            
            #line 174 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.IsBank));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>");


            
            #line 176 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.IsBank));

            
            #line default
            #line hidden
WriteLiteral(@"
                            </td>
                        </tr>
                    </table>
                    <table border=""0"" cellpadding=""2"" cellspacing=""1"" data-bind=""visible: Model.Card.IsBank"">
                        <tr>
                            <td width=""100px"">
                                ");


            
            #line 183 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.BIK));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td style=\"widt" +
"h: 160px;\">\r\n                                ");


            
            #line 186 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.BIK));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");


            
            #line 187 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.BIK));

            
            #line default
            #line hidden
WriteLiteral(@"
                            </td>
                            <td>
                                <a href=""javascript: void(0);"" onclick=""addBanks(ViewModel.Model.Card.BIK());"">
                                    <img style=""cursor: pointer; border: 0px;"" src=""");


            
            #line 191 "..\..\Views\Juridical\Index.cshtml"
                                                                               Write(Url.Content(Kesco.Persons.Web.Configuration.AppSettings.URI_Styles));

            
            #line default
            #line hidden
WriteLiteral("store.gif\" \r\n\t\t\t\t\t\t\t/></a>\r\n                            </td>\r\n                  " +
"          <td>\r\n                                &nbsp;\r\n                        " +
"    </td>\r\n                            <td>\r\n                                ");


            
            #line 198 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.LoroConto));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td style=\"widt" +
"h: 160px;\">\r\n                                ");


            
            #line 201 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.LoroConto));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");


            
            #line 202 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.LoroConto));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"           <tr>\r\n                            <td>\r\n                             " +
"   ");


            
            #line 207 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.SWIFT));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 210 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.SWIFT));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");


            
            #line 211 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.SWIFT));

            
            #line default
            #line hidden
WriteLiteral(@"
                            </td>
                            <td>
                                &nbsp;
                            </td>
                            <td>
                                &nbsp;
                            </td>
                            <td>
                                ");


            
            #line 220 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.BIKRKC));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 223 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.BIKRKC));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");


            
            #line 224 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.ValidationMessageFor(m => m.Model.Card.BIKRKC));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n            </tr>\r\n            ");



WriteLiteral("\r\n            <tr data-bind=\"ifnot: HidePersonTypesSection\">\r\n                <td" +
" style=\"border-bottom: 1px outset;\">\r\n                    <table>\r\n             " +
"           <tr>\r\n                            <td>\r\n                             " +
"   ");



WriteLiteral("\r\n                                <!-- | <a href=\"javascript: void(0)\" data-bind=" +
"\"\r\n\t\t\t\t\t\t\t\tclick: openChooseEmployeesDialog\r\n\t\t\t\t\t\t\t\" title=\"");


            
            #line 239 "..\..\Views\Juridical\Index.cshtml"
            Write(global::Resources.Resources.Kesco_Persons_Web_VW_1002);

            
            #line default
            #line hidden
WriteLiteral("\"><span class=\"ui-icon ui-icon-plus text-ui-icon\">&nbsp;</span>");


            
            #line 239 "..\..\Views\Juridical\Index.cshtml"
                                                                                                                                   Write(global::Resources.Resources.Kesco_Persons_Web_VW_1002);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t\t\t\t//-->\r\n                                                <!-- Если секр" +
"етарь или администратор лиц -->\r\n");


            
            #line 242 "..\..\Views\Juridical\Index.cshtml"
             	                    if (accessLevel.Contains("11") || accessLevel.Contains("12"))
                                    {
				                    
            
            #line default
            #line hidden
            
            #line 244 "..\..\Views\Juridical\Index.cshtml"
                   Write(Html.Raw(String.Format(@"<a href='javascript: void(0);' onclick=""window.ViewModel.ChooseEmpls(getResponsibleIds());"">{0}</a>", global::Resources.Resources.Kesco_Persons_Web_VW_126)));

            
            #line default
            #line hidden
            
            #line 244 "..\..\Views\Juridical\Index.cshtml"
                                                                                                                                                                                                                ;
				                    } else {
            

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t                    <span class=\"ui-icon ui-icon-person text-ui-icon\">&nbsp;\r" +
"\n\t\t\t\t                    </span>");


            
            #line 248 "..\..\Views\Juridical\Index.cshtml"
                               
            
            #line default
            #line hidden
            
            #line 248 "..\..\Views\Juridical\Index.cshtml"
                           Write(global::Resources.Resources.Kesco_Persons_Web_VW_126);

            
            #line default
            #line hidden
            
            #line 248 "..\..\Views\Juridical\Index.cshtml"
                                                                                      
                                    }

            
            #line default
            #line hidden
WriteLiteral(@"                            </td>
                        </tr>
                    </table>
                    <table>
                        <tr>
                            <td style=""width: 100px;"">
                                &nbsp;
                            </td>
                            <td>
                               						<table cellpadding=""0"" cellpadding=""0"">
							<tbody data-bind=""foreach: Model.ResponsibleEmployees"">
								<tr>
									<td>
                                        <!--   visible: ($data.ID()) != ViewModel.Model.CurrentEmployeeID(), -->
");


            
            #line 264 "..\..\Views\Juridical\Index.cshtml"
                                          if (accessLevel.Contains("11") || accessLevel.Contains("12"))
                                         {

            
            #line default
            #line hidden
WriteLiteral("                                             <a href=\"javascript: void(0);\" data-" +
"bind=\"\r\n\t\t\t\t\t\t\t\t\t\t\t\tclick: $root.removeResponsibleEmployee\r\n\t\t\t\t\t\t\t\t\t\t\t\" title=\"" +
"");


            
            #line 268 "..\..\Views\Juridical\Index.cshtml"
                Write(global::Resources.Resources.Kesco_Persons_Web_VW_1001);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                                 ><span class=\"ui-icon ui-icon" +
"-minus text-ui-icon\">&nbsp;</span></a>\r\n");


            
            #line 270 "..\..\Views\Juridical\Index.cshtml"
                                         }

            
            #line default
            #line hidden
WriteLiteral(@"										<a class=""employeeControl"" title=""$data.FullName()"" href=""javascript: void(0)""
											data-bind=""
												attr: { 
													id: $data.ID(), 
													'data-employee-id': $data.ID(), 
													alt: $data.FullName(), 
													title: $data.FullName()
												},
												click: function() { ViewModel.showUser($data.ID()); },
												dynamicLink: { 
													value: $data.ID(), 
													source: '");


            
            #line 282 "..\..\Views\Juridical\Index.cshtml"
                  Write(Url.Action("GetItem", "EmployeeSelect"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n\t\t\t\t\t\t\t\t\t\t\t\t\ttooltipSource: \'");


            
            #line 283 "..\..\Views\Juridical\Index.cshtml"
                         Write(Configuration.AppSettings.URI_user_info);

            
            #line default
            #line hidden
WriteLiteral(@"'
												}
										""></a>
									</td>
								</tr>
							</tbody>
							<tbody data-bind=""visible: Model.ResponsibleEmployees().length == 0"">
								<td>
                                    <span id=""responsibleValidationMessage"">
                                        <label style=""COLOR: #ff0000; font-weight:100;  font-size: 10px;"">");


            
            #line 292 "..\..\Views\Juridical\Index.cshtml"
                                                                                                      Write(Kesco.Persons.Web.Localization.Resources.Views_NaturalPerson_Validation_Responsible);

            
            #line default
            #line hidden
WriteLiteral(@"</label> 
                                    </span>
                                   
                                </td>
							</tbody>
						</table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
                        <tr data-bind=""ifnot: HidePersonTypesSection"">
                <td>
                    <table width=""100%"">
                        <tr valign=""top"">
                            <td width=""100px"">
                                <span class=""ui-icon ui-icon-script text-ui-icon"">&nbsp;</span> ");


            
            #line 308 "..\..\Views\Juridical\Index.cshtml"
                                                                                            Write(global::Resources.Resources.Kesco_Persons_Web_VW_138);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n\t         " +
"                   ");


            
            #line 311 "..\..\Views\Juridical\Index.cshtml"
                        Write(Html.EditorFor(m => m.Model.PersonTypes));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span  class=\"field-validation-error\"><span id=" +
"\"personTypesValidationMessage\"  style=\"display: none\">");


            
            #line 312 "..\..\Views\Juridical\Index.cshtml"
                                                                                                                                 Write(global::Resources.Resources.Kesco_Persons_CreateJuridical_2202);

            
            #line default
            #line hidden
WriteLiteral(@"</span></span>
                        
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <!-- Комментарии -->
                <td style=""border-top: 1px outset;"">
                    <table width=""100%"">
                        <tr valign=""top"">
                            <td width=""100px"">
                                ");


            
            #line 325 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.LabelFor(m => m.Model.Card.Comment));

            
            #line default
            #line hidden
WriteLiteral(":\r\n                            </td>\r\n                            <td>\r\n         " +
"                       ");


            
            #line 328 "..\..\Views\Juridical\Index.cshtml"
                           Write(Html.EditorFor(m => m.Model.Card.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n            </tr>\r\n\r\n        </table>\r\n");


            
            #line 336 "..\..\Views\Juridical\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");



WriteLiteral("\r\n");


            
            #line 339 "..\..\Views\Juridical\Index.cshtml"
  
    Html.RegisterScript(@"
		;(function(scope, $) {{
			// поиск страна регистрации 
			scope.ViewModel.Model.Card.TerritoryID.__SearchParameters.HowSearch(1); // начинается с
			scope.ViewModel.Model.Card.TerritoryID.__SearchParameters.AreaIDs.push(2); // является страной

			// поиск бизнес-проекта 
			scope.ViewModel.Model.Card.BusinessProjectID.__SearchParameters.HowSearch(1); // начинается с

		}})(window, jQuery);
		
	");


            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral(@"
    <div id=""toolBar"" class=""ui-widget-header ui-corner-all kui-toolbar"" style=""padding: 2px;""
        data-bind=""visible: PageLoaded"">
        <table cellspacing=""0"" cellpadding=""0"" border=""0"" style=""margin-top: -2px;"" width=""100%"">
            <tr valign=""middle"">
                <td>
                    &nbsp;
                    <button type=""button"" data-bind="" 
						click: function() { ViewModel.Model.Confirmed(false); SubmitForm(); },
						jqueryui: { widget: 'button', options: { icons: { primary: 'ui-icon-disk' } } }
					"">");


            
            #line 363 "..\..\Views\Juridical\Index.cshtml"
   Write(global::Resources.Resources.GUI_Button_Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    <button type=\"button\" data-bind=\" \r\n\t\t\t\t\t\tclick: c" +
"loseDialog, \r\n\t\t\t\t\t\tjqueryui: { widget: \'button\', options: { icons: { primary: \'" +
"ui-icon-cancel\' } } }\r\n\t\t\t\t\t\">");


            
            #line 367 "..\..\Views\Juridical\Index.cshtml"
   Write(global::Resources.Resources.GUI_Button_Cancel);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                </td>
                <td nowrap=""nowrap"" style=""width: 30px;"">
                    <button type=""button"" style="""" data-bind=""jqueryui: { widget: 'button', options: { text: false, icons: { primary: 'ui-icon-help' }}}, click: showHelp"">");


            
            #line 370 "..\..\Views\Juridical\Index.cshtml"
                                                                                                                                                                       Write(Kesco.Web.Mvc.UI.Controls.Localization.Resources.GUI_Menu_Help);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </td>\r\n\r\n            </tr>\r\n        </table>\r\n    </di" +
"v>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Footer", () => {

WriteLiteral("\r\n\r\n\r\n\r\n\r\n    ");


            
            #line 382 "..\..\Views\Juridical\Index.cshtml"
Write(Html.CommonScriptCode("Juridical_Footer",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden

WriteLiteralTo(@__razor_template_writer, "<script>\r\n");


            
            #line 384 "..\..\Views\Juridical\Index.cshtml"
  
    bool isMvc = (Request["clr"] ?? "0") == "0";


            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\r\n\r\n$(window).load(function() { ViewModel.Model.PersonTypes.PersonTypeIDs.subscri" +
"be(function(newValue) { checkTypesValid(); }) });\r\n\tfunction returnResult(result" +
") {\r\n\r\n");


            
            #line 392 "..\..\Views\Juridical\Index.cshtml"
 		if (isMvc)
  { 

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\t\t\t");

WriteLiteralTo(@__razor_template_writer, " var arr = []; arr.push(result);\r\n");



WriteLiteralTo(@__razor_template_writer, "\t\t\t");

WriteLiteralTo(@__razor_template_writer, " closeDialogAndReturnValue(JSON.stringify(arr));\r\n");


            
            #line 396 "..\..\Views\Juridical\Index.cshtml"
		}
  else
  {

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\t\t\t");

WriteLiteralTo(@__razor_template_writer, " var retVal = result.value + String.fromCharCode(31) + result.label;\r\n");



WriteLiteralTo(@__razor_template_writer, "\t\t\t");

WriteLiteralTo(@__razor_template_writer, " DialogPageReturn(retVal, 0);\r\n");


            
            #line 401 "..\..\Views\Juridical\Index.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\t}\r\n\r\n\tfunction addBanks(search) {\r\n\t\tvar callbackUrl = encodeURIComponent(\'");


            
            #line 405 "..\..\Views\Juridical\Index.cshtml"
       WriteTo(@__razor_template_writer, Url.FullPathAction("DialogResult", "Default"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\');\r\n\r\n\t\tif (!search) {\r\n\t\t\tvar url = \'");


            
            #line 408 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, Kesco.Persons.Web.Configuration.AppSettings.URI_bank_search);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "?return=1&mvc=1&callbackKey=c1&callbackUrl={0}\';\r\n\t\t\turl = $.validator.format(url" +
", callbackUrl);\r\n\t\t} else {\r\n\t\t\tvar url = \'");


            
            #line 411 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, Kesco.Persons.Web.Configuration.AppSettings.URI_bank_search);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "?return=1&mvc=1&callbackKey=c1&callbackUrl={0}&search={1}\';\r\n\t\t\turl = $.validator" +
".format(url, callbackUrl, encodeURIComponent(search));\r\n\t\t}\r\n\r\n\r\n\t\twindow.openPo" +
"pupWindow(url, {\r\n\t\t\t\tcallbackUrl: \'");


            
            #line 417 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, Url.FullPathAction("DialogResult", "Default"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\'\r\n\t\t\t}, \r\n\t\t\tfunction (val) {\r\n\t\t\t\tif (val) {\r\n\t\t\t\t\twindow.ViewModel.Model.Card." +
"BIK(val[0].bik);\r\n\t\t\t\t\twindow.ViewModel.Model.Card.LoroConto(val[0].korschet);\r\n" +
"\t\t\t\t}\r\n\t\t\t}, \"test\", 800, 600);\r\n\t}\r\n\r\n\tfunction checkTypesValid() {\r\n\t    var v" +
"alidationMsg = document.getElementById(\'personTypesValidationMessage\');\r\n\t    if" +
"(ViewModel.Model.PersonTypes.PersonTypeIDs() == null || ViewModel.Model.PersonTy" +
"pes.PersonTypeIDs() == \"\") {\r\n            if (validationMsg != null && validatio" +
"nMsg != \"\") validationMsg.style.display = \"table\";\r\n        }\r\n\t    else {\r\n    " +
"         if (validationMsg != null && validationMsg != \"\") validationMsg.style.d" +
"isplay = \"none\";\r\n        }   \r\n\t}\r\n\tfunction checkTerritoryValid() {\r\n\t    if(V" +
"iewModel.Model.Card.TerritoryID() == null || ViewModel.Model.Card.TerritoryID() " +
"== \"\") {\r\n\t        territotyIDValidationMessage.style.display = \"table\";\r\n      " +
"  }\r\n\t    else {\r\n\t        territotyIDValidationMessage.style.display = \"none\";\r" +
"\n        }\r\n\t}\r\n    function checkRequisitesValid() {\r\n\t    if((ViewModel.Model." +
"Card.Requisites.ShortNameLat() == null || ViewModel.Model.Card.Requisites.ShortN" +
"ameLat() == \"\") && (ViewModel.Model.Card.Requisites.ShortNameRus() == null || Vi" +
"ewModel.Model.Card.Requisites.ShortNameRus() == \"\")) {\r\n\t        setRequisitesVa" +
"lid(false);\r\n        }\r\n\t    else {\r\n\t       setRequisitesValid(true);\r\n        " +
"}\r\n\t}\r\n    \r\n    function checkBunkFrom() {\r\n       if((document.getElementById(" +
"\'Model_Card_BIK\').value == null || document.getElementById(\'Model_Card_BIK\').val" +
"ue == \"\") && (document.getElementById(\'Model_Card_SWIFT\').value == null || docum" +
"ent.getElementById(\'Model_Card_SWIFT\').value == \"\"))\r\n            {\r\n           " +
" ViewModel.Model.Card.LoroConto(\"\");\r\n            ViewModel.Model.Card.BIKRKC(\"\"" +
");\r\n            }\r\n        if(ViewModel.Model.Card.IsBank() == false) {\r\n       " +
"      ViewModel.Model.Card.LoroConto(\"\");\r\n            ViewModel.Model.Card.BIKR" +
"KC(\"\");\r\n             ViewModel.Model.Card.BIK(\"\");\r\n            ViewModel.Model" +
".Card.SWIFT(\"\");\r\n        }\r\n        \r\n    }\r\n\r\n        function getResponsibleI" +
"ds() {\r\n        var employeeControlIds = \'\';\r\n\t    for (var i = 0; i < $(\'.emplo" +
"yeeControl\').length; i++) {{\r\n\t            if(i == ($(\'.employeeControl\').length" +
" - 1))\r\n\t\t                {{ employeeControlIds+= $(\'.employeeControl\')[i].id; }" +
"} \r\n  \t            else {{employeeControlIds+= $(\'.employeeControl\')[i].id; empl" +
"oyeeControlIds+= \',\'; }}  \r\n            }}\r\n\r\n        return employeeControlIds;" +
"\r\n    }\r\n\r\n    function SubmitForm() {\r\n        checkBunkFrom();\r\n\r\n\t\tvar $form " +
"= $(\"#CreateNewJuridical\");\r\n\r\n\t\tif ($form.valid()) {\r\n\t\t\twindow.ViewModel.save(" +
");\r\n\t\t}\r\n\t    if(ViewModel.Model.Card.PersonID() == null || ViewModel.Model.Card" +
".PersonID() == \"\") {\r\n\t            checkTypesValid();\r\n\t            checkTerrito" +
"ryValid();\r\n\t            checkRequisitesValid();\r\n\t    }\r\n\t  \r\n\t    return false" +
";\r\n\t}\r\n\r\n\r\n    \r\n    function setCountryFildEmpty() {\r\n             var countryF" +
"ield = document.getElementById(\'Model_Card_TerritoryID___Autocomplete\');\r\n      " +
"      if(countryField == null) return;\r\n                countryField.onfocusout " +
"= function() {\r\n                    if(countryField.value == null || countryFiel" +
"d.value == \"\") {\r\n                        ViewModel.Model.Card.TerritoryID(\'\');\r" +
"\n                    }\r\n                };\r\n        }\r\n    \r\n    function setBui" +
"ssnesFieldEmpty() {\r\n             var buissnessField = document.getElementById(\'" +
"Model_Card_BusinessProjectID___Autocomplete\');\r\n            if(buissnessField ==" +
" null) return;\r\n                buissnessField.onfocusout = function() {\r\n      " +
"              if(buissnessField.value == null || buissnessField.value == \"\") {\r\n" +
"                        ViewModel.Model.Card.BusinessProjectID(\'\');\r\n           " +
"         }\r\n                };\r\n        }\r\n\r\n\r\n    $(document).ready(function ()" +
" {\r\n\t    ");



WriteLiteralTo(@__razor_template_writer, "\r\n       \r\n       //$(\'#Model_Card_OGRN\').mask(\'option\').mask.length\r\n\r\n\t\t");



WriteLiteralTo(@__razor_template_writer, "\r\n\t\tViewModel.ControlNameToFocus=\'#Model_Card_Nickname\';\r\n\r\n\t\tViewModel.prevVersi" +
"onUrl = function() {\r\n\t\t\tvar url = \"");


            
            #line 528 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, Kesco.Persons.Web.Configuration.AppSettings.URI_person_search_old);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\";\r\n\t\t\tvar value = url.substring(0, url.lastIndexOf(\'/\') + 1);\r\n");


            
            #line 530 "..\..\Views\Juridical\Index.cshtml"
 			if (Model.Model.Card.PersonID != null)
   {

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\t\t\t");

WriteLiteralTo(@__razor_template_writer, " value += \"Form/Edit/client.aspx?idClient=");


            
            #line 532 "..\..\Views\Juridical\Index.cshtml"
               WriteTo(@__razor_template_writer, Model.Model.Card.PersonID);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\";\r\n");


            
            #line 533 "..\..\Views\Juridical\Index.cshtml"
			}
   else
   {

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\t\t\t");

WriteLiteralTo(@__razor_template_writer, " value += \"Form/Edit/clientAdd.aspx?clr=1\";\r\n");


            
            #line 537 "..\..\Views\Juridical\Index.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\t\t     setCountryFildEmpty();\r\n\t\t    setBuissnesFieldEmpty();\r\n\t\t\treturn value;\r\n" +
"\t\t    \r\n\r\n\t\t}\r\n\r\n        \t    window.ViewModel.ChooseEmpls = function (responsib" +
"leIDs) {\r\n\t\t\t$.ajax({\r\n\t\t\t\turl: \'");


            
            #line 547 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, Url.Action("Dispatch"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"',
				type: 'POST',
				data: window.ko.toJSON({
					command: 'chooseempls',
					control: responsibleIDs,
					model:  window.ko.mapping.toJS(window.ViewModel.Model)
				}),
				contentType: ""application/json; charset=utf-8""
			});
		};

		window.ViewModel.save = function () {
			$.ajax({
				url: '");


            
            #line 560 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, Url.Action("Dispatch"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"',
				type: 'POST',
				data: window.ko.toJSON({
					command: 'save',
					control: null,
					model:  window.ko.mapping.toJS(window.ViewModel.Model)
				}),
				contentType: ""application/json; charset=utf-8""
			});
		};

		window.ViewModel.Model.Card.TerritoryID.subscribe(function (newTerritoryID) {
			window.ViewModel.Model.Card.Requisites.TerritoryID(newTerritoryID);
		    checkTerritoryValid();
		});

		ViewModel.removeResponsibleEmployee = function() {
				ViewModel.Model.ResponsibleEmployees.remove(this);
		};


		// TODO: Make universary
		ViewModel.openChooseEmployeesDialog = function() {
			var selected = [];
			var list = ko.mapping.toJS(ViewModel.Model.ResponsibleEmployees());
			for(var i=0; i<list.length; i++) {
				selected[i] = list[i].ID.toString();
			}
			selected = selected.join("","");
			var callbackUrl = encodeURIComponent('");


            
            #line 589 "..\..\Views\Juridical\Index.cshtml"
         WriteTo(@__razor_template_writer, Url.FullPathAction("DialogResult", "Default"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\');\r\n\t\t\tvar title = encodeURIComponent(\'");


            
            #line 590 "..\..\Views\Juridical\Index.cshtml"
   WriteTo(@__razor_template_writer, global::Resources.Resources.Kesco_Persons_Web_VW_1000);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\');\r\n\t\t\tvar url;\r\n\t\t\turl = \'");


            
            #line 592 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, Html.Raw(Configuration.AppSettings.URI_user_search));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "?");


            
            #line 592 "..\..\Views\Juridical\Index.cshtml"
                                 WriteTo(@__razor_template_writer, Html.Raw(Configuration.URI_user_search_QS ?? "t=1"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"&selectedid='+selected;
			url = $.validator.format(url, callbackUrl, title);

			openPopupWindow(url, null, function(result) {
				if ($.isArray(result)) {
					ViewModel.Model.ResponsibleEmployees.removeAll();
					for(var i=0; i<result.length; i++)
						ViewModel.Model.ResponsibleEmployees.push({ID: ko.observable(result[i].ID), FullName: ko.observable(result[i].Name) });
				}
			}, ""wnd_ChooseEmployees"", 800, 600);
		};

");


            
            #line 604 "..\..\Views\Juridical\Index.cshtml"
  
    ModelMetadata pmm = ViewData.ModelMetadata
        .Properties.First(p => p.PropertyName == "Model")
        .Properties.First(p => p.PropertyName == "Card");


            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\r\n\t\t$(\'#");


            
            #line 610 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\').mask();\r\n\t\t$(\'#");


            
            #line 611 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\').mask();\r\n\t\t$(\'#");


            
            #line 612 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"').mask();

//		var updateRegistrationFormat = function (tid) {
//			function repeat(symbol, length) {
//				var s="""", len = 0+length;
//				for (var i = 0; i < len; i++) s += symbol;
//				return s;
//			}
//			var result = window.ViewModel.FormatRegistrations.filterByProperty(""ID"", tid || 0);
//			var registrationFormat = window.ViewModel.FormatRegistration;
//			if (result().length > 0) {
//			    format = result()[0];
//                registrationFormat.OGRNLength1(format.OGRNLength1());
//			    registrationFormat.OGRNFormat1(format.OGRNFormat1());
//				registrationFormat.OGRNName(format.OGRNName());
//				registrationFormat.INNName(format.INNName());
//				registrationFormat.INNLength1(format.INNLength1());
//				registrationFormat.OKPOName(format.OKPOName());
//				registrationFormat.OKPOLength1(format.OKPOLength1());
//			    
//			} else {
//				registrationFormat.OGRNName('");


            
            #line 633 "..\..\Views\Juridical\Index.cshtml"
   WriteTo(@__razor_template_writer, pmm.Properties.First(p => p.PropertyName == "OGRN").GetDisplayName());

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"');
//				registrationFormat.INNName("""");
//				//registrationFormat.INNLength1(20);
//				registrationFormat.OGRNFormat1(""####################"");
//			    registrationFormat.OGRNLength1(20);
//				registrationFormat.OKPOName("""");
//				//registrationFormat.OKPOLength1(20);
//			}

//			try {
//				var multiplicator = 8;
//				var len = 0;
//			    var baseMask;
//                
//                len = registrationFormat.OGRNLength1();
//                baseMask = registrationFormat.OGRNFormat1();

//				$('#");


            
            #line 650 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"')
//					.mask(""option"", { mask: baseMask })
//					.width(len*multiplicator).parent().width(len*multiplicator);
//                    
//                    if(len == 0) {
//                      document.getElementById(""OGRNFields"").style.display = ""none"";
//                       
//                    }
//			        else {
//                         document.getElementById(""OGRNFields"").style.display = """";
//                    }
//                     document.getElementById('OGRNlenghtField').innerText = len;
//				len = registrationFormat.INNLength1()?registrationFormat.INNLength1():12;
//				$('#");


            
            #line 663 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\')\r\n//\t\t\t\t\t.mask(\"option\", { mask: repeat(\"9\", len) })\r\n//\t\t\t\t\t.width(len*multipl" +
"icator).parent().width(len*multiplicator);\r\n\r\n//\t\t\t\tlen = registrationFormat.OKP" +
"OLength1()?registrationFormat.OKPOLength1():10;\r\n//\t\t\t\t$(\'#");


            
            #line 668 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"')
//					.mask(""option"", { mask: repeat(""9"", len) })
//					.width(len*multiplicator).parent().width(len*multiplicator);
//			} catch(e) { 
//				if (window.console) console.log(e);
//			}
//		};
        var updateRegistrationFormat = function (tid) {
			function repeat(symbol, length) {
				var s="""", len = 0+length;
				for (var i = 0; i < len; i++) s += symbol;
				return s;
			}
			var result = window.ViewModel.FormatRegistrations.filterByProperty(""ID"", tid || 0);
			var registrationFormat = window.ViewModel.FormatRegistration;
			if (result().length > 0) {
				format = result()[0];
				registrationFormat.OGRNFormat(format.OGRNFormat());
				registrationFormat.OGRNName(format.OGRNName());
				registrationFormat.INNName(format.INNName());
				registrationFormat.INNLength1(format.INNLength1());
				registrationFormat.OKPOName(format.OKPOName());
				registrationFormat.OKPOLength1(format.OKPOLength1());
			} else {
				registrationFormat.OGRNName('");


            
            #line 692 "..\..\Views\Juridical\Index.cshtml"
 WriteTo(@__razor_template_writer, pmm.Properties.First(p => p.PropertyName == "OGRN").GetDisplayName());

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"');
				registrationFormat.INNName("""");
				//registrationFormat.INNLength1(20);
				registrationFormat.OGRNFormat(""####################"");
				registrationFormat.OKPOName("""");
				//registrationFormat.OKPOLength1(20);
			}

			try {
				var multiplicator = 8;
				var len = registrationFormat.OGRNFormat().length;
				$('#");


            
            #line 703 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\')\r\n\t\t\t\t\t.mask(\"option\", { mask: registrationFormat.OGRNFormat() })\r\n\t\t\t\t\t.width(" +
"len*multiplicator).parent().width(len*multiplicator);\r\n\r\n\t\t\t\tlen = registrationF" +
"ormat.INNLength1()?registrationFormat.INNLength1():12;\r\n\t\t\t\t$(\'#");


            
            #line 708 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\')\r\n\t\t\t\t\t.mask(\"option\", { mask: repeat(\"9\", len) })\r\n\t\t\t\t\t.width(len*multiplicat" +
"or).parent().width(len*multiplicator);\r\n\r\n\t\t\t\tlen = registrationFormat.OKPOLengt" +
"h1()?registrationFormat.OKPOLength1():10;\r\n\t\t\t\t$(\'#");


            
            #line 713 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\')\r\n\t\t\t\t\t.mask(\"option\", { mask: repeat(\"9\", len) })\r\n\t\t\t\t\t.width(len*multiplicat" +
"or).parent().width(len*multiplicator);\r\n\t\t\t    \r\n                $(\'#");


            
            #line 717 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OGRN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\')[0].maxLength = 200;\r\n\t\t\t    $(\'#");


            
            #line 718 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_INN"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\')[0].maxLength = 200;\r\n\t\t\t    $(\'#");


            
            #line 719 "..\..\Views\Juridical\Index.cshtml"
WriteTo(@__razor_template_writer, ViewData.TemplateInfo.GetFullHtmlFieldId("Model_Card_OKPO"));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, @"')[0].maxLength = 200;
			} catch(e) { 
				if (window.console) console.log(e);
			}
		};

		updateRegistrationFormat(window.ViewModel.Model.Card.TerritoryID());

		window.ViewModel.Model.Card.TerritoryID.subscribe(updateRegistrationFormat);

		$(window).resize(function () {
			$(""#formContainer"").height($(""#dialogContentPane"").height());
			$(""#formContainer"").width($(""#dialogContentPane"").outerWidth());
		});

        function getURLParameter(name) {
            return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""""])[1].replace(/\+/g, '%20'))||null
        }

");


            
            #line 738 "..\..\Views\Juridical\Index.cshtml"
         if (!Model.Model.Card.ID.HasValue && Request["text"] != null && Request["text"] != "")
        {

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "        ");

WriteLiteralTo(@__razor_template_writer, "  var nickNameParametr = getURLParameter(\'text\').replace(/\\s+/gi, \" \");\r\n");



WriteLiteralTo(@__razor_template_writer, "\t\t");

WriteLiteralTo(@__razor_template_writer, "\tViewModel.Model.Card.Nickname(nickNameParametr)\r\n");


            
            #line 742 "..\..\Views\Juridical\Index.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\r\n\t});\r\n</script>");


            
            #line 745 "..\..\Views\Juridical\Index.cshtml"
       })));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 746 "..\..\Views\Juridical\Index.cshtml"
Write(Html.DisplayFor(m => m.Model.Card, "ChangedByInfo"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
