#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Dossier\Info.cshtml"
    using Kesco.Persons.Web.Models.Dossier;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Dossier\Info.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Dossier/Info.cshtml")]
    public partial class _Views_Dossier_Info_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Persons.Web.Models.Dossier.DossierSectionContext>
    {
        public _Views_Dossier_Info_cshtml()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\Dossier\Info.cshtml"
  
	var sectionID = Model.Section.ID.ToString();
	var items = Model.ViewModel.GetContextItems(cxti => cxti.TabID == Model.Section.ID);
	if (items.Count == 0) {
		Html.DossierClientSideScript_HideSection(Model.Section.ID);
		return;
	}
	var i = 0;


            
            #line default
            #line hidden

            
            #line 13 "..\..\Views\Dossier\Info.cshtml"
 foreach (var item in items) {

            
            #line default
            #line hidden
WriteLiteral("\t<tr class=\"dsl");


            
            #line 14 "..\..\Views\Dossier\Info.cshtml"
           Write(sectionID);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 15 "..\..\Views\Dossier\Info.cshtml"
 		if (i++ == 0) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<td colspan=\"2\" style=\"padding-left: 20px;\">\r\n\t\t\t");


            
            #line 17 "..\..\Views\Dossier\Info.cshtml"
Write(Html.Raw(HL(item.Label)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</td>\r\n");



WriteLiteral("\t\t<td class=\"changed\" rowspan=\"");


            
            #line 19 "..\..\Views\Dossier\Info.cshtml"
                           Write(items.Count);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t");


            
            #line 20 "..\..\Views\Dossier\Info.cshtml"
Write(Html.DisplayFor(m => item.ChangedBy, "EmployeeStatic", new {
				TooltipPositionMy = "middle right", TooltipPositionAt = "middle left",
				InitialLabel = HL(item.ChangedByFIO)
			}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t<span>");


            
            #line 24 "..\..\Views\Dossier\Info.cshtml"
     Write(item.ChangedDate);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t</td>\r\n");


            
            #line 26 "..\..\Views\Dossier\Info.cshtml"
		} else {
			if (!String.IsNullOrEmpty(item.Caption)){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<td nowrap=\"nowrap\" class=\"ui-label\" style=\"padding-left: 20px;\">");


            
            #line 28 "..\..\Views\Dossier\Info.cshtml"
                                                               Write(Html.Raw(Html.GetInfoLocalizedString(item.Caption, item.ID)));

            
            #line default
            #line hidden
WriteLiteral(":</td>\r\n");



WriteLiteral("\t\t\t<td style=\"width: 90%;\">&nbsp;");


            
            #line 29 "..\..\Views\Dossier\Info.cshtml"
                            Write(Html.Raw(HL(item.Label)));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");


            
            #line 30 "..\..\Views\Dossier\Info.cshtml"
			} else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<td colspan=\"2\" style=\"padding-left: 20px;\">");


            
            #line 31 "..\..\Views\Dossier\Info.cshtml"
                                          Write(Html.Raw(HL(Html.GetInfoLocalizedString(item.Label))));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");


            
            #line 32 "..\..\Views\Dossier\Info.cshtml"
			}
		}

            
            #line default
            #line hidden
WriteLiteral("\t</tr>\r\n");


            
            #line 35 "..\..\Views\Dossier\Info.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
