#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
    using Kesco.Persons.Web.Models.Dossier;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
    using Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Dossier/ResponsibleEmpls.cshtml")]
    public partial class _Views_Dossier_ResponsibleEmpls_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Persons.Web.Models.Dossier.DossierSectionContext>
    {
        public _Views_Dossier_ResponsibleEmpls_cshtml()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
  
	int personID = Model.ViewModel.Model.PersonID;
	int accessLevel = (int) Model.ViewModel.AccessLevel;
	var sectionID = Model.Section.ID.ToString();
	var currentAccess = Model.AccessGranted;
	var items = Model.ViewModel.GetContextItems(cxti => cxti.TabID == Model.Section.ID);


            
            #line default
            #line hidden

            
            #line 12 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
 if (items.Count == 0) {

            
            #line default
            #line hidden
WriteLiteral("<tr class=\"hoverable dsl");


            
            #line 13 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                    Write(sectionID);

            
            #line default
            #line hidden
WriteLiteral("\"><td colspan=\"4\">");


            
            #line 13 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                                                 Write(Resources.Persons_Dossier_NoData);

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n");


            
            #line 14 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
} else {
	var comparer = StringComparer.OrdinalIgnoreCase;
	items.Sort((x, y) => comparer.Compare(x.Label, y.Label));
	foreach (var item in items) { 

            
            #line default
            #line hidden
WriteLiteral("<tr class=\"hoverable dsl");


            
            #line 18 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                    Write(sectionID);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t<td colspan=\"2\">\r\n\t\t&nbsp;\r\n");


            
            #line 21 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
 		if (accessLevel >= 2 && currentAccess > 0) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<a id=\"Dossier_Responsible_Personal_");


            
            #line 22 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                                  Write(item.ID);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n\t\t\t\thref=\"javascript: void(0);\" \r\n\t\t\t\tclass=\"personality ");


            
            #line 24 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                   Write((item.Order == 0) ? "" : "ui-hover-visible");

            
            #line default
            #line hidden
WriteLiteral("\" \r\n\t\t\t\tdata-section-id=\"");


            
            #line 25 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                 Write(sectionID);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n\t\t\t\tdata-person-id=\"");


            
            #line 26 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                Write(personID);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n\t\t\t\tdata-employee-id=\"");


            
            #line 27 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                  Write(item.ID);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n\t\t\t\tdata-personality=\"");


            
            #line 28 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                  Write(item.Order);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n\t\t\t\ttitle=\"");


            
            #line 29 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
       Write(Resources.Dossier_PrivatePerson_SetRemoveSignPrivate);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n\t\t\t><span class=\"ui-icon ui-icon-flag text-ui-icon\" ></span></a>\r\n");


            
            #line 31 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
		} else {

            
            #line default
            #line hidden
WriteLiteral("\t\t<a id=\"Dossier_Responsible_Personal_");


            
            #line 32 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                                  Write(item.ID);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n\t\t\thref=\"javascript: void(0);\" class=\"");


            
            #line 33 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                                  Write((item.Order == 0) ? "" : "ui-hover-visible");

            
            #line default
            #line hidden
WriteLiteral("\"><span class=\"ui-icon ui-icon-flag text-ui-icon\" ></span></a>\r\n");


            
            #line 34 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t\t");


            
            #line 35 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
Write(Html.DisplayFor(m => item.ID, "EmployeeStatic", new {
			TooltipPositionMy = "middle left",
			TooltipPositionAt = "middle right",
			InitialLabel = HL(item.Label)
		}));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");


            
            #line 40 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
 		if (item.Order == 0) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<span class=\"clGray\" style=\"display: inline-block\">");


            
            #line 41 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
                                                 Write(Resources.Dossier_PrivatePerson_Label);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 42 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</td>\r\n\t<td class=\"changed\">\r\n\t\t");


            
            #line 45 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
Write(Html.DisplayFor(m => item.ChangedBy, "EmployeeStatic", new {
			TooltipPositionMy = "middle right",
			TooltipPositionAt = "middle left",
			InitialLabel = HL(item.ChangedByFIO)
		}));

            
            #line default
            #line hidden
WriteLiteral(" <span>");


            
            #line 49 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
       Write(item.ChangedDate);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t</td>\r\n</tr>\r\n");


            
            #line 52 "..\..\Views\Dossier\ResponsibleEmpls.cshtml"
	}
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
