#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\Card\Index.cshtml"
    using Kesco.Persons.Web;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Card\Index.cshtml"
    using Kesco.Persons.Web.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Card\Index.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Card\Index.cshtml"
    using Kesco.Web.Mvc.UI;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Card\Index.cshtml"
    using Kesco.Web.Mvc.UI.Controls;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Card\Index.cshtml"
    using Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Card/Index.cshtml")]
    public partial class _Views_Card_Index_cshtml : Kesco.Persons.Web.SiteViewPage<Kesco.Persons.Web.Models.Card.ViewModel>
    {
        public _Views_Card_Index_cshtml()
        {
        }
        public override void Execute()
        {








            
            #line 8 "..\..\Views\Card\Index.cshtml"
  
	Model
		.GetScriptCapabilities()
			.DisableGridScript()
			.DisableTreeScript();
	Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div id=\"dialogContentPaneContainer\" style=\"overflow: auto;\">\r\n");


            
            #line 17 "..\..\Views\Card\Index.cshtml"
Write(Html.CommonScriptCode("Card_Init",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden

WriteLiteralTo(@__razor_template_writer, "<script>\r\n\t\t");



WriteLiteralTo(@__razor_template_writer, @"
		(function(window, undefined) {
		})(this);

		$(document).ready(function () {

			$(window).resize(function () {
				$(""#dialogContentPaneContainer"").height($(""#dialogContentPane"").height());
				$(""#dialogContentPaneContainer"").width($(""#dialogContentPane"").width());
			});

		});
</script>");


            
            #line 31 "..\..\Views\Card\Index.cshtml"
       })));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 32 "..\..\Views\Card\Index.cshtml"
   Html.EnableClientValidation(); 

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 34 "..\..\Views\Card\Index.cshtml"
 using (Html.BeginForm("Check", "Card", FormMethod.Post, new { id = "PageForm", name = "PageForm", onsubmit = "return false;" }))
{
	
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Card\Index.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Card\Index.cshtml"
                              

	
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Card\Index.cshtml"
Write(Html.HiddenFor(m => m.Model.PersonID));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Card\Index.cshtml"
                                       


            
            #line default
            #line hidden
WriteLiteral("\t<table class=\"formTable\" cellspacing=\"0\" cellpadding=\"4\" border=\"0\" style=\"min-w" +
"idth: 400px;\">\r\n\t<tr>\r\n\t\t<td colspan=\"7\" align=\"center\">");


            
            #line 42 "..\..\Views\Card\Index.cshtml"
                             Write(Kesco.Persons.Web.Localization.Resources.Views_Card_PageMessage);

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t<br />&nbsp;</td>\r\n\t</tr>\r\n\t<tr valign=\"top\">\r\n\t\t<td style=\"padding-top: 4px" +
";\">\r\n\t\t\t<div class=\"editor-label\">\r\n\t\t\t\t");


            
            #line 48 "..\..\Views\Card\Index.cshtml"
Write(Html.LabelForEx(m => m.Model.From));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</div>\r\n\t\t</td>\r\n\t\t<td>&nbsp;</td>\r\n\t\t<td>\r\n\t\t\t<div class=\"editor-field\">\r\n" +
"\t\t\t\t");


            
            #line 54 "..\..\Views\Card\Index.cshtml"
Write(Html.EditorFor(m => m.Model.From));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t");


            
            #line 55 "..\..\Views\Card\Index.cshtml"
Write(Html.ValidationMessageFor(m => m.Model.From));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</div>\r\n\t\t</td>\r\n\t\t<td>&nbsp;</td>\r\n\t\t<td style=\"padding-top: 4px;\">\r\n\t\t\t<di" +
"v class=\"editor-label\">\r\n\t\t\t\t");


            
            #line 61 "..\..\Views\Card\Index.cshtml"
Write(Html.LabelForEx(m => m.Model.To));

            
            #line default
            #line hidden
WriteLiteral(":\r\n\t\t\t</div>\r\n\t\t</td>\r\n\t\t<td>&nbsp;</td>\r\n\t\t<td>\r\n\t\t\t<div class=\"editor-field\">\r\n" +
"\t\t\t\t");


            
            #line 67 "..\..\Views\Card\Index.cshtml"
Write(Html.EditorFor(m => m.Model.To));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t");


            
            #line 68 "..\..\Views\Card\Index.cshtml"
Write(Html.ValidationMessageFor(m => m.Model.To));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</div>\r\n\t\t</td>\r\n\t</tr>\r\n\t</table>\r\n");


            
            #line 73 "..\..\Views\Card\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n");


DefineSection("Header", () => {

WriteLiteral(@"
<div id=""toolBar"" class=""ui-widget-header ui-corner-all kui-toolbar"" style=""padding: 2px;"" data-bind=""visible: PageLoaded"">
	<table cellspacing=""0"" cellpadding=""0"" border=""0"" style=""margin-top: -2px;"" width=""100%"">
		<tr>
			<td>
				<button type=""button"" data-bind=""
						click: function() { setTimeout( function() { ViewModel.dispatchModelCommand('check'); }, 300); },
						jqueryui: { widget: 'button', options: { disabled: Processing() , icons: { primary: 'ui-icon-check' } } }
					"">");


            
            #line 85 "..\..\Views\Card\Index.cshtml"
   Write(Resources.GUI_Button_Create);

            
            #line default
            #line hidden
WriteLiteral("*</button>\r\n\t\t\t\t<button type=\"button\" data-bind=\"\r\n\t\t\t\t\t\tclick: closeDialog,\r\n\t\t\t" +
"\t\t\tjqueryui: { widget: \'button\', options: { disabled: Processing(), icons: { pri" +
"mary: \'ui-icon-cancel\' } } }\r\n\t\t\t\t\t\">");


            
            #line 89 "..\..\Views\Card\Index.cshtml"
  Write(Resources.GUI_Button_Cancel);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</table>\r\n</div>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Footer", () => {

WriteLiteral(" \r\n<div style=\"text-align:left;\">\r\n\t<sup>*</sup> - ");


            
            #line 98 "..\..\Views\Card\Index.cshtml"
            Write(Kesco.Persons.Web.Localization.Resources.Views_Card_PageMessageComment);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


});

WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
