#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kesco.Persons.Controls.Views.PersonSelectUsage
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\PersonSelectUsage\Index.cshtml"
    using Kesco;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\PersonSelectUsage\Index.cshtml"
    using Kesco.Persons.Controls;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\PersonSelectUsage\Index.cshtml"
    using Kesco.Persons.Controls.Models;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\PersonSelectUsage\Index.cshtml"
    using Kesco.Persons.Controls.Views;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PersonSelectUsage\Index.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PersonSelectUsage/Index.cshtml")]
    public class Index : Kesco.Persons.Controls.SiteViewPage<Kesco.Persons.Controls.Controllers.PersonSelectUsageController.ViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {






WriteLiteral("\t\t\t  \r\n");


            
            #line 8 "..\..\Views\PersonSelectUsage\Index.cshtml"
  
    ViewBag.Title = "Использование элемента управления 'Выбор лица'";
	Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("Header", () => {

WriteLiteral(" \r\n<h2>Пример использования PersonSelect</h2>\r\n");


});

WriteLiteral(@"

<div id=""container"" style=""overflow: auto;"">
<table width=""100%"">
<tr>
    <td>
        <span style=""float: left;"">
        <pre>
            // Модель данных
	        public class DataModel
	        {

			[Display(Name=""Поставщик"")]
			[PersonSelect(CLID = 62)]
			public int ShipperID { get; set; }

			[Display(Name = ""Клиент"")]
			[PersonSelect(CLID = 62)]
			public int ClientID { get; set; }

	        }
        </pre>
        </span>
        <span style=""float: left;"">
        <pre>
            // Модель представления
	        public class ViewModel : ViewModel&lt;DataModel&gt; { }
        </pre>
        </span>
        <span style=""float: left;"">
        <pre>
            ");


WriteLiteral("@* Форма редактирования *");


WriteLiteral("@\r\n            ");


WriteLiteral("@using (var form = Html.BeginForm())\r\n            {\r\n                ");


WriteLiteral("@Html.EditorForModel();\r\n            }\r\n        </pre>\r\n        </span>\r\n        " +
"<span style=\"float: left;\">\r\n        <pre>\r\n            ");


WriteLiteral("@* Просмотр *");


WriteLiteral("@\r\n            ");


WriteLiteral("@Html.EditorForModel();\r\n        </pre>\r\n        </span>\r\n        <span style=\"fl" +
"oat: left;\">\r\n        <pre>\r\n            ");


WriteLiteral("@* Состояние модели *");


WriteLiteral("@\r\n        </pre>\r\n        <pre data-bind=\"text: ko.toJSON(ko.mapping.toJS(ViewMo" +
"del.Model))\">\r\n            ");


WriteLiteral("@* Состояние модели *");


WriteLiteral("@\r\n        </pre>\r\n        </span>\r\n    </td>\r\n</tr>\r\n<tr valign=\"top\">\r\n    <td>" +
"\r\n        <hr />\r\n        <h3>Просмотр</h3>\r\n        ");


            
            #line 73 "..\..\Views\PersonSelectUsage\Index.cshtml"
   Write(Html.DisplayFor(m => m.Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n        <h3>Форма редактирования</h3>\r\n");


            
            #line 76 "..\..\Views\PersonSelectUsage\Index.cshtml"
         using (var form = Html.BeginForm())
        {
            
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\PersonSelectUsage\Index.cshtml"
       Write(Html.EditorFor(m => m.Model));

            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\PersonSelectUsage\Index.cshtml"
                                         ;
        }

            
            #line default
            #line hidden
WriteLiteral("    </td>\r\n</tr>\r\n</table>\r\n</div>\r\n\r\n");


            
            #line 85 "..\..\Views\PersonSelectUsage\Index.cshtml"
Write(Html.CommonScriptCode("PersonControls_Usage",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden

WriteLiteralTo(@__razor_template_writer, "<script>\r\n\t$(function () {\r\n\t\t");



WriteLiteralTo(@__razor_template_writer, "\r\n\t\t$(window).resize(function() {\r\n\t\t\tvar $parent = $(\"#dialogContentPane\");\r\n\t\t\t" +
"$(\"#container\").width($parent.width())\r\n\t\t\t$(\"#container\").height($parent.height" +
"())\r\n\t\t});\r\n\r\n\r\n\t});\r\n</script>");


            
            #line 99 "..\..\Views\PersonSelectUsage\Index.cshtml"
       })));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 100 "..\..\Views\PersonSelectUsage\Index.cshtml"
  
	
	Html.RegisterScript(@"
		
		;(function(scope, $) {{
			scope.ViewModel.Model.ShipperID.__SearchParameters.PersonHowSearch(1); // начинается с
			scope.ViewModel.Model.ShipperID.__SearchParameters.PersonType(1); // является юр лицом
//			scope.ViewModel.Model.ShipperID.__SearchParameters.IsBank(false); // не является банком
//			scope.ViewModel.Model.ResponsibleID.__SearchParameters.HowSearch(1); // начинается с
//			scope.ViewModel.Model.ResponsibleID.__SearchParameters.PersonTypes.push(2); // является физ лицом
//			scope.ViewModel.Model.BankID.__SearchParameters.HowSearch(1); // начинается с
//			scope.ViewModel.Model.BankID.__SearchParameters.IsBank(true); // является банком
		}})(window, jQuery);
		
	".FormatWith(""));


            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
