#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\AppCommon.cshtml"
    using Kesco.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\AppCommon.cshtml"
    using Kesco.Web.Mvc.SharedViews;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\AppCommon.cshtml"
    using Kesco.Web.Mvc.SharedViews.Localization;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/AppCommon.cshtml")]
    public partial class _Views_Shared_AppCommon_cshtml : Kesco.Web.Mvc.SharedViews.SharedViewPage<DialogViewModel>
    {
        public _Views_Shared_AppCommon_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\AppCommon.cshtml"
   
	var scriptCapabilities = Model.GetScriptCapabilities();

            
            #line default
            #line hidden
WriteLiteral("\r\n<img");

WriteAttribute("src", Tuple.Create(" src=\"", 242), Tuple.Create("\"", 279)
            
            #line 8 "..\..\Views\Shared\AppCommon.cshtml"
, Tuple.Create(Tuple.Create("", 248), Tuple.Create<System.Object, System.Int32>(WebAssetImage("sandwatch.gif")
            
            #line default
            #line hidden
, 248), false)
);

WriteLiteral(" id=\"imgBusy\"");

WriteLiteral(" style=\"display: none; position: absolute; top: 1px; z-index: 2000;\"");

WriteLiteral(" />\r\n<text>\r\n<style>\r\n\t.ui-equipment-type-20 { display: inline-block; width: 20px" +
"; height: 20px; background: url(\'");

            
            #line 11 "..\..\Views\Shared\AppCommon.cshtml"
                                                                                       Write(WebAssetImage("phoneDigital.gif"));

            
            #line default
            #line hidden
WriteLiteral("\') center center no-repeat no-repeat; }\r\n\t.ui-equipment-type-21 { display: inline" +
"-block; width: 20px; height: 20px; background: url(\'");

            
            #line 12 "..\..\Views\Shared\AppCommon.cshtml"
                                                                                       Write(WebAssetImage("phoneStandard.gif"));

            
            #line default
            #line hidden
WriteLiteral("\') center center no-repeat no-repeat; }\r\n\t.ui-equipment-type-24 { display: inline" +
"-block; width: 20px; height: 20px; background: url(\'");

            
            #line 13 "..\..\Views\Shared\AppCommon.cshtml"
                                                                                       Write(WebAssetImage("phoneDect.gif"));

            
            #line default
            #line hidden
WriteLiteral("\') center center no-repeat no-repeat; }\r\n\t.ui-equipment-type-30 { display: inline" +
"-block; width: 20px; height: 20px; background: url(\'");

            
            #line 14 "..\..\Views\Shared\AppCommon.cshtml"
                                                                                       Write(WebAssetImage("phoneIP.gif"));

            
            #line default
            #line hidden
WriteLiteral("\') center center no-repeat no-repeat; }\r\n</style>\r\n\r\n\r\n<div");

WriteLiteral(" id=\"PhoneCalling_Dialog\"");

WriteAttribute("title2", Tuple.Create(" title2=\"", 1087), Tuple.Create("\"", 1173)
            
            #line 18 "..\..\Views\Shared\AppCommon.cshtml"
, Tuple.Create(Tuple.Create("", 1096), Tuple.Create<System.Object, System.Int32>(Kesco.Web.Mvc.SharedViews.Localization.Resources.PhoneCalling_Dialog_Title
            
            #line default
            #line hidden
, 1096), false)
);

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n\t<form");

WriteLiteral(" onsubmit=\"return false;\"");

WriteLiteral(">\r\n\r\n\t</form>\r\n</div>\r\n");

            
            #line 23 "..\..\Views\Shared\AppCommon.cshtml"
  
	Html.RegisterExternalScript("ScriptController_AppEnv", Url.Action("AppEnv", "Script"));
	Html.RegisterExternalScript("ScriptController_AppCommon", Url.Action("AppCommon", "Script"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 28 "..\..\Views\Shared\AppCommon.cshtml"
Write(Html.ExternalScript("Shared_ViewModel",
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "<script>\r\n    var kesco_ip = \'");

            
            #line 30 "..\..\Views\Shared\AppCommon.cshtml"
WriteTo(__razor_template_writer, Request.ServerVariables["HTTP_X_FORWARDED_FOR"] ?? Request.ServerVariables["REMOTE_ADDR"]);

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\';\r\n\t; (function (scope, $, undefined) {\r\n\t\tvar env = window.Env || {}; scope.Env" +
" = env; env.scriptCapabilities = ");

            
            #line 32 "..\..\Views\Shared\AppCommon.cshtml"
                                         WriteTo(__razor_template_writer, Html.Raw(Kesco.Web.Mvc.Json.Serialize(scriptCapabilities, true)));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, ";\r\n\r\n\t\t// Сделать глобальной\r\n\t\tvar vm = scope.ViewModel || {};\tscope.ViewModel =" +
" vm;\r\n\r\n\t\t// Установим данные для модели представления\r\n\t\tko.mapping.fromJS(");

            
            #line 38 "..\..\Views\Shared\AppCommon.cshtml"
WriteTo(__razor_template_writer, Html.Raw((Kesco.Web.Mvc.Json.Serialize(Model, true) ?? String.Empty).Replace("<script", "<scr\"+\"ipt").Replace("</script", "</scr\"+\"ipt")));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, ", {}, vm);\r\n\r\n\t\tvm.dispatchModelCommand = function (command, control, replaceOpti" +
"ons) {\r\n\t\t\t\r\n\t\t\tvar requestOptions = $.extend({\r\n\t\t\t\t\turl: \'");

            
            #line 43 "..\..\Views\Shared\AppCommon.cshtml"
WriteTo(__razor_template_writer, Url.Action("Dispatch"));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, @"',
					type: 'POST',
					data: window.ko.toJSON({
						command: command,
						control: control || null,
						model: ko.mapping.toJS(vm.Model)
					}),
					contentType: ""application/json; charset=utf-8""
				},
				replaceOptions || {}
			);

			return $.ajax(requestOptions);
		}

	})(window, jQuery);

</script>");

            
            #line 60 "..\..\Views\Shared\AppCommon.cshtml"
       })));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
